/**
 * Jest setup: mock native modules that pure-logic tests pull in transitively
 * (lib/supabase imports AsyncStorage at module load). Official mock per the
 * @react-native-async-storage docs.
 */
jest.mock('@react-native-async-storage/async-storage', () =>
  require('@react-native-async-storage/async-storage/jest/async-storage-mock'),
);

/**
 * expo-crypto's own autogenerated jest mock (node_modules/expo-crypto/mocks)
 * is a dumb stub -- digestStringAsync always returns '', randomUUID returns
 * undefined. Any test that actually exercises signing/hashing needs a real
 * digest, so this swaps in Node's built-in crypto instead.
 */
jest.mock('expo-crypto', () => {
  const nodeCrypto = require('crypto');
  return {
    CryptoDigestAlgorithm: { SHA256: 'SHA256' },
    digestStringAsync: async (_algorithm, str) =>
      nodeCrypto.createHash('sha256').update(str).digest('hex'),
    randomUUID: () => nodeCrypto.randomUUID(),
  };
});
