import React from 'react';
import { FlatList, Text } from 'react-native';
import { act, create } from 'react-test-renderer';
import CirclesDirectory, { type CirclesDirectoryProps } from '../CirclesDirectory';
import CircleCard from '../CircleCard';
import SuggestionCard from '../SuggestionCard';
import CirclesSummaryHeader from '../CirclesSummaryHeader';
import CirclesEmptyState from '../CirclesEmptyState';
import { AfterglowFallbackFonts } from '../../../../constants/Typography';
const mockPush=jest.fn(), mockRefetch=jest.fn(), mockMutate=jest.fn(), mockRetry=jest.fn();
const mockCircleRead=jest.fn(), mockSuggestionRead=jest.fn(), mockPreviewRead=jest.fn();
let mockUser:string|null='alice', mockEpoch=0, mockFocused=true, mockAccountError:Error|null=null;
let mockLoading=false, mockError=false, mockRefreshing=false, mockCircles:any[]=[], mockSuggestions:any[]=[];
jest.mock('expo-router',()=>({useRouter:()=>({push:mockPush})}));
jest.mock('@react-navigation/native',()=>({useIsFocused:()=>mockFocused}));
jest.mock('../../../../hooks/useObservedUser',()=>({useObservedUser:()=>{const epoch=mockEpoch;return{viewerId:mockUser,epoch,isLoading:false,error:mockAccountError,isCurrent:()=>epoch===mockEpoch,retry:mockRetry};}}));
jest.mock('../../../../hooks/useMyCircles',()=>({useMyCircles:(id:any,scope:any)=>{mockCircleRead(id,scope);return{data:mockCircles,isLoading:mockLoading,isError:mockError,isRefetching:mockRefreshing,refetch:mockRefetch};}}));
jest.mock('../../../../hooks/useCircleMemberPreviews',()=>({useCircleMemberPreviews:(ids:any,id:any,scope:any)=>{mockPreviewRead(ids,id,scope);return{data:{}};}}));
jest.mock('../../../../hooks/useCircleSuggestions',()=>({useCircleSuggestions:(id:any,scope:any)=>{mockSuggestionRead(id,scope);return{data:mockSuggestions};},useSetSuggestionStatus:()=>({mutateAsync:mockMutate}),isObsoleteCircleSuggestion:(e:any)=>e?.obsolete===true}));
jest.mock('../CircleCard',()=>({__esModule:true,default:(p:any)=>require('react').createElement('CircleRow',p)}));
jest.mock('../SuggestionCard',()=>({__esModule:true,default:(p:any)=>require('react').createElement('SuggestionRow',p)}));
jest.mock('../CirclesSummaryHeader',()=>({__esModule:true,default:(p:any)=>require('react').createElement('Summary',p)}));
jest.mock('../CirclesEmptyState',()=>({__esModule:true,default:(p:any)=>require('react').createElement('EmptyCircles',p)}));
jest.mock('../../../SkeletonCard',()=>({SkeletonCircles:()=>null}));
const appearance={fonts:AfterglowFallbackFonts},cleanup:Array<()=>void>=[];
const circle=(id:string,name:string,count:number)=>({id,name,member_count:count,last_message_at:null});
const suggestion=(id='s1')=>({id,suggested_user_ids:['bea','cam'],shared_count:3,shared_event_ids:['p1'],people:[]});
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
async function flush(){await act(async()=>{for(let i=0;i<8;i++)await Promise.resolve();});}
function render(extra:Partial<CirclesDirectoryProps>={}){let props:CirclesDirectoryProps={userId:'alice',hasPeople:true,onCreate:jest.fn(),onAddPeople:jest.fn(),onOpenCircle:jest.fn(),appearance,...extra};let tree!:ReturnType<typeof create>,alive=true;act(()=>{tree=create(<CirclesDirectory {...props}/>);});const unmount=()=>{if(alive)act(()=>tree.unmount());alive=false;};cleanup.push(unmount);return{tree,unmount,get props(){return props;},update(next:Partial<CirclesDirectoryProps>={}){props={...props,...next};act(()=>tree.update(<CirclesDirectory {...props}/>));},suggestion:(id='s1')=>tree.root.findAllByType(SuggestionCard).find(n=>n.props.suggestion.id===id),text:()=>tree.root.findAllByType(Text).flatMap(n=>n.props.children).join(' '),button:(label:string)=>tree.root.findAll(n=>n.props.accessibilityLabel===label&&typeof n.props.onPress==='function')[0]};}
beforeEach(()=>{jest.clearAllMocks();mockUser='alice';mockEpoch=0;mockFocused=true;mockAccountError=null;mockLoading=false;mockError=false;mockRefreshing=false;mockCircles=[circle('first','Coffee friends',4)];mockSuggestions=[];mockMutate.mockReset().mockResolvedValue('dismissed');mockRefetch.mockReset().mockResolvedValue({data:mockCircles});});
afterEach(()=>cleanup.splice(0).forEach(fn=>fn()));
it('keeps source order and named pairs, excluding only unnamed two-person DMs',()=>{mockCircles=[circle('z','Named pair',2),circle('dm','',2),circle('a','',3)];const f=render();expect(f.tree.root.findByType(FlatList).props.data.map((c:any)=>c.id)).toEqual(['z','a']);expect(f.tree.root.findByType(CirclesSummaryHeader).props.count).toBe(2);expect(f.tree.root.findAllByType(CircleCard).every(n=>n.props.appearance===appearance)).toBe(true);});
it('keeps the existing circle and create callbacks',()=>{const f=render();act(()=>f.tree.root.findByType(CircleCard).props.onPress('first'));expect(f.props.onOpenCircle).toHaveBeenCalledWith('first');act(()=>f.tree.root.findByType(CirclesSummaryHeader).props.onCreate());expect(f.props.onCreate).toHaveBeenCalledTimes(1);});
it.each([true,false])('keeps hasPeople=%s and both empty actions intact',hasPeople=>{mockCircles=[];const f=render({hasPeople});const empty=f.tree.root.findByType(CirclesEmptyState);expect(empty.props.hasPeople).toBe(hasPeople);act(()=>{empty.props.onCreate();empty.props.onAddPeople();});expect(f.props.onCreate).toHaveBeenCalledTimes(1);expect(f.props.onAddPeople).toHaveBeenCalledTimes(1);});
it('shows suggestions even when there are no joined circles',()=>{mockCircles=[];mockSuggestions=[suggestion()];const f=render();expect(f.suggestion()).toBeDefined();expect(f.tree.root.findAllByType(CirclesEmptyState)).toHaveLength(0);});
it('keeps suggestion seed and id, without marking it converted on Start',()=>{mockSuggestions=[suggestion()];const f=render();const row=f.suggestion()!.props;act(()=>{row.onStart(row.suggestion);row.onStart(row.suggestion);});expect(mockPush).toHaveBeenCalledTimes(1);expect(mockPush).toHaveBeenCalledWith('/circle/new?seed=bea,cam&suggestion=s1');expect(mockMutate).not.toHaveBeenCalled();});
it('locks repeated dismiss and Start taps until confirmation, then hides only that suggestion',async()=>{mockSuggestions=[suggestion(),suggestion('s2')];const gate=deferred<string>();mockMutate.mockReturnValueOnce(gate.promise);const f=render();const row=f.suggestion()!.props;act(()=>{row.onDismiss(row.suggestion);row.onDismiss(row.suggestion);row.onStart(row.suggestion);});expect(mockMutate).toHaveBeenCalledTimes(1);expect(mockPush).not.toHaveBeenCalled();expect(f.suggestion()!.props.dismissPending).toBe(true);expect(mockMutate.mock.calls[0][0]).toEqual({id:'s1',status:'dismissed'});expect(mockMutate.mock.calls[0][1].scope.canDispatch()).toBe(true);gate.resolve('dismissed');await flush();expect(f.suggestion()).toBeUndefined();expect(f.suggestion('s2')).toBeDefined();});
it('failed dismissal stays visible with retry and clears the failure after confirmation',async()=>{mockSuggestions=[suggestion()];mockMutate.mockRejectedValueOnce(new Error('offline'));const f=render();act(()=>f.suggestion()!.props.onDismiss(suggestion()));await flush();expect(f.suggestion()!.props.dismissError).toContain('Couldn’t dismiss');expect(f.suggestion()!.props.dismissPending).toBe(false);act(()=>f.suggestion()!.props.onDismiss(suggestion()));await flush();expect(mockMutate).toHaveBeenCalledTimes(2);expect(f.suggestion()).toBeUndefined();});
it.each(['not_found',null,'unexpected'])('does not hide a suggestion for an unconfirmed %s receipt',async result=>{mockSuggestions=[suggestion()];mockMutate.mockResolvedValueOnce(result);const f=render();act(()=>f.suggestion()!.props.onDismiss(suggestion()));await flush();expect(f.suggestion()!.props.dismissError).toContain('Couldn’t dismiss');});
it.each(['account','unmount','focus'])('retires a pending dismissal on %s without poisoning the next visit',async kind=>{mockSuggestions=[suggestion()];const gate=deferred<string>();mockMutate.mockReturnValueOnce(gate.promise);const f=render();act(()=>f.suggestion()!.props.onDismiss(suggestion()));const scope=mockMutate.mock.calls[0][1].scope;if(kind==='account'){mockUser='bob';mockEpoch++;f.update({userId:'bob'});}if(kind==='unmount')f.unmount();if(kind==='focus'){mockFocused=false;f.update();mockFocused=true;f.update();}expect(scope.isCurrent()).toBe(false);gate.resolve('dismissed');await flush();if(kind!=='unmount'){expect(f.suggestion()).toBeDefined();expect(f.suggestion()!.props.dismissPending).not.toBe(true);}});
it('rechecks whether the suggestion still exists before deferred dispatch',()=>{mockSuggestions=[suggestion()];mockMutate.mockReturnValue(new Promise(()=>{}));const f=render();act(()=>f.suggestion()!.props.onDismiss(suggestion()));const scope=mockMutate.mock.calls[0][1].scope;mockSuggestions=[];f.update();expect(scope.canDispatch()).toBe(false);});
it('retired suggestion callbacks cannot start or dismiss after account change',()=>{mockSuggestions=[suggestion()];const f=render();const old=f.suggestion()!.props;mockUser='bob';mockEpoch++;f.update({userId:'bob'});act(()=>{old.onStart(old.suggestion);old.onDismiss(old.suggestion);});expect(mockPush).not.toHaveBeenCalled();expect(mockMutate).not.toHaveBeenCalled();});
it('loading and failed reads never appear as an empty directory',()=>{mockCircles=[];mockLoading=true;const f=render();expect(f.text()).toContain('Loading your circles');expect(f.tree.root.findAllByType(CirclesEmptyState)).toHaveLength(0);mockLoading=false;mockError=true;f.update();expect(f.text()).toContain("Your circles didn't load");expect(f.tree.root.findAllByType(CirclesEmptyState)).toHaveLength(0);});
it('retries a directory failure once per pending attempt',async()=>{mockError=true;const gate=deferred<any>();mockRefetch.mockReturnValueOnce(gate.promise);const f=render();const press=f.button('Try again').props.onPress;act(()=>{press();press();});expect(mockRefetch).toHaveBeenCalledTimes(1);gate.resolve({data:mockCircles});await flush();expect(f.button('Try again').props.disabled).toBe(false);});
it('account uncertainty hides data and offers account retry',()=>{mockAccountError=new Error('offline');const f=render();expect(f.tree.root.findAllByType(CircleCard)).toHaveLength(0);act(()=>f.button('Try again to check account').props.onPress());expect(mockRetry).toHaveBeenCalledTimes(1);});

it('all directory reads share one account generation and retire it after account change',()=>{const f=render();const old=mockCircleRead.mock.calls.at(-1)[1];expect(old.userId).toBe('alice');expect(old.epoch).toBe(0);expect(old.isCurrent()).toBe(true);expect(mockSuggestionRead.mock.calls.at(-1)[1]).toBe(old);expect(mockPreviewRead.mock.calls.at(-1)[2]).toBe(old);mockFocused=false;f.update();expect(old.isCurrent()).toBe(true);mockUser='bob';mockEpoch++;f.update({userId:'bob'});expect(old.isCurrent()).toBe(false);expect(mockCircleRead.mock.calls.at(-1)[1].userId).toBe('bob');});
it('does not enable directory reads while the account is uncertain',()=>{mockAccountError=new Error('offline');render();expect(mockCircleRead.mock.calls.at(-1)[0]).toBeNull();expect(mockSuggestionRead.mock.calls.at(-1)[0]).toBeNull();expect(mockPreviewRead.mock.calls.at(-1)[1]).toBeNull();});

it('Start uses the refreshed suggestion members when its id is unchanged',()=>{mockSuggestions=[suggestion()];const f=render();const old=f.suggestion()!.props;mockSuggestions=[{...suggestion(),suggested_user_ids:['dee','erin']}];f.update();act(()=>old.onStart(old.suggestion));expect(mockPush).toHaveBeenCalledWith('/circle/new?seed=dee,erin&suggestion=s1');expect(mockMutate).not.toHaveBeenCalled();});
