import React from 'react';
import { Text } from 'react-native';
import { act, create } from 'react-test-renderer';
import CreateCircleFlow from '../CreateCircleFlow';
import PeopleStep from '../PeopleStep';
import IdentityStep from '../IdentityStep';
import PermissionsStep from '../PermissionsStep';
import { AfterglowFallbackFonts } from '../../../../constants/Typography';
const mockBack=jest.fn(),mockReplace=jest.fn(),mockCreate=jest.fn(),mockRetrySetup=jest.fn(),mockConvert=jest.fn(),mockPick=jest.fn(),mockRefetch=jest.fn(),mockAccountRetry=jest.fn();
let mockUser:string|null='alice',mockEpoch=0,mockFocused=true,mockAccountError:Error|null=null,mockAccountLoading=false,mockLoading=false,mockError=false,mockPeople:any[]=[],mockParams:any={};
jest.mock('expo-router',()=>({useRouter:()=>({back:mockBack,replace:mockReplace}),useLocalSearchParams:()=>mockParams}));
jest.mock('@react-navigation/native',()=>({useIsFocused:()=>mockFocused}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaView:(p:any)=>require('react').createElement('SafeArea',p,p.children),useSafeAreaInsets:()=>({top:0,bottom:20,left:0,right:0})}));
jest.mock('../../../../hooks/useObservedUser',()=>({useObservedUser:()=>{const epoch=mockEpoch;return{viewerId:mockUser,epoch,isLoading:mockAccountLoading,error:mockAccountError,retry:mockAccountRetry,isCurrent:()=>epoch===mockEpoch};}}));
jest.mock('../../../../hooks/useYoursGrid',()=>({useYoursGrid:()=>({data:mockPeople,isLoading:mockLoading,isError:mockError,refetch:mockRefetch})}));
jest.mock('../../../../hooks/useCreateCircle',()=>({useCreateCircle:()=>({mutateAsync:mockCreate,retrySetupAsync:mockRetrySetup,isPending:false}),isObsoleteCircleCreation:(e:any)=>e?.obsolete===true,isUnconfirmedCircleCreation:(e:any)=>e?.unconfirmed===true}));
jest.mock('../../../../hooks/useCircleSuggestions',()=>({useSetSuggestionStatus:()=>({mutateAsync:mockConvert})}));
jest.mock('../../../../lib/circles/pickCover',()=>({pickCoverPhoto:()=>mockPick()}));
jest.mock('../../../../lib/haptics',()=>({hapticSelection:jest.fn()}));
jest.mock('../PeopleStep',()=>({__esModule:true,default:(p:any)=>require('react').createElement('PeopleStep',p)}));
jest.mock('../IdentityStep',()=>({__esModule:true,default:(p:any)=>require('react').createElement('IdentityStep',p)}));
jest.mock('../PermissionsStep',()=>({__esModule:true,default:(p:any)=>require('react').createElement('PermissionsStep',p)}));
const appearance={fonts:AfterglowFallbackFonts},cleanup:Array<()=>void>=[];
const complete={circleId:'00000000-0000-0000-0000-000000000001',policyApplied:true,coverApplied:true};
const person=(id:string)=>({user_id:id,first_name_display:id,handle:id,profile_photo_url:null});
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
async function flush(){await act(async()=>{for(let i=0;i<10;i++)await Promise.resolve();});}
function render(){let tree!:ReturnType<typeof create>,alive=true;act(()=>{tree=create(<CreateCircleFlow appearance={appearance}/>);});const unmount=()=>{if(alive)act(()=>tree.unmount());alive=false;};cleanup.push(unmount);return{tree,unmount,update:()=>act(()=>tree.update(<CreateCircleFlow appearance={appearance}/>)),people:()=>tree.root.findByType(PeopleStep).props,identity:()=>tree.root.findByType(IdentityStep).props,permissions:()=>tree.root.findByType(PermissionsStep).props,button:(label:string)=>tree.root.findAll(n=>n.props.accessibilityLabel===label&&typeof n.props.onPress==='function')[0],text:()=>tree.root.findAllByType(Text).flatMap(n=>n.props.children).join(' ')};}
function select(f:ReturnType<typeof render>,ids=['bea','cam']){act(()=>ids.forEach(id=>f.people().onToggle(id)));}
function identity(f:ReturnType<typeof render>){select(f);act(()=>f.button('Next').props.onPress());act(()=>{f.identity().onName('  Saturday friends  ');f.identity().onDescription('  Coffee then a walk  ');});}
function permissions(f:ReturnType<typeof render>){identity(f);act(()=>f.button('Next').props.onPress());}
beforeEach(()=>{jest.clearAllMocks();mockUser='alice';mockEpoch=0;mockFocused=true;mockAccountError=null;mockAccountLoading=false;mockLoading=false;mockError=false;mockParams={};mockPeople=['bea','cam','dee'].map(person);mockCreate.mockReset().mockResolvedValue(complete);mockRetrySetup.mockReset().mockResolvedValue(complete);mockConvert.mockReset().mockResolvedValue('converted');mockPick.mockReset().mockResolvedValue(null);mockRefetch.mockReset().mockResolvedValue({data:mockPeople});});
afterEach(()=>cleanup.splice(0).forEach(fn=>fn()));
it('keeps two-other-person and required-name gates, with optional photo/description',async()=>{const f=render();expect(f.button('Next').props.disabled).toBe(true);act(()=>f.button('Next').props.onPress());expect(f.people()).toBeDefined();select(f,['bea']);expect(f.button('Next').props.disabled).toBe(true);select(f,['cam']);act(()=>f.button('Next').props.onPress());expect(f.button('Next').props.disabled).toBe(true);act(()=>f.identity().onName('Friends'));act(()=>f.button('Next').props.onPress());act(()=>f.button('Create circle').props.onPress());await flush();expect(mockCreate.mock.calls[0][0]).toMatchObject({name:'Friends',description:null,coverBase64:null,memberUserIds:['bea','cam']});});
it('applies seed only once and only for visible accepted people',()=>{mockParams={seed:'bea,unknown,cam',suggestion:'s1'};const f=render();expect([...f.people().selected]).toEqual(['bea','cam']);act(()=>f.people().onToggle('bea'));mockPeople=[...mockPeople];f.update();expect([...f.people().selected]).toEqual(['cam']);expect(f.people().selected.has('unknown')).toBe(false);});
it.each(['only_me','chosen','everyone'])('preserves %s policy and actual admin selections',async policy=>{const f=render();permissions(f);act(()=>{f.permissions().onPolicy(policy);f.permissions().onToggleAdmin('bea');f.permissions().onToggleAdmin('invisible');});act(()=>f.button('Create circle').props.onPress());await flush();expect(mockCreate.mock.calls[0][0]).toMatchObject({name:'Saturday friends',description:'Coffee then a walk',memberUserIds:['bea','cam'],invitePolicy:policy,adminUserIds:policy==='chosen'?['bea']:[]});});
it('deselecting a member also removes chosen administration',async()=>{const f=render();permissions(f);act(()=>{f.permissions().onPolicy('chosen');f.permissions().onToggleAdmin('bea');});act(()=>f.button('Back').props.onPress());act(()=>f.button('Back').props.onPress());act(()=>{f.people().onToggle('bea');f.people().onToggle('dee');});act(()=>f.button('Next').props.onPress());act(()=>f.button('Next').props.onPress());act(()=>f.button('Create circle').props.onPress());await flush();expect(mockCreate.mock.calls[0][0]).toMatchObject({memberUserIds:['cam','dee'],adminUserIds:[]});});
it('removes no-longer-accepted selections before submit',()=>{const f=render();permissions(f);mockPeople=['bea','dee'].map(person);f.update();act(()=>f.button('Create circle').props.onPress());expect(mockCreate).not.toHaveBeenCalled();expect([...f.people().selected]).toEqual(['bea']);});
it('a repeated old Next press advances only one step',()=>{const f=render();identity(f);act(()=>f.button('Back').props.onPress());const press=f.button('Next').props.onPress;act(()=>{press();press();});expect(f.identity()).toBeDefined();});
it('locks create immediately before hook pending can rerender',async()=>{const gate=deferred<any>();mockCreate.mockReturnValueOnce(gate.promise);const f=render();permissions(f);const press=f.button('Create circle').props.onPress;act(()=>{press();press();});expect(mockCreate).toHaveBeenCalledTimes(1);expect(f.button('Creating circle…').props.disabled).toBe(true);gate.resolve(complete);await flush();expect(mockReplace).toHaveBeenCalledTimes(1);expect(mockReplace).toHaveBeenCalledWith(`/circle/${complete.circleId}`);});
it('a definite create failure preserves the draft for a retry',async()=>{mockCreate.mockRejectedValueOnce(new Error('rejected'));const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());await flush();expect(f.text()).toContain("Couldn't make the circle");expect(f.permissions().circleName).toBe('Saturday friends');act(()=>f.button('Create circle').props.onPress());await flush();expect(mockCreate).toHaveBeenCalledTimes(2);expect(mockCreate.mock.calls[1][0]).toEqual(mockCreate.mock.calls[0][0]);});
it('unconfirmed creation offers View circles without another create attempt',async()=>{mockCreate.mockRejectedValueOnce({unconfirmed:true});const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());await flush();expect(f.text()).toContain('Check your circles');expect(f.button('Create circle')).toBeUndefined();act(()=>f.button('View circles').props.onPress());expect(mockBack).toHaveBeenCalledTimes(1);expect(mockCreate).toHaveBeenCalledTimes(1);});
it('partial setup retains the ID and retries only setup',async()=>{mockCreate.mockResolvedValueOnce({...complete,policyApplied:false,coverApplied:false});const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());await flush();expect(f.text()).toContain('Circle created');expect(f.text()).toContain('Who can add people');expect(f.text()).toContain('Cover photo');expect(mockReplace).not.toHaveBeenCalled();act(()=>f.button('Try again').props.onPress());await flush();expect(mockRetrySetup).toHaveBeenCalledWith(complete.circleId);expect(mockCreate).toHaveBeenCalledTimes(1);expect(mockReplace).toHaveBeenCalledWith(`/circle/${complete.circleId}`);});
it('partial setup can open its existing circle without retrying',async()=>{mockCreate.mockResolvedValueOnce({...complete,coverApplied:false});const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());await flush();act(()=>f.button('View circle').props.onPress());expect(mockReplace).toHaveBeenCalledWith(`/circle/${complete.circleId}`);expect(mockRetrySetup).not.toHaveBeenCalled();});
it('seed conversion happens only after confirmed create and does not turn failure into create failure',async()=>{mockParams={seed:'bea,cam',suggestion:'s1'};const gate=deferred<any>();mockCreate.mockReturnValueOnce(gate.promise);mockConvert.mockRejectedValueOnce(new Error('offline'));const f=render();act(()=>f.button('Next').props.onPress());act(()=>f.identity().onName('Friends'));act(()=>f.button('Next').props.onPress());act(()=>f.button('Create circle').props.onPress());expect(mockConvert).not.toHaveBeenCalled();gate.resolve(complete);await flush();expect(mockConvert.mock.calls[0][0]).toEqual({id:'s1',status:'converted'});expect(mockReplace).toHaveBeenCalledWith(`/circle/${complete.circleId}`);});
it('photo errors stay inline, and cancelling a new pick preserves the previous cover',async()=>{const f=render();identity(f);mockPick.mockRejectedValueOnce(new Error('offline'));act(()=>f.identity().onPickCover());await flush();expect(f.identity().pickError).toContain('Couldn’t open');mockPick.mockResolvedValueOnce({base64:'photo-data',uri:'file:///photo.jpg'});act(()=>f.identity().onPickCover());await flush();expect(f.identity().coverPreviewUri).toBe('file:///photo.jpg');act(()=>f.identity().onPickCover());await flush();expect(f.identity().coverPreviewUri).toBe('file:///photo.jpg');});
it('a late photo cannot attach after leaving and returning to identity',async()=>{const gate=deferred<any>();mockPick.mockReturnValueOnce(gate.promise);const f=render();identity(f);act(()=>f.identity().onPickCover());act(()=>f.button('Back').props.onPress());gate.resolve({base64:'old',uri:'file:///old.jpg'});await flush();act(()=>f.button('Next').props.onPress());expect(f.identity().coverPreviewUri).toBeNull();});
it.each(['account','focus','close','unmount'])('late creation cannot navigate from retired %s entry',async kind=>{const gate=deferred<any>();mockCreate.mockReturnValueOnce(gate.promise);const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());const scope=mockCreate.mock.calls[0][1].scope;if(kind==='account'){mockUser='bob';mockEpoch++;f.update();}if(kind==='focus'){mockFocused=false;f.update();mockFocused=true;f.update();}if(kind==='close')act(()=>f.button('Close circle creation').props.onPress());if(kind==='unmount')f.unmount();expect(scope.isCurrent()).toBe(false);gate.resolve(complete);await flush();expect(mockReplace).not.toHaveBeenCalled();expect(mockConvert).not.toHaveBeenCalled();});
it('new account and new seed get a fresh draft',()=>{const f=render();identity(f);mockUser='bob';mockEpoch++;mockParams={seed:'cam,dee'};f.update();expect([...f.people().selected]).toEqual(['cam','dee']);act(()=>f.button('Next').props.onPress());expect(f.identity().name).toBe('');expect(f.identity().coverPreviewUri).toBeNull();});
it('people loading and error stay distinct from no people and retry retains the flow',async()=>{mockPeople=[];mockLoading=true;const f=render();expect(f.text()).toContain('Loading your people');expect(f.tree.root.findAllByType(PeopleStep)).toHaveLength(0);mockLoading=false;mockError=true;f.update();expect(f.text()).toContain('Your people didn’t load');act(()=>f.button('Try again').props.onPress());await flush();expect(mockRefetch).toHaveBeenCalledTimes(1);});

it('confirmed success has truthful Finishing copy while conversion waits',async()=>{mockParams={seed:'bea,cam',suggestion:'s1'};const gate=deferred<string>();mockConvert.mockReturnValueOnce(gate.promise);const f=render();act(()=>f.button('Next').props.onPress());act(()=>f.identity().onName('Friends'));act(()=>f.button('Next').props.onPress());act(()=>f.button('Create circle').props.onPress());await flush();expect(f.text()).toContain('Your circle is ready.');expect(f.text()).toContain('Finishing…');expect(f.text()).not.toContain('couldn’t finish');expect(f.button('Create circle')).toBeUndefined();gate.resolve('converted');await flush();expect(mockReplace).toHaveBeenCalledTimes(1);});
it('completed setup retry and View circle each ignore repeated immediate taps',async()=>{mockCreate.mockResolvedValueOnce({...complete,coverApplied:false});const gate=deferred<any>();mockRetrySetup.mockReturnValueOnce(gate.promise);const f=render();permissions(f);act(()=>f.button('Create circle').props.onPress());await flush();const retry=f.button('Try again').props.onPress;act(()=>{retry();retry();});expect(mockRetrySetup).toHaveBeenCalledTimes(1);const view=f.button('View circle').props.onPress;act(()=>{view();view();});expect(mockReplace).toHaveBeenCalledTimes(1);gate.resolve(complete);await flush();expect(mockReplace).toHaveBeenCalledTimes(1);expect(mockCreate).toHaveBeenCalledTimes(1);});
it('a completed old people retry cannot leave a returned visit stuck',async()=>{mockError=true;const gate=deferred<any>();mockRefetch.mockReturnValueOnce(gate.promise);const f=render();act(()=>f.button('Try again').props.onPress());mockFocused=false;f.update();mockFocused=true;f.update();gate.resolve({data:[]});await flush();expect(f.button('Try again').props.disabled).toBe(false);});
