import React from 'react';
import { Text, ScrollView, StyleSheet } from 'react-native';
import { act, create } from 'react-test-renderer';
import PersonProfilePage, { type PersonProfilePageProps } from '../PersonProfilePage';
import { AfterglowFallbackFonts, Fonts } from '../../../../constants/Typography';
import { AfterglowColors } from '../../../../constants/Colors';
import { buildComposerWithPerson } from '../../../../lib/composerLink';
import type { PersonProfile } from '../../../../lib/yours/types';
const mockProfile = jest.fn(), mockDm = jest.fn(), mockRemove = jest.fn(), mockBlock = jest.fn(), mockRefetch = jest.fn(), mockRetry = jest.fn(), mockPush = jest.fn(), mockBack = jest.fn();
let mockFocused = true, mockViewerId: string | null = 'alice', mockEpoch = 0, mockLoading = false, mockIdentityError: Error | null = null, mockBlocking = false;
jest.mock('react-native', () => {
  const actual = jest.requireActual('react-native'), React = require('react');
  const descriptors = Object.getOwnPropertyDescriptors(actual);
  descriptors.Pressable = { enumerable: true, configurable: true, value: React.forwardRef((props: any, ref: any) => {
    React.useImperativeHandle(ref, () => ({ measureInWindow: (fn: Function) => fn(300, 20, 44, 44) }));
    return require('react').createElement('ProfilePressable', props, props.children);
  }) };
  return Object.defineProperties({}, descriptors);
});
jest.mock('expo-router', () => ({ router: { push: (...args: unknown[]) => mockPush(...args), back: () => mockBack() } }));
jest.mock('@react-navigation/native', () => ({ useIsFocused: () => mockFocused }));
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: (props: any) => require('react').createElement('SafeArea', props, props.children) }));
jest.mock('lucide-react-native', () => Object.fromEntries(['ChevronLeft', 'MoreHorizontal', 'MessageCircle', 'CalendarPlus', 'UserMinus', 'Flag'].map(name => [name, () => null])));
jest.mock('expo-image', () => ({ Image: (props: any) => require('react').createElement('ProfileImage', props) }));
jest.mock('../../../../lib/haptics', () => ({ hapticSelection: jest.fn() }));
jest.mock('../../../../hooks/usePersonProfile', () => ({ usePersonProfile: (...args: unknown[]) => mockProfile(...args) }));
jest.mock('../../../../hooks/useObservedUser', () => ({ useObservedUser: () => { const epoch = mockEpoch; return { viewerId: mockViewerId, epoch, isLoading: mockLoading, error: mockIdentityError, isCurrent: () => epoch === mockEpoch, retry: mockRetry }; } }));
jest.mock('../../../../hooks/useGetOrCreateDm', () => ({ useGetOrCreateDm: () => ({ mutateAsync: mockDm }), isObsoleteDmOperation: (e: Error) => e.name === 'ObsoleteDmOperationError' }));
jest.mock('../../../../hooks/usePeopleConnectionMutations', () => ({ usePeopleConnectionMutations: () => ({ remove: { mutateAsync: mockRemove } }), isObsoletePeopleConnection: (e: Error) => e.name === 'ObsoletePeopleConnectionError' }));
jest.mock('../../../../hooks/useBlock', () => ({ useBlock: () => ({ blockUser: mockBlock, blocking: mockBlocking }) }));
jest.mock('../../../BrandedAlert', () => ({ BrandedAlert: (props: any) => require('react').createElement('ProfileAlert', props) }));
jest.mock('../../../menu/MenuCard', () => ({ __esModule: true, default: (props: any) => require('react').createElement('ProfileMenu', props) }));
const profile = (extra: Partial<PersonProfile> = {}): PersonProfile => ({ user_id: 'amelia', first_name_display: 'Amelia', handle: 'amelia', profile_photo_url: 'https://example.invalid/amelia.jpg', neighborhood: 'Santa Monica', bio: 'Coffee walks and music.', vibe_tags: ['Coffee'], phone_verified: true, joined_at: '2025-03-02T12:00:00Z', plans_created: 4, mutual_count: 2, mutual_faces: [{ user_id: 'jamie', first_name_display: 'Jamie', profile_photo_url: 'https://example.invalid/jamie.jpg' }], is_new: false, upcoming: [{ event_id: 'next-plan', title: 'A sunset walk', start_time: '2026-09-20T21:00:00Z', neighborhood: 'Ocean Park' }], upcoming_count: 1, past: [{ event_id: 'past-plan', title: 'Coffee last week', date: '2026-09-10T21:00:00Z' }], past_total: 3, ...extra });
let result: { data: PersonProfile | null; isLoading: boolean; isFetching: boolean; isError: boolean; refetch: typeof mockRefetch };
const cleanup: Array<() => void> = [];
function deferred<T>() { let resolve!: (value: T) => void, reject!: (error: Error) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
function mount(extra: Partial<PersonProfilePageProps> = {}) {
  let props: PersonProfilePageProps = { userId: 'alice', targetId: 'amelia', appearance: { fonts: AfterglowFallbackFonts }, ...extra };
  let tree!: ReturnType<typeof create>; act(() => { tree = create(<PersonProfilePage {...props}/>, { createNodeMock: () => ({ measureInWindow: (fn: Function) => fn(300, 20, 44, 44) }) }); });
  let closed = false; const unmount = () => { if (!closed) act(() => tree.unmount()); closed = true; }; cleanup.push(unmount);
  const button = (label: string) => tree.root.findAll(n => n.props.accessibilityLabel === label && typeof n.props.onPress === 'function')[0];
  const menu = () => tree.root.findByType('ProfileMenu' as any).props;
  const alert = () => tree.root.findByType('ProfileAlert' as any).props;
  const choose = (key: string) => { act(() => button('More options').props.onPress()); const m = menu(); act(() => { m.onClose(); m.rows.find((row: any) => row.key === key).onPress(); }); const closing = menu(); act(() => closing.onClosed()); return closing; };
  return { tree, unmount, button, menu, alert, choose,
    update: (next: Partial<PersonProfilePageProps> = {}) => { props = { ...props, ...next }; act(() => tree.update(<PersonProfilePage {...props}/>)); },
    text: () => tree.root.findAllByType(Text).map(n => n.props.children).flat().join(' '),
    photo: () => tree.root.findAllByType('ProfileImage' as any)[0],
  };
}
beforeEach(() => { jest.clearAllMocks(); mockFocused = true; mockViewerId = 'alice'; mockEpoch = 0; mockLoading = false; mockIdentityError = null; mockBlocking = false; result = { data: profile(), isLoading: false, isFetching: false, isError: false, refetch: mockRefetch }; mockProfile.mockImplementation(() => result); mockDm.mockReset().mockResolvedValue('dm-room'); mockRemove.mockReset().mockResolvedValue(undefined); mockBlock.mockReset().mockResolvedValue(undefined); mockRefetch.mockReset().mockResolvedValue({}); mockRetry.mockReset().mockResolvedValue(undefined); });
afterEach(() => cleanup.splice(0).forEach(fn => fn()));
it('uses the existing full profile facts, handle and cream/Mona presentation without inventing shared attendance', () => {
  const f = mount(); expect(mockProfile).toHaveBeenCalledWith('alice', 'amelia', { userId: 'alice', epoch: 0, isCurrent: expect.any(Function) });
  expect(f.text()).toContain('@amelia'); expect(f.text()).toContain('4 plans created'); expect(f.text()).toContain('3 plans'); expect(f.text()).toContain('you both know Jamie and 1 other'); expect(f.text()).toContain('and 2 more'); expect(f.text()).toContain('Past plans');
  const name = f.tree.root.findAllByType(Text).find(n => n.props.children === 'Amelia')!; expect(StyleSheet.flatten(name.props.style).fontFamily).toBe(AfterglowFallbackFonts.display);
  expect(f.tree.root.findByType('SafeArea' as any).props.style.backgroundColor).toBe(AfterglowColors.paper); expect(f.menu().appearance).toEqual({ fonts: AfterglowFallbackFonts }); expect(f.alert().appearance).toEqual({ fonts: AfterglowFallbackFonts }); expect(f.menu().rows.find((r: any) => r.key === 'report')).toMatchObject({ label: 'Block', subtitle: 'Review before blocking' });
});
it('keeps the default font family when optional appearance is absent', () => { const f = mount({ appearance: undefined }); const name = f.tree.root.findAllByType(Text).find(n => n.props.children === 'Amelia')!; expect(StyleSheet.flatten(name.props.style).fontFamily).toBe(Fonts.display); expect(f.alert().appearance).toBeUndefined(); expect(f.menu().rows.find((r: any) => r.key === 'report').label).toBe('Report or block'); });
it('normalizes an existing handle and omits missing handles', () => { result.data = profile({ handle: ' @@amelia ' }); const f = mount(); expect(f.text()).toContain('@amelia'); expect(f.text()).not.toContain('@@'); result.data = profile({ handle: null }); f.update(); expect(f.text()).not.toContain('@'); });
it('shows read failure and retry without displaying cached private profile facts', async () => { result.isError = true; const f = mount(); expect(f.text()).toContain('Couldn’t load this profile'); expect(f.text()).not.toContain('Amelia'); expect(f.button('Back')).toBeDefined(); await act(async () => f.button('Try again to load profile').props.onPress()); expect(mockRefetch).toHaveBeenCalledTimes(1); });
it('serializes retry while a deferred refetch is pending', async () => { const pending = deferred<object>(); mockRefetch.mockReturnValue(pending.promise); result.isError = true; const f = mount(); const retry = f.button('Try again to load profile').props.onPress; act(() => { retry(); retry(); }); expect(mockRefetch).toHaveBeenCalledTimes(1); expect(f.text()).toContain('Loading profile'); await act(async () => pending.resolve({})); expect(f.button('Try again to load profile')).toBeDefined(); });
it.each([null, profile({ user_id: 'wrong-target' })])('uses one unavailable result for private/missing/wrong-target profiles', data => { result.data = data; const f = mount(); expect(f.text()).toContain('This profile isn’t available'); expect(f.button('More options')).toBeUndefined(); expect(f.button('Message Amelia')).toBeUndefined(); });
it('shows loading explicitly and disables account-dependent lookup until identity is ready', async () => { mockLoading = true; const f = mount(); expect(f.text()).toContain('Loading profile'); expect(mockProfile).toHaveBeenCalledWith(null, null, expect.any(Object)); mockLoading = false; mockIdentityError = new Error('offline'); f.update(); expect(f.text()).toContain('Couldn’t check your account'); await act(async () => f.button('Try again to check account').props.onPress()); expect(mockRetry).toHaveBeenCalledTimes(1); });
it('retains a photo fallback and isolates a late failed URL from the renewed portrait', () => { const f = mount(); const oldFailure = f.photo().props.onError; act(() => oldFailure()); expect(f.photo().props.source.uri).toContain('jamie'); expect(f.text()).toContain('A'); result.data = profile({ profile_photo_url: 'https://example.invalid/renewed.jpg' }); f.update(); act(() => oldFailure()); expect(f.photo().props.source.uri).toContain('renewed'); expect(f.photo().props.contentFit).toBe('cover'); });
it('serializes Message taps and opens the existing confirmed DM destination', async () => { const pending = deferred<string>(); mockDm.mockReturnValue(pending.promise); const f = mount(); const send = f.button('Message Amelia').props.onPress; act(() => { send(); send(); }); expect(mockDm).toHaveBeenCalledTimes(1); expect(mockDm).toHaveBeenCalledWith('amelia', { scope: { userId: 'alice', isCurrent: expect.any(Function) } }); expect(f.button('Opening chat with Amelia').props.disabled).toBe(true); await act(async () => pending.resolve('dm-room')); expect(mockPush).toHaveBeenCalledWith('/(tabs)/chats/circle/dm-room'); });
it.each(['failure', 'empty'])('keeps Message recoverable after a %s result', async kind => { if (kind === 'failure') mockDm.mockRejectedValueOnce(new Error('offline')); else mockDm.mockResolvedValueOnce(''); const f = mount(); await act(async () => f.button('Message Amelia').props.onPress()); expect(mockPush).not.toHaveBeenCalled(); expect(f.text()).toContain("Couldn't open this chat"); await act(async () => f.button('Message Amelia').props.onPress()); expect(mockPush).toHaveBeenCalledTimes(1); });
it.each(['back', 'blur-return', 'target', 'account', 'unmount'])('retires delayed Message navigation after %s', async change => { const pending = deferred<string>(); mockDm.mockReturnValue(pending.promise); const f = mount(); const oldSend = f.button('Message Amelia').props.onPress; act(() => oldSend());
  if (change === 'back') act(() => f.button('Back').props.onPress());
  if (change === 'blur-return') { const scroll = f.tree.root.findByType(ScrollView); mockFocused = false; f.update(); mockFocused = true; f.update(); expect(f.tree.root.findByType(ScrollView)).toBe(scroll); }
  if (change === 'target') { result.data = profile({ user_id: 'luca', first_name_display: 'Luca' }); f.update({ targetId: 'luca' }); }
  if (change === 'account') { mockViewerId = 'bob'; mockEpoch++; f.update({ userId: 'bob' }); mockViewerId = 'alice'; mockEpoch++; f.update({ userId: 'alice' }); }
  if (change === 'unmount') f.unmount();
  expect(mockDm.mock.calls[0][1].scope.isCurrent()).toBe(false); act(() => oldSend()); await act(async () => pending.resolve('old-room')); expect(mockPush).not.toHaveBeenCalled(); expect(mockDm).toHaveBeenCalledTimes(1);
});
it('makes a plan with the same removable invited person and prevents duplicate navigation', () => { const f = mount(); const make = f.button('Make a plan').props.onPress; act(() => { make(); make(); }); expect(mockPush.mock.calls).toEqual([[buildComposerWithPerson('amelia', 'Amelia', profile().profile_photo_url)]]); });
it('preserves the shared-history destination and plan destinations', () => { const f = mount(); expect(f.text()).toContain('Your shared plans'); act(() => f.button('View your shared plans with Amelia').props.onPress()); expect(mockPush).toHaveBeenCalledWith('/person/amelia'); const g = mount(); const plan = g.tree.root.findAll(n => n.props.accessibilityLabel?.startsWith('A sunset walk.') && n.props.onPress)[0]; act(() => plan.props.onPress()); expect(mockPush).toHaveBeenCalledWith('/plan/next-plan'); });
it('does not open a plan from a retained row callback after that plan leaves the visible payload', () => { const f = mount(); const plan = f.tree.root.findAll(n => n.props.accessibilityLabel?.startsWith('A sunset walk.') && n.props.onPress)[0].props.onPress; result.data = profile({ upcoming: [] }); f.update(); act(() => plan()); expect(mockPush).not.toHaveBeenCalled(); });
it('starts remove confirmation only after the menu has actually closed', () => { const f = mount(); act(() => f.button('More options').props.onPress()); const m = f.menu(); act(() => { m.onClose(); m.rows.find((r: any) => r.key === 'remove').onPress(); }); expect(f.alert().visible).toBe(false); act(() => f.menu().onClosed()); expect(f.alert().visible).toBe(true); expect(mockRemove).not.toHaveBeenCalled(); });
it('a stale menu closure cannot open a confirmation after leaving and returning', () => { const f = mount(); act(() => f.button('More options').props.onPress()); const m = f.menu(); act(() => { m.onClose(); m.rows.find((r: any) => r.key === 'remove').onPress(); }); const closed = f.menu().onClosed; mockFocused = false; f.update(); mockFocused = true; f.update(); act(() => closed()); expect(f.alert().visible).toBe(false); });
it('uses scoped Remove, preserves the confirmation contract and waits for confirmed completion', async () => { const pending = deferred<void>(); mockRemove.mockReturnValue(pending.promise); const f = mount(); f.choose('remove'); const a = f.alert(); const remove = a.buttons.find((b: any) => b.text === 'Remove').onPress; act(() => { remove(); a.onClose(); remove(); }); expect(mockRemove).toHaveBeenCalledTimes(1); const [target, options] = mockRemove.mock.calls[0]; expect(target).toBe('amelia'); expect(options.scope.userId).toBe('alice'); expect(options.scope.isCurrent()).toBe(true); expect(options.scope.canDispatch()).toBe(true); expect(mockBack).not.toHaveBeenCalled(); await act(async () => pending.resolve()); expect(mockBack).toHaveBeenCalledTimes(1); });
it('removal failure stays on the profile with honest feedback', async () => { mockRemove.mockRejectedValueOnce(new Error('offline')); const f = mount(); f.choose('remove'); const a = f.alert(); await act(async () => { a.buttons.find((b: any) => b.text === 'Remove').onPress(); a.onClose(); }); expect(mockBack).not.toHaveBeenCalled(); expect(f.text()).toContain("Couldn't remove them just now"); expect(f.button('Message Amelia')).toBeDefined(); });
it('retires delayed remove confirmation and dispatch scope after account/visit changes', async () => { const pending = deferred<void>(); mockRemove.mockReturnValue(pending.promise); const f = mount(); f.choose('remove'); const a = f.alert(); const remove = a.buttons.find((b: any) => b.text === 'Remove').onPress; act(() => remove()); const scope = mockRemove.mock.calls[0][1].scope; mockEpoch++; f.update(); expect(scope.isCurrent()).toBe(false); expect(scope.canDispatch()).toBe(false); act(() => remove()); await act(async () => pending.resolve()); expect(mockRemove).toHaveBeenCalledTimes(1); expect(mockBack).not.toHaveBeenCalled(); });
it('does not lose confirmed remove navigation when its own refresh revokes profile readability', async () => { const pending = deferred<void>(); mockRemove.mockReturnValue(pending.promise); const f = mount(); f.choose('remove'); act(() => f.alert().buttons.find((b: any) => b.text === 'Remove').onPress()); result.data = null; f.update(); await act(async () => pending.resolve()); expect(mockBack).toHaveBeenCalledTimes(1); });
it('passes current account/visit scope to the existing block confirmation and retires old success', () => { const f = mount(); f.choose('report'); expect(mockBlock).toHaveBeenCalledTimes(1); const [target, name, success, scope] = mockBlock.mock.calls[0]; expect([target, name, scope.userId]).toEqual(['amelia', 'Amelia', 'alice']); expect(scope.isCurrent()).toBe(true); mockFocused = false; f.update(); mockFocused = true; f.update(); expect(scope.isCurrent()).toBe(false); act(() => success()); expect(mockBack).not.toHaveBeenCalled(); });
it('disables visible actions while the shared block operation is pending', () => { mockBlocking = true; const f = mount(); expect(f.button('Message Amelia').props.disabled).toBe(true); expect(f.button('Make a plan').props.disabled).toBe(true); expect(f.button('More options').props.disabled).toBe(true); });
