import React from 'react';
import {act,create,type ReactTestRenderer} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {TouchableOpacity,TextInput} from 'react-native';
const mockLegacyRead=jest.fn(),mockLegacyConfirm=jest.fn(),mockAccess=jest.fn(),mockEntry=jest.fn(),mockSync=jest.fn(),mockList=jest.fn(),mockRecord=jest.fn(),mockAttendees=jest.fn(),mockReplace=jest.fn();
const event='22222222-2222-4222-8222-222222222222',page='33333333-3333-4333-8333-333333333333';let mockCurrent=true;const mockScope={userId:'11111111-1111-4111-8111-111111111111',isCurrent:()=>mockCurrent};
jest.mock('../../ProfileButton',()=>({__esModule:true,default:()=>null}));
jest.mock('expo-linear-gradient',()=>({LinearGradient:require('react-native').View}));
jest.mock('../../../hooks/useCreatorPageScope',()=>({useCreatorPageScope:()=>({scope:mockScope,account:{epoch:1}})}));
jest.mock('../../../lib/creatorTicketRead',()=>({canReadCreatorTickets:(...a:any[])=>mockAccess(...a)}));
jest.mock('../../../lib/creatorEventEntry',()=>({resolveCreatorEventEntry:(...a:any[])=>mockEntry(...a)}));
jest.mock('../../../constants/FeatureFlags',()=>({CREATOR_PAGES_ENABLED:true}));
jest.mock('../../../lib/ticketDoor',()=>({...jest.requireActual('../../../lib/ticketDoor'),readLegacyCheckins:(...a:any[])=>mockLegacyRead(...a),confirmLegacyCheckins:(...a:any[])=>mockLegacyConfirm(...a),syncQueuedCheckins:(...a:any[])=>mockSync(...a),listQueued:(...a:any[])=>mockList(...a),recordCheckin:(...a:any[])=>mockRecord(...a)}));
jest.mock('../../../lib/ticketAttendees',()=>({...jest.requireActual('../../../lib/ticketAttendees'),getEventAttendees:(...a:any[])=>mockAttendees(...a)}));
jest.mock('../../../lib/haptics',()=>({hapticLight:jest.fn(),hapticSuccess:jest.fn(),hapticError:jest.fn(),hapticWarning:jest.fn()}));
jest.mock('../pages/PageFrame',()=>({PageFrame:({children}:any)=>children,pageStyles:{body:{}},PageAction:(props:any)=>require('react').createElement(require('react-native').TouchableOpacity,{onPress:props.onPress,accessibilityLabel:props.title})}));
jest.mock('expo-router',()=>({useLocalSearchParams:()=>({id:'22222222-2222-4222-8222-222222222222'}),router:{back:jest.fn(),canGoBack:()=>false,replace:(...a:any[])=>mockReplace(...a)}}));
jest.mock('react-native-safe-area-context',()=>jest.requireActual('react-native-safe-area-context/jest/mock').default);
import Screen from '../../../app/creator/check-in';
let tree:ReactTestRenderer,client:QueryClient;
const settle=()=>act(async()=>{await new Promise(r=>setTimeout(r,25));});
const json=()=>JSON.stringify(tree.toJSON());
const named=(label:string)=>tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===label)!;
async function mount(){client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}});await act(async()=>{tree=create(<QueryClientProvider client={client}><Screen/></QueryClientProvider>);});await settle();await settle();}
beforeEach(()=>{jest.clearAllMocks();mockCurrent=true;mockLegacyRead.mockResolvedValue([]);mockLegacyConfirm.mockResolvedValue({processed:[],remaining:0});mockAccess.mockResolvedValue(true);mockEntry.mockResolvedValue({kind:'page',eventId:event,pageId:page,entry:'owner'});mockSync.mockResolvedValue({processed:[],remaining:0});mockList.mockResolvedValue([]);mockRecord.mockResolvedValue({kind:'result',result:'admitted',code:'ENTRY234',admittedAt:null});mockAttendees.mockResolvedValue([]);});
afterEach(()=>{if(tree)act(()=>tree.unmount());client?.clear();});
it('gates page access before queue sync and passes resolved event/account context',async()=>{await mount();expect(mockSync).toHaveBeenCalledTimes(1);expect(mockSync).toHaveBeenCalledWith({eventId:event,pageId:page,scope:mockScope});expect(mockAttendees).toHaveBeenCalledWith(event,expect.objectContaining({userId:mockScope.userId,isCurrent:expect.any(Function)}));});
it('denied access neither drains queues nor loads attendees',async()=>{mockAccess.mockResolvedValue(false);await mount();expect(mockSync).not.toHaveBeenCalled();expect(mockAttendees).not.toHaveBeenCalled();expect(json()).toContain('isn’t available');});
it('a failed automatic sync has visible recovery and does not crash the screen',async()=>{mockSync.mockRejectedValueOnce(Error('storage unavailable'));await mount();expect(json()).toContain('Your saved records are kept');await act(async()=>named('Try again').props.onPress());await settle();expect(mockSync).toHaveBeenCalledTimes(2);expect(json()).not.toContain('Your saved records are kept');});
it('serializes same-frame submits and does not show unconfirmed scans as admitted',async()=>{let resolve:any;mockRecord.mockImplementation(()=>new Promise(r=>resolve=r));await mount();const input=tree.root.findByType(TextInput);act(()=>input.props.onChangeText('ENTRY234'));await act(async()=>{input.props.onSubmitEditing();input.props.onSubmitEditing();});expect(mockRecord).toHaveBeenCalledTimes(1);await act(async()=>resolve({kind:'queued',code:'ENTRY234'}));await settle();expect(json()).toContain('awaiting confirmation');expect(json()).not.toContain('"admitted"');});
it('failed storage retains typed code and never claims it was saved offline',async()=>{mockRecord.mockRejectedValue(Error('storage full'));await mount();const input=tree.root.findByType(TextInput);act(()=>input.props.onChangeText('ENTRY234'));await act(async()=>input.props.onSubmitEditing());await settle();expect(json()).toContain('not confirmed');expect(tree.root.findByType(TextInput).props.value).toBe('ENTRY234');expect(json()).not.toContain('is saved on this device');});
it('failed attendance read never displays a successful zero count',async()=>{mockAttendees.mockRejectedValue(Error('offline'));await mount();expect(json()).toContain('Attendance couldn’t be loaded');expect(json()).not.toContain('checked in</');expect(tree.root.findAll(n=>n.props.accessibilityRole==='summary')).toHaveLength(0);});
it('retired callbacks do not record scans and cold Back preserves event context',async()=>{await mount();await act(async()=>named('back').props.onPress());expect(mockReplace).toHaveBeenCalledWith(`/creator/attendees?id=${event}`);const input=tree.root.findByType(TextInput);act(()=>input.props.onChangeText('ENTRY234'));mockCurrent=false;await act(async()=>input.props.onSubmitEditing());expect(mockRecord).not.toHaveBeenCalled();});

it('a server refusal keeps the code available for correction',async()=>{mockRecord.mockResolvedValue({kind:'error',code:'ENTRY234',message:'This ticket is for another event.'});await mount();const input=tree.root.findByType(TextInput);act(()=>input.props.onChangeText('ENTRY234'));await act(async()=>input.props.onSubmitEditing());await settle();expect(tree.root.findByType(TextInput).props.value).toBe('ENTRY234');expect(json()).toContain('another event');});

it('earlier scans require review and confirmation before any recovery write',async()=>{const rows=[{code:'ENTRY234',queuedAt:'2026-09-16T20:00:00Z'}];mockLegacyRead.mockResolvedValue(rows);await mount();expect(mockLegacyConfirm).not.toHaveBeenCalled();expect(json()).toContain('earlier saved');await act(async()=>named('Review scans').props.onPress());expect(json()).toContain('ENTRY234');expect(mockLegacyConfirm).not.toHaveBeenCalled();mockLegacyRead.mockResolvedValue([]);mockLegacyConfirm.mockResolvedValue({processed:[{code:'ENTRY234',outcome:{kind:'result',result:'duplicate',code:'ENTRY234',admittedAt:'2026-09-16T20:00:00Z'}}],remaining:0});await act(async()=>named('Confirm earlier scans').props.onPress());await settle();expect(mockLegacyConfirm).toHaveBeenCalledWith({eventId:event,pageId:page,scope:mockScope},rows);expect(json()).toContain('already in');expect(json()).not.toContain('earlier saved');});
it('failed legacy preview shows recovery without showing unverified ticket codes',async()=>{mockLegacyRead.mockRejectedValue(Error('offline'));await mount();expect(json()).toContain('Earlier saved scans couldn’t be verified');expect(json()).not.toContain('ENTRY234');expect(mockLegacyConfirm).not.toHaveBeenCalled();});
