import React from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { TextInput, TouchableOpacity, Text } from 'react-native';
const mockQuestions=jest.fn(),mockSave=jest.fn(),mockAccess=jest.fn(),mockBack=jest.fn();
const mockStorage=new Map<string,string>(),mockSet=jest.fn();
let mockQuestionId='new',mockCurrent=true;
const eventId='11111111-1111-4111-8111-111111111111',existingId='22222222-2222-4222-8222-222222222222';
const mockScope={userId:'33333333-3333-4333-8333-333333333333',isCurrent:()=>mockCurrent};
jest.mock('../../../hooks/useCreatorPageScope',()=>({useCreatorPageScope:()=>({scope:mockScope,account:{epoch:1}})}));
jest.mock('../../../lib/creatorTicketRead',()=>({canReadCreatorTickets:()=>mockAccess()}));
jest.mock('../../../lib/creatorEventEntry',()=>({resolveCreatorEventEntry:async()=>({kind:'ordinary'})}));
jest.mock('../../../lib/creatorMode',()=>({getCreatorAccess:async()=>({hasEventHostGrant:true}),canManageEvents:()=>false}));
jest.mock('../../../lib/creatorQuestionEditor',()=>({...jest.requireActual('../../../lib/creatorQuestionEditor'),saveCreatorQuestion:(...a:any[])=>mockSave(...a)}));
jest.mock('../../../lib/ticketing',()=>({...jest.requireActual('../../../lib/ticketing'),getQuestions:(...a:any[])=>mockQuestions(...a)}));
jest.mock('../../../lib/haptics',()=>({hapticLight:jest.fn(),hapticSuccess:jest.fn(),hapticError:jest.fn()}));
jest.mock('expo-router',()=>({useLocalSearchParams:()=>({id:'11111111-1111-4111-8111-111111111111',questionId:mockQuestionId}),router:{back:()=>mockBack()},Stack:{Screen:()=>null}}));
jest.mock('react-native-safe-area-context',()=>jest.requireActual('react-native-safe-area-context/jest/mock').default);
jest.mock('../pages/PageFrame',()=>({PageFrame:({children}:any)=>children,PageAction:()=>null,pageStyles:{small:{}}}));
jest.mock('../../composer/CollapsibleCalendar',()=>()=>null);
jest.mock('../../composer/TimePicker',()=>({__esModule:true,default:(props:any)=>require('react').createElement('TimePicker',props)}));
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:async(k:string)=>mockStorage.get(k)??null,setItem:(k:string,v:string)=>mockSet(k,v),removeItem:async(k:string)=>{mockStorage.delete(k);}}}));
jest.mock('expo-crypto',()=>({randomUUID:()=> '44444444-4444-4444-8444-444444444444'}));
jest.mock('../../../hooks/useCommunicationDraftExit',()=>({useCommunicationDraftExit:jest.fn()}));
import {CreatorQuestionChanged,CreatorQuestionRejected} from '../../../lib/creatorQuestionEditor';
import Screen from '../../../app/creator/question-editor';
let tree:ReactTestRenderer,client:QueryClient;
const text=()=>JSON.stringify(tree.toJSON());
const settle=()=>act(async()=>{await new Promise(r=>setTimeout(r,20));});
async function mount(){client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0},mutations:{gcTime:0}}});await act(async()=>{tree=create(<QueryClientProvider client={client}><Screen/></QueryClientProvider>);});await settle();await settle();}
function input(name:string,value:string){act(()=>tree.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel===name)!.props.onChangeText(value));}
const save=()=>tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==='Save registration question')!.props.onPress();
beforeEach(()=>{jest.clearAllMocks();mockStorage.clear();mockSet.mockImplementation(async(k:string,v:string)=>{mockStorage.set(k,v);});mockQuestionId='new';mockCurrent=true;mockAccess.mockResolvedValue(true);mockQuestions.mockResolvedValue([]);mockSave.mockResolvedValue({id:'saved'});});
afterEach(()=>{if(tree)act(()=>tree.unmount());client?.clear();});

const pressText=(label:string)=>tree.root.findAllByType(TouchableOpacity).find(n=>n.findAllByType(Text).some(t=>t.props.children===label))!.props.onPress();
it('denies entry before private question reads',async()=>{mockAccess.mockResolvedValue(false);await mount();expect(mockQuestions).not.toHaveBeenCalled();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);});
it('keeps read failure distinct from a missing question',async()=>{mockQuestionId=existingId;mockQuestions.mockRejectedValue(Error('offline'));await mount();expect(text()).toContain('Couldn’t load the saved question.');expect(tree.root.findAllByType(TextInput)).toHaveLength(0);});
it('never creates from a missing existing question',async()=>{mockQuestionId=existingId;await mount();expect(text()).toContain('no longer available');expect(mockSave).not.toHaveBeenCalled();});
it('gives visible feedback for an empty prompt',async()=>{await mount();await act(async()=>save());expect(text()).toContain('Write a question');expect(mockSave).not.toHaveBeenCalled();});
it('saves required per-ticket choices through the original route',async()=>{await mount();input('Question text','Which picnic?');act(()=>pressText('pick one'));input('Choice 1','Vegetarian');input('Choice 2','Classic');act(()=>{pressText('required');pressText('Per ticket');});await act(async()=>save());expect(mockSave.mock.calls[0][2]).toEqual({prompt:'Which picnic?',qtype:'single_select',options:['Vegetarian','Classic'],required:true,scope:'per_attendee'});expect(mockBack).toHaveBeenCalledTimes(1);});
it('retains exact failed draft and rejects stale option callbacks',async()=>{mockSave.mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce({id:'saved'});await mount();input('Question text','What should we know?');const stale=()=>pressText('required');await act(async()=>save());act(()=>stale());expect(tree.root.findAllByType(TextInput).every(n=>!n.props.editable)).toBe(true);await act(async()=>save());expect(mockSave.mock.calls[1].slice(0,6)).toEqual(mockSave.mock.calls[0].slice(0,6));expect(mockSave.mock.calls[1][2].required).toBe(false);});
it('ignores duplicate submission and retired-visit navigation',async()=>{let done!:(v:any)=>void;mockSave.mockImplementation(()=>new Promise(r=>done=r));await mount();input('Question text','Any allergies?');act(()=>{save();save();});await settle();expect(mockSave).toHaveBeenCalledTimes(1);mockCurrent=false;await act(async()=>done({id:'saved'}));expect(mockBack).not.toHaveBeenCalled();});

async function reopen(){act(()=>tree.unmount());client.clear();await mount();}
it('restores unfinished choices on return without sending a save',async()=>{await mount();input('Question text','Unfinished picnic ');act(()=>pressText('pick one'));input('Choice 1','Vegetarian ');await settle();await reopen();expect(tree.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==='Question text')!.props.value).toBe('Unfinished picnic ');expect(tree.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==='Choice 1')!.props.value).toBe('Vegetarian ');expect(mockSave).not.toHaveBeenCalled();});
it('retains a lost save ID across unmount and checks read-only on request',async()=>{mockSave.mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce({id:'saved'});await mount();input('Question text','Original question');await act(async()=>save());const original=mockSave.mock.calls[0];await reopen();expect(mockSave).toHaveBeenCalledTimes(1);expect(tree.root.findAllByType(TextInput).every(n=>!n.props.editable)).toBe(true);await act(async()=>tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==='Check question save')!.props.onPress());expect(mockSave.mock.calls[1].slice(0,5)).toEqual(original.slice(0,5));expect(mockSave.mock.calls[1][5]).toBe(false);expect(mockStorage.size).toBe(0);});
it('local storage failure prevents dispatch and keeps a retryable original draft',async()=>{await mount();input('Question text','Please keep me');await settle();mockSet.mockRejectedValueOnce(Error('Storage unavailable'));await act(async()=>save());expect(mockSave).not.toHaveBeenCalled();expect(text()).toContain('Storage unavailable');await act(async()=>save());expect(mockSave).toHaveBeenCalledTimes(1);expect(mockSave.mock.calls[0][2].prompt).toBe('Please keep me');});
it('an authoritative changed-question result offers saved-version recovery without replay',async()=>{mockSave.mockRejectedValueOnce(new CreatorQuestionChanged('changed'));await mount();input('Question text','Attempt');await act(async()=>save());expect(text()).toContain('Use saved version');const count=mockSave.mock.calls.length;await act(async()=>tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==='Use saved question')!.props.onPress());await settle();expect(mockSave).toHaveBeenCalledTimes(count);expect(mockStorage.size).toBe(0);expect(mockBack).toHaveBeenCalled();});

it('a returned edit retains its original baseline despite a newer server version',async()=>{mockQuestionId=existingId;const original={id:existingId,event_id:eventId,prompt:'Original',qtype:'short_text',options:null,required:false,scope:'per_order',sort_order:0,is_active:true};mockQuestions.mockResolvedValue([original]);await mount();input('Question text','My unfinished edit');await settle();mockQuestions.mockResolvedValue([{...original,prompt:'Newer teammate edit'}]);await reopen();expect(tree.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==='Question text')!.props.value).toBe('My unfinished edit');await act(async()=>save());expect(mockSave.mock.calls[0][3].prompt).toBe('Original');});
it('a removed question still exposes recovery for its original pending save',async()=>{mockQuestionId=existingId;const original={id:existingId,event_id:eventId,prompt:'Original',qtype:'short_text',options:null,required:false,scope:'per_order',sort_order:0,is_active:true};mockQuestions.mockResolvedValue([original]);mockSave.mockRejectedValueOnce(Error('lost')).mockRejectedValueOnce(new CreatorQuestionChanged('gone'));await mount();input('Question text','Pending change');await act(async()=>save());mockQuestions.mockResolvedValue([]);await reopen();expect(text()).toContain('Check saved status');await act(async()=>tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==='Check question save')!.props.onPress());expect(text()).toContain('Use saved version');});

it('a confirmed refusal restores editable fields and preserves the question ID on return',async()=>{mockSave.mockImplementationOnce(async(...args:any[])=>{await args[6].beforeDispatch();throw new CreatorQuestionRejected('Review your question and try again.');});await mount();input('Question text','Original retained');await act(async()=>save());expect(text()).toContain('Review your question');expect(tree.root.findAllByType(TextInput).every(n=>n.props.editable)).toBe(true);expect(text()).not.toContain('Check saved status');const id=mockSave.mock.calls[0][1];input('Question text','Corrected question');await settle();await reopen();expect(tree.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==='Question text')!.props.value).toBe('Corrected question');await act(async()=>save());expect(mockSave.mock.calls[1][1]).toBe(id);expect(mockSave.mock.calls[1][6].previouslyDispatched).toBe(false);});
it('durably records dispatch before a lost response and carries it through return',async()=>{mockSave.mockImplementationOnce(async(...args:any[])=>{expect(args[6].previouslyDispatched).toBe(false);expect(await args[6].beforeDispatch()).toBe(true);expect(JSON.parse([...mockStorage.values()][0]).value.dispatched).toBe(true);throw Error('lost');}).mockRejectedValueOnce(Error('rejected retry remains uncertain'));await mount();input('Question text','Retained attempt');await act(async()=>save());await reopen();await act(async()=>save());expect(mockSave.mock.calls[1][6].previouslyDispatched).toBe(true);expect(tree.root.findAllByType(TextInput).every(n=>!n.props.editable)).toBe(true);});
it('legacy pending drafts are treated as previously dispatched',async()=>{mockSave.mockRejectedValueOnce(Error('lost'));await mount();input('Question text','Legacy attempt');await act(async()=>save());const [key,raw]=[...mockStorage.entries()][0],record=JSON.parse(raw);delete record.value.dispatched;mockStorage.set(key,JSON.stringify(record));await reopen();await act(async()=>save());expect(mockSave.mock.calls[1][6].previouslyDispatched).toBe(true);});
