import React from 'react';
import {act,create,type ReactTestRenderer} from 'react-test-renderer';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Alert,Share,Text,TextInput,TouchableOpacity} from 'react-native';
import type {AttendeeQuestion,RawTicketAnswer} from '../../../lib/ticketAttendees';
const mockAccess=jest.fn(),mockAttendees=jest.fn(),mockQuestions=jest.fn(),mockAnswers=jest.fn(),mockBack=jest.fn();
let mockEvent='event',mockScope:{userId:string;isCurrent():boolean}|null={userId:'creator',isCurrent:()=>true};
jest.mock('../../../hooks/useCreatorPageScope',()=>({useCreatorPageScope:()=>({scope:mockScope})}));
jest.mock('../../../lib/creatorTicketRead',()=>({canReadCreatorTickets:(...a:any[])=>mockAccess(...a)}));
jest.mock('../pages/PageFrame',()=>({PageFrame:({children}:any)=>children,PageAction:()=>null,pageStyles:{body:{}}}));
jest.mock('expo-router',()=>({useLocalSearchParams:()=>({id:mockEvent}),router:{back:()=>mockBack()}}));
jest.mock('../../../lib/supabase',()=>({supabase:{}}));
jest.mock('../../../lib/haptics',()=>({hapticLight:jest.fn()}));
jest.mock('../../../lib/ticketAttendees',()=>({...jest.requireActual('../../../lib/ticketAttendees'),getEventAttendees:(...a:any[])=>mockAttendees(...a),getEventQuestions:(...a:any[])=>mockQuestions(...a),getEventAnswers:(...a:any[])=>mockAnswers(...a)}));
import Screen from '../../../app/creator/questionnaire-responses';
import {PageAction} from '../pages/PageFrame';
let tree:ReactTestRenderer,client:QueryClient,alive=false;
const seats=[{positionId:'seat1',orderId:'order1',positionIndex:1,referenceCode:'WU-1',buyerName:'Juniper',tierName:'Entry',orderStatus:'paid',voided:false,checkedIn:false,refundedCents:0,purchasedAt:'2026-09-01'}, {positionId:'seat2',orderId:'order2',positionIndex:1,referenceCode:'WU-2',buyerName:'Aster',tierName:'Gold',orderStatus:'paid',voided:false,checkedIn:false,refundedCents:0,purchasedAt:'2026-09-03'}, {positionId:'seat3',orderId:'order3',positionIndex:1,referenceCode:'WU-3',buyerName:'Cedar',tierName:'Entry',orderStatus:'paid',voided:false,checkedIn:false,refundedCents:0,purchasedAt:'2026-09-05'}];
const questions:AttendeeQuestion[]=[{id:'q1',prompt:'What are you bringing?',qtype:'short_text',scope:'per_order',sortOrder:0,options:null},{id:'q2',prompt:'Food preferences',qtype:'multi_select',scope:'per_attendee',sortOrder:1,options:['Vegan','Gluten-free, dairy-free','Other']}];
const answers:RawTicketAnswer[]=[{orderId:'order1',questionId:'q1',attendeeIndex:null,value:{text:'Picnic'}},{orderId:'order1',questionId:'q2',attendeeIndex:1,value:{choices:['Vegan','Gluten-free, dairy-free']}},{orderId:'order2',questionId:'q1',attendeeIndex:null,value:{text:'Bread'}},{orderId:'order2',questionId:'q2',attendeeIndex:1,value:{choices:['Vegan']}}];
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(v:any)=>void;const promise=new Promise<T>((r,j)=>{resolve=r;reject=j;});return{promise,resolve,reject};}
const content=()=> <QueryClientProvider client={client}><Screen/></QueryClientProvider>;
function mount(){act(()=>{tree=create(content());alive=true;});}
function update(){act(()=>tree.update(content()));}
function unmount(){if(alive)act(()=>{tree.unmount();alive=false;});}
function text(n:any):string{return Array.isArray(n)?n.map(text).join(''):String(n??'');}
function words(){return tree.root.findAllByType(Text).map(n=>text(n.props.children)).join(' ');}
function button(label:string){return tree.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===label)!;}
function chip(label:string){return tree.root.findAllByType(TouchableOpacity).find(n=>n.findAllByType(Text).some(t=>text(t.props.children)===label))!;}
function retry(){return tree.root.findByType(PageAction);}
async function flush(){for(let pass=0;pass<3;pass++){await act(async()=>{for(let i=0;i<25;i++)await Promise.resolve();});await act(async()=>{jest.advanceTimersByTime(1);for(let i=0;i<25;i++)await Promise.resolve();});}}
beforeEach(()=>{jest.useFakeTimers();jest.clearAllMocks();mockEvent='event';mockScope={userId:'creator',isCurrent:()=>true};mockAccess.mockReset().mockResolvedValue(true);mockAttendees.mockReset().mockResolvedValue(seats);mockQuestions.mockReset().mockResolvedValue(questions);mockAnswers.mockReset().mockResolvedValue(answers);client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:Infinity}}});});
afterEach(()=>{unmount();client.clear();jest.clearAllTimers();jest.useRealTimers();jest.restoreAllMocks();});
it.each([['attendees',mockAttendees,seats],['questions',mockQuestions,questions],['answers',mockAnswers,answers]] as const)('bounds %s loading, refuses false blanks, retries and ignores late data',async(_name,read,result)=>{
 const pending=deferred<any>();read.mockReturnValue(pending.promise);mount();await flush();expect(words()).not.toContain('blank (');expect(words()).not.toContain('no questions');expect(button('export responses')).toBeUndefined();await act(async()=>{jest.advanceTimersByTime(12000);});await flush();expect(words()).toContain('Responses couldn’t be loaded.');expect(read).toHaveBeenCalledTimes(1);read.mockResolvedValue(result);act(()=>retry().props.onPress());await flush();act(()=>button('show answers for Juniper').props.onPress());expect(words()).toContain('Picnic');pending.resolve([]);await flush();expect(words()).toContain('Picnic');expect(words()).toContain('Vegan (2)');
});
it.each([['attendees',mockAttendees,'event-attendees'],['questions',mockQuestions,'event-questions'],['answers',mockAnswers,'event-answers']] as const)('keeps actual answers, filter and expanded rows on cached %s failure and busy retry',async(_name,read,key)=>{
 mount();await flush();act(()=>{tree.root.findByType(TextInput).props.onChangeText('WU-1');button('show answers for Juniper').props.onPress();});expect(words()).toContain('Picnic');read.mockRejectedValue(Error('offline'));await act(async()=>{await client.invalidateQueries({queryKey:[key]});});await flush();expect(words()).toContain('Picnic');expect(words()).toContain('Vegan (1)');expect(words()).not.toContain('Aster');expect(button('export responses')).toBeUndefined();
 const pending=deferred<any>();read.mockReturnValue(pending.promise);const fn=retry().props.onPress;const count=read.mock.calls.length;act(()=>{fn();fn();});await flush();expect(read).toHaveBeenCalledTimes(count+1);expect(retry().props.disabled).toBe(true);expect(words()).toContain('Picnic');pending.resolve(read===mockAttendees?seats:read===mockQuestions?questions:answers);await flush();expect(tree.root.findByType(TextInput).props.value).toBe('WU-1');expect(words()).toContain('Picnic');expect(button('export responses')).toBeDefined();
});
it('preserves multi-select comma labels, faceted counts, blank bucket, tier/search filtering, sorting and filtered CSV',async()=>{
 const share=jest.spyOn(Share,'share').mockResolvedValue({action:Share.sharedAction});mount();await flush();expect(words()).toContain('Vegan (2)');expect(words()).toContain('Gluten-free, dairy-free (1)');expect(words()).toContain('Other (0)');expect(words()).toContain('blank (1)');act(()=>chip('Gluten-free, dairy-free (1)').props.onPress());expect(words()).toContain('Juniper');expect(words()).not.toContain('Aster');expect(words()).toContain('Vegan (2)');await act(async()=>{await button('export responses').props.onPress();});expect(share.mock.calls[0][0].message).toContain('Picnic');expect(share.mock.calls[0][0].message).toContain('WU-1');expect(share.mock.calls[0][0].message).not.toContain('WU-2');act(()=>chip('Gluten-free, dairy-free (1)').props.onPress());act(()=>chip('blank (1)').props.onPress());expect(words()).toContain('Cedar');expect(words()).not.toContain('Juniper');act(()=>chip('blank (1)').props.onPress());act(()=>chip('Entry').props.onPress());expect(words()).toContain('Vegan (1)');expect(words()).not.toContain('Aster');act(()=>chip('Entry').props.onPress());const names=()=>tree.root.findAllByType(TouchableOpacity).map(n=>n.props.accessibilityLabel).filter(l=>l?.startsWith('show answers'));expect(names()).toEqual(['show answers for Aster','show answers for Cedar','show answers for Juniper']);act(()=>button('sort most recent first').props.onPress());expect(names()).toEqual(['show answers for Cedar','show answers for Aster','show answers for Juniper']);
});
it.each(['event','account','same-account-new-visit','unmount'])('retires export/back/retry and private data on %s',async retirement=>{
 const share=jest.spyOn(Share,'share').mockResolvedValue({action:Share.sharedAction});mount();await flush();const exportRows=button('export responses').props.onPress;const back=button('back').props.onPress;mockAnswers.mockRejectedValue(Error('offline'));await act(async()=>{await client.invalidateQueries({queryKey:['event-answers']});});await flush();const oldRetry=retry().props.onPress;mockAnswers.mockImplementation(()=>new Promise(()=>{}));if(retirement==='unmount')unmount();else{if(retirement==='event')mockEvent='event2';mockScope={userId:retirement==='account'?'other':'creator',isCurrent:()=>true};update();await flush();expect(words()).not.toContain('Juniper');}const count=mockAnswers.mock.calls.length;await act(async()=>{await exportRows();back();oldRetry();});expect(share).not.toHaveBeenCalled();expect(mockBack).not.toHaveBeenCalled();expect(mockAnswers).toHaveBeenCalledTimes(count);
});
it('does not read private data without current exact-event access, and bounds access retry',async()=>{
 mockAccess.mockImplementation(()=>new Promise(()=>{}));mount();await flush();expect(mockAttendees).not.toHaveBeenCalled();await act(async()=>{jest.advanceTimersByTime(12000);});await flush();expect(words()).toContain('This event couldn’t be loaded.');mockAccess.mockResolvedValue(false);act(()=>retry().props.onPress());await flush();expect(words()).toContain('Response access isn’t available');expect(mockAttendees).not.toHaveBeenCalled();mockAccess.mockResolvedValue(true);act(()=>retry().props.onPress());await flush();expect(words()).toContain('Juniper');expect(mockAttendees.mock.calls[0][1].userId).toBe('creator');expect(mockQuestions.mock.calls[0][1].userId).toBe('creator');expect(mockAnswers.mock.calls[0][1].userId).toBe('creator');
});
it('renders no-question and empty-attendance states only after successful reads',async()=>{
 mockQuestions.mockRejectedValue(Error('offline'));mount();await flush();expect(words()).not.toContain('no questions');mockQuestions.mockResolvedValue([]);act(()=>retry().props.onPress());await flush();expect(words()).toContain('this event has no questions set up.');expect(mockAnswers).not.toHaveBeenCalled();unmount();client.clear();mockQuestions.mockResolvedValue(questions);mockAttendees.mockResolvedValue([]);mount();await flush();expect(words()).toContain('no one matches that yet.');expect(mockAnswers).not.toHaveBeenCalled();
});
it('holds the last complete snapshot when new orders require answers, instead of inventing blanks',async()=>{
 mount();await flush();act(()=>button('show answers for Juniper').props.onPress());const pending=deferred<any>();mockAnswers.mockReturnValue(pending.promise);mockAttendees.mockResolvedValue([...seats,{...seats[0],positionId:'seat4',orderId:'order4',buyerName:'Riley',referenceCode:'WU-4'}]);await act(async()=>{await client.invalidateQueries({queryKey:['event-attendees']});});await flush();expect(words()).toContain('Picnic');expect(words()).not.toContain('Riley');expect(words()).toContain('blank (1)');expect(button('export responses')).toBeUndefined();pending.resolve([...answers,{orderId:'order4',questionId:'q2',attendeeIndex:1,value:{choices:['Vegan']}}]);await flush();expect(words()).toContain('Riley');expect(words()).toContain('Vegan (3)');expect(words()).toContain('blank (1)');
});
it('suppresses share rejection feedback after leaving and keeps the current Back destination',async()=>{
 const pending=deferred<any>();jest.spyOn(Share,'share').mockReturnValue(pending.promise);const alert=jest.spyOn(Alert,'alert');mount();await flush();act(()=>{void button('export responses').props.onPress();button('back').props.onPress();});expect(mockBack).toHaveBeenCalledTimes(1);unmount();pending.reject(Error('dismissed'));await flush();expect(alert).not.toHaveBeenCalled();
});
