import React,{useEffect,useState} from 'react';import {act,create,type ReactTestRenderer} from 'react-test-renderer';import {Text,TextInput} from 'react-native';
const mockResolve=jest.fn();let mockUser='0e6e1827-0f87-4e03-b42b-7ade8219725b',mockEpoch=0,mockAccountCurrent=true,mockFocused=true,mockScope:any;const mockAccount={get viewerId(){return mockUser;},get epoch(){return mockEpoch;},isCurrent:()=>mockAccountCurrent,isLoading:false,error:null};
jest.mock('../../../../hooks/useCreatorPageScope',()=>({useCreatorPageScope:()=>({scope:mockScope,account:mockAccount})}));
jest.mock('../../../../hooks/useAfterglowFonts',()=>({useAfterglowFonts:()=>({fonts:{regular:'System',medium:'System',semibold:'System',display:'System'}})}));
jest.mock('../../../../lib/creatorEventEntry',()=>({...jest.requireActual('../../../../lib/creatorEventEntry'),resolveCreatorEventEntry:(...a:unknown[])=>mockResolve(...a)}));
jest.mock('../../../../lib/creatorPageEventReuseEntry',()=>({}));
jest.mock('../../../../lib/supabase',()=>({supabase:{}}));
jest.mock('expo-router',()=>({Redirect:(p:any)=>require('react').createElement(require('react-native').Text,{testID:'redirect'},p.href),router:{canGoBack:()=>true,back:()=>{}},Stack:{Screen:()=>null}}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaView:require('react-native').View}));
import CreatorEventEntryGate from '../CreatorEventEntryGate';import {PageAction} from '../PageFrame';
const event='0fe10000-0000-4000-8000-000000000001',page='f5d7644a-2ff5-4def-b0ab-d04b8250892b';const intent={kind:'edit' as const,id:event};let tree:ReactTestRenderer,mounts=0;
function Editor(){const [value,setValue]=useState('Saved title');useEffect(()=>{mounts++;},[]);return <TextInput accessibilityLabel="Ordinary editor title" value={value} onChangeText={setValue}/>;}
const element=()=> <CreatorEventEntryGate intent={intent} returnToTickets><Editor/></CreatorEventEntryGate>;
async function flush(){for(let i=0;i<6;i++)await act(async()=>{await Promise.resolve();});}
async function mount(){await act(async()=>{tree=create(element());});await flush();}
beforeEach(()=>{jest.clearAllMocks();mockUser='0e6e1827-0f87-4e03-b42b-7ade8219725b';mockEpoch=0;mockAccountCurrent=true;mockFocused=true;mockScope={userId:mockUser,isCurrent:()=>mockFocused&&mockAccountCurrent};mounts=0;mockResolve.mockResolvedValue({kind:'ordinary'});});
afterEach(()=>act(()=>tree?.unmount()));
it('keeps the ordinary editor unmounted until its source is classified',async()=>{let finish!:(v:any)=>void;mockResolve.mockReturnValueOnce(new Promise(r=>{finish=r;}));await mount();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);await act(async()=>{finish({kind:'ordinary'});});expect(mounts).toBe(1);});
it('confirmed ordinary entry preserves unsaved edits across focus changes without another classification',async()=>{await mount();act(()=>tree.root.findByType(TextInput).props.onChangeText('Unsaved changes'));mockFocused=false;mockScope={...mockScope};act(()=>tree.update(element()));await flush();mockFocused=true;mockScope={...mockScope};act(()=>tree.update(element()));await flush();expect(tree.root.findByType(TextInput).props.value).toBe('Unsaved changes');expect(mounts).toBe(1);expect(mockResolve).toHaveBeenCalledTimes(1);});
it('a new account must classify again and cannot inherit the old ordinary editor state',async()=>{await mount();act(()=>tree.root.findByType(TextInput).props.onChangeText('Old account draft'));mockUser='0fe10000-0000-4000-8000-000000000009';mockEpoch++;mockScope={userId:mockUser,isCurrent:()=>mockAccountCurrent};mockResolve.mockResolvedValue({kind:'page',pageId:page,eventId:event,entry:'team'});act(()=>tree.update(element()));await flush();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(mockResolve).toHaveBeenCalledTimes(2);expect(tree.root.findByProps({testID:'redirect'}).props.children).toBe(`/creator/event-form?id=${event}&pageId=${page}&team=1&returnToTickets=1`);});
it('unknown access shows retry and never mounts the ordinary editor',async()=>{mockResolve.mockRejectedValue(Error('Offline'));await mount();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(tree.root.findByType(PageAction).props.title).toBe('Check access');});
it('an explicit check can recover page entry without an ordinary fallback',async()=>{mockResolve.mockRejectedValueOnce(Error('Offline'));await mount();mockResolve.mockResolvedValue({kind:'page',pageId:page,eventId:event,entry:'owner'});await act(async()=>{await tree.root.findByType(PageAction).props.onPress();});await flush();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(tree.root.findByProps({testID:'redirect'}).props.children).toContain(`pageId=${page}`);});
it('late results cannot open any editor after the initiating account retires',async()=>{let finish!:(v:any)=>void;mockResolve.mockReturnValueOnce(new Promise(r=>{finish=r;}));await mount();mockAccountCurrent=false;await act(async()=>{finish({kind:'ordinary'});});expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(mounts).toBe(0);});
