import React from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { TextInput, TouchableOpacity } from 'react-native';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
const mockRead=jest.fn(),mockSave=jest.fn(),mockQuestionSave=jest.fn(),mockBack=jest.fn(),mockSuccess=jest.fn(),mockQuestionsRead=jest.fn();
let mockActor='a',mockEpoch=1,mockFocused=true,mockLive=true;
let mockScope:any,mockAccount:any;
function newScope(){const actor=mockActor,epoch=mockEpoch;mockLive=true;mockScope={userId:actor,isCurrent:()=>mockLive&&mockActor===actor&&mockEpoch===epoch&&mockFocused};mockAccount={viewerId:actor,epoch,isLoading:false,error:null,isCurrent:()=>mockActor===actor&&mockEpoch===epoch,retry:jest.fn()};}
jest.mock('../../../hooks/useCreatorPageScope',()=>({useCreatorPageScope:()=>({scope:mockScope,account:mockAccount,focused:mockFocused})}));
jest.mock('expo-router',()=>({Stack:{Screen:()=>null},useRouter:()=>({back:mockBack}),Redirect:()=>null}));
jest.mock('../../../hooks/useAfterglowFonts',()=>({useAfterglowFonts:()=>({fonts:{display:'Display',regular:'Regular',medium:'Medium',semibold:'Semibold'}})}));
jest.mock('../../../components/creator/CreatorScreenHeader',()=>({CreatorScreenHeader:(p:any)=>require('react').createElement('Header',p)}));
jest.mock('../../../components/communities/JoinCommunityPopup',()=>({JoinCommunityPopup:()=>null}));
jest.mock('../../../components/BrandedAlert',()=>({BrandedAlert:(p:any)=>require('react').createElement('Alert',p)}));
jest.mock('../../../lib/haptics',()=>({hapticSuccess:()=>mockSuccess(),hapticLight:jest.fn()}));
jest.mock('../../../lib/selectedCommunity',()=>({useLedCommunity:(a:any)=>a?.ledCommunities?.[0]}));
jest.mock('../../../constants/FeatureFlags',()=>({JOIN_GATE_ENABLED:true,CONFIGURABLE_JOIN_QUESTIONS_ENABLED:true}));
jest.mock('../../../lib/creatorMode',()=>({
 getCreatorAccess:jest.fn(async(id?:string)=>({ledCommunities:[{id:'community-'+(typeof id==='string'?id:mockActor),name:'Community '+(typeof id==='string'?id:mockActor),role:'leader'}],hasLeaderGrant:true,hasEventHostGrant:false})),
 canManageMembers:()=>true,creatorLandingRoute:()=>'/creator/pages',getJoinGateSettings:(...a:any[])=>mockRead(...a),updateJoinGateSettings:(...a:any[])=>mockSave(...a),
 getJoinPolicy:async()=>null,setJoinPolicy:jest.fn(),getCommunityMemberCounts:async()=>null,getJoinQuestionsConfig:(...a:any[])=>mockQuestionsRead(...a),getCommunityRestrictedGender:async()=>null,
 updateJoinQuestionsConfig:(...a:any[])=>mockQuestionSave(...a),
}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaView:require('react-native').View}));
import Screen from '../join-gate';
let tree:ReactTestRenderer,client:QueryClient;
const settings=(label='Original')=>({join_welcome_message:label,join_intro_question:'Tell us',guidelines_url:'https://example.test/rules'});
const deferred=()=>{let resolve!:(v?:any)=>void,reject!:(v?:any)=>void;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject};};
function ui(){return <QueryClientProvider client={client}><Screen/></QueryClientProvider>;}
async function flush(){for(let i=0;i<5;i++)await act(async()=>{await jest.advanceTimersByTimeAsync(1);});}
async function mount(){await act(async()=>{tree=create(ui());});await flush();}
function text(n:any):string{return typeof n==='string'?n:Array.isArray(n)?n.map(text).join(''):n?.children?text(n.children):'';}
function button(label:string){const n=tree.root.findAllByType(TouchableOpacity).find(x=>text({children:x.children})===label);if(!n)throw Error('Missing button '+label);return n;}
function input(){return tree.root.findAllByType(TextInput)[0];}
beforeEach(()=>{jest.useFakeTimers();jest.clearAllMocks();mockActor='a';mockEpoch=1;mockFocused=true;newScope();client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:Infinity}}});mockRead.mockResolvedValue(settings());mockSave.mockResolvedValue(undefined);mockQuestionSave.mockResolvedValue(undefined);mockQuestionsRead.mockResolvedValue({askReason:false,askSource:false,askRulesConfirm:false,openQuestion:null});});
afterEach(()=>{act(()=>tree?.unmount());client.clear();jest.useRealTimers();});
it('failed initial read exposes Retry, no blank editor or Save; retry loads exact saved fields',async()=>{mockRead.mockRejectedValueOnce(Error('offline'));await mount();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(()=>button('save')).toThrow();await act(async()=>button('Retry').props.onPress());await flush();expect(input().props.value).toBe('Original');expect(mockSave).not.toHaveBeenCalled();});
it('a fresh failed read does not offer cached fields for saving',async()=>{client.setQueryData(['join-gate','community-a','a'],settings('Cached'));mockRead.mockRejectedValue(Error('offline'));await mount();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);expect(()=>button('save')).toThrow();expect(mockSave).not.toHaveBeenCalled();});
it('current edits survive failed refresh and explicit Retry instead of being replaced',async()=>{await mount();act(()=>input().props.onChangeText('My edits'));mockRead.mockRejectedValueOnce(Error('offline'));await act(async()=>{await client.invalidateQueries({queryKey:['join-gate']});});await flush();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);mockRead.mockResolvedValue(settings('Server'));await act(async()=>button('Retry').props.onPress());await flush();expect(input().props.value).toBe('My edits');});
it('same-frame duplicate Save dispatches one unchanged settings write',async()=>{const write=deferred();mockSave.mockReturnValue(write.promise);await mount();act(()=>input().props.onChangeText('Kept'));const save=button('save').props.onPress;act(()=>{void save();void save();});expect(mockSave).toHaveBeenCalledTimes(1);expect(mockSave).toHaveBeenCalledWith('community-a',{...settings(),join_welcome_message:'Kept'});await act(async()=>write.resolve());await flush();expect(mockQuestionSave).toHaveBeenCalledTimes(1);expect(mockSuccess).toHaveBeenCalledTimes(1);});
it('account switch clears old private fields and retained Save cannot write',async()=>{await mount();act(()=>input().props.onChangeText('Private A'));const save=button('save').props.onPress;mockActor='b';mockEpoch=2;newScope();mockRead.mockResolvedValue(settings('B'));await act(async()=>tree.update(ui()));await flush();expect(input().props.value).toBe('B');await act(async()=>save());expect(mockSave).not.toHaveBeenCalled();});
it('retired save cannot continue extra-question write or show success after account roundtrip',async()=>{const write=deferred();mockSave.mockReturnValue(write.promise);await mount();act(()=>{void button('save').props.onPress();});mockActor='b';mockEpoch=2;newScope();await act(async()=>tree.update(ui()));await flush();mockActor='a';mockEpoch=3;newScope();await act(async()=>tree.update(ui()));await flush();await act(async()=>write.resolve());await flush();expect(mockQuestionSave).not.toHaveBeenCalled();expect(mockSuccess).not.toHaveBeenCalled();expect(tree.root.findByType('Alert' as any).props.visible).toBe(false);});
it('blur and return retires old controls and late save while keeping the current draft',async()=>{const write=deferred();mockSave.mockReturnValue(write.promise);await mount();act(()=>input().props.onChangeText('Kept here'));const oldSave=button('save').props.onPress,oldEdit=input().props.onChangeText;act(()=>{void oldSave();});mockLive=false;mockFocused=false;await act(async()=>tree.update(ui()));mockFocused=true;newScope();await act(async()=>tree.update(ui()));await flush();act(()=>oldEdit('Wrong'));await act(async()=>oldSave());expect(mockSave).toHaveBeenCalledTimes(1);await act(async()=>write.resolve());await flush();expect(input().props.value).toBe('Kept here');expect(mockQuestionSave).not.toHaveBeenCalled();expect(mockSuccess).not.toHaveBeenCalled();expect(button('save').props.disabled).toBe(false);});
it('late initial settings result for previous account cannot populate the new editor',async()=>{const read=deferred();mockRead.mockReturnValueOnce(read.promise);await mount();mockActor='b';mockEpoch=2;newScope();mockRead.mockResolvedValue(settings('B'));await act(async()=>tree.update(ui()));await flush();await act(async()=>read.resolve(settings('Private A')));await flush();expect(input().props.value).toBe('B');});

it('cached A is not seeded before fresh B resolves; Save writes B',async()=>{client.setQueryData(['join-gate','community-a','a'],settings('Cached A'));const fresh=deferred();mockRead.mockReturnValueOnce(fresh.promise);await mount();expect(tree.root.findAllByType(TextInput)).toHaveLength(0);await act(async()=>fresh.resolve(settings('Fresh B')));await flush();expect(input().props.value).toBe('Fresh B');await act(async()=>button('save').props.onPress());await flush();expect(mockSave).toHaveBeenCalledWith('community-a',settings('Fresh B'));});

it('cached optional questions wait for fresh success before Save includes them',async()=>{client.setQueryData(['join-questions-config','community-a','a'],{askReason:false,askSource:false,askRulesConfirm:false,openQuestion:'Cached'});const fresh=deferred();mockQuestionsRead.mockReturnValue(fresh.promise);await mount();await act(async()=>fresh.resolve({askReason:true,askSource:false,askRulesConfirm:false,openQuestion:'Fresh'}));await flush();await act(async()=>button('save').props.onPress());await flush();expect(mockQuestionSave).toHaveBeenCalledWith('community-a',{askReason:true,askSource:false,askRulesConfirm:false,openQuestion:'Fresh'});});
it('failed optional read never writes stale cached questions during base save',async()=>{client.setQueryData(['join-questions-config','community-a','a'],{askReason:true,askSource:false,askRulesConfirm:false,openQuestion:'Cached'});mockQuestionsRead.mockRejectedValue(Error('unavailable'));await mount();await act(async()=>button('save').props.onPress());await flush();expect(mockSave).toHaveBeenCalledTimes(1);expect(mockQuestionSave).not.toHaveBeenCalled();});
