import {parsePageInvitationDispatch,renderPageInvitationEmail} from '../_shared/pageInvitationEmail.ts';
import {resolvePageInvitationPushTargets,pageInvitationPushData} from '../_shared/pageInvitationPushTargets.ts';
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',c='33333333-3333-4333-8333-333333333333';
const good={decision:'deliver',email:'test@example.invalid',pageId:a,invitationId:b,userId:c,idempotencyKey:`page-invitation/${b}/${c}`};
function ok(v:unknown){if(!v)throw Error('assertion failed');}
Deno.test('email binds exact invitation, recipient and idempotency key',()=>{ok(parsePageInvitationDispatch(good,b,c));for(const patch of [{userId:a},{invitationId:a},{pageId:'../../other'},{idempotencyKey:'new'},{email:'bad'}])ok(parsePageInvitationDispatch({...good,...patch},b,c)===null);});
Deno.test('email uses existing authenticated review and no private page metadata',()=>{const v=parsePageInvitationDispatch(good,b,c);if(!v||v.decision!=='deliver')throw Error();const r=renderPageInvitationEmail(v);ok(r.text.includes(`/app/pages/${a}/team?invitationId=${b}`));ok(!r.html.includes(good.email));ok(r.text.includes('72 hours'));});
Deno.test('pause and cancellation stay distinct from delivery',()=>{ok(parsePageInvitationDispatch({decision:'pause',reason:'missing email'},b,c)?.decision==='pause');ok(parsePageInvitationDispatch({decision:'cancel',reason:'expired'},b,c)?.decision==='cancel');ok(parsePageInvitationDispatch({decision:'deliver'},b,c)===null);});
Deno.test('push resolves exact mapping and ordinary notifications make no call',async()=>{let count=0;const db={rpc:async()=>{count++;return {data:[{notification_id:a,page_id:a,invitation_id:b,user_id:c,eligible:true}]};}};ok((await resolvePageInvitationPushTargets(db,[{id:a,user_id:c,type:'broadcast'}])).size===0);ok(count===0);const t=(await resolvePageInvitationPushTargets(db,[{id:a,user_id:c,type:'page_team_invitation'}])).get(a)!;ok(pageInvitationPushData(t).pageInvitationId===b);});
Deno.test('missing, mismatched and duplicate push mappings fail closed',async()=>{for(const data of [[],[{notification_id:a,page_id:a,invitation_id:b,user_id:b,eligible:true}],[{notification_id:a,page_id:a,invitation_id:b,user_id:c,eligible:true},{notification_id:a,page_id:a,invitation_id:b,user_id:c,eligible:true}]]){let rejected=false;try{await resolvePageInvitationPushTargets({rpc:async()=>({data})},[{id:a,user_id:c,type:'page_team_invitation'}]);}catch{rejected=true;}ok(rejected);}});
