const mockSession=jest.fn(),mockRpc=jest.fn(),mockFrom=jest.fn(),mockPayout=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(...a:any[])=>mockRpc(...a),from:(...a:any[])=>mockFrom(...a)}}));
jest.mock('../ticketing',()=>({getMyPayoutState:(...a:any[])=>mockPayout(...a),isPayoutReady:(p:any)=>!!p.ready}));
import {performTicketAction,type TicketAction} from '../creatorTicketAction';
let current=true,results:any[],requests:any[];
const scope={userId:'creator',isCurrent:()=>current};
const action:TicketAction={kind:'tier-sale',eventId:'event',recordId:'tier',label:'Sunday',expected:'on_sale'};
const row=(status='on_sale')=>({id:'tier',event_id:'event',status,price_cents:2400});
function chain(){const request:any={filters:[],headers:[],method:'read'};requests.push(request);const q:any={};for(const method of ['select','update','delete','eq','maybeSingle','setHeader'])q[method]=(...args:any[])=>{if(method==='eq')request.filters.push(args);if(method==='setHeader')request.headers.push(args);if(method==='update'||method==='delete'){request.method=method;request.value=args[0];}return q;};q.then=(resolve:any,reject:any)=>{const next=results.shift();return(next instanceof Error?Promise.reject(next):Promise.resolve(next)).then(resolve,reject);};return q;}
beforeEach(()=>{current=true;results=[];requests=[];jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'creator'},access_token:'creator-token'}}});mockRpc.mockImplementation(()=>({setHeader:()=>Promise.resolve({data:true,error:null})}));mockFrom.mockImplementation(chain);mockPayout.mockResolvedValue({ready:true});});
it('pins the session and uses exact event/record and expected-state filters',async()=>{results=[{data:row()},{data:row('closed')}];expect(await performTicketAction(action,scope)).toBe('confirmed');expect(requests[1].filters).toEqual([['event_id','event'],['id','tier'],['status','on_sale']]);expect(requests[1].value).toEqual({status:'closed'});for(const r of requests)expect(r.headers).toContainEqual(['Authorization','Bearer creator-token']);});
it('recovers a committed change with a read and never toggles it back',async()=>{results=[{data:row()},Error('lost response'),{data:row('closed')}];expect(await performTicketAction(action,scope)).toBe('confirmed');expect(requests.filter(r=>r.method==='update')).toHaveLength(1);});
it('does not call a zero-row response successful when the saved state is unchanged',async()=>{results=[{data:row()},{data:null},{data:row()}];expect(await performTicketAction(action,scope)).toBe('unchanged');});
it('keeps an unknown result when recovery cannot read, and check-only never writes',async()=>{results=[{data:row()},Error('lost'),Error('offline')];expect(await performTicketAction(action,scope)).toBe('unknown');results=[{data:row('closed')}];expect(await performTicketAction(action,scope,true)).toBe('confirmed');expect(requests.filter(r=>r.method==='update')).toHaveLength(1);});
it('does not overwrite a concurrent changed state',async()=>{results=[{data:row('draft')}];expect(await performTicketAction(action,scope)).toBe('changed');expect(requests.every(r=>r.method==='read')).toBe(true);});
it('rejects foreign sessions and denied authority before record access',async()=>{mockSession.mockResolvedValueOnce({data:{session:{user:{id:'other'},access_token:'other-token'}}});await expect(performTicketAction(action,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();mockRpc.mockImplementation(()=>({setHeader:()=>Promise.resolve({data:false})}));await expect(performTicketAction(action,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it('does not dispatch after the visit retires during a read',async()=>{mockRpc.mockImplementation(()=>({setHeader:()=>{current=false;return Promise.resolve({data:true});}}));await expect(performTicketAction(action,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it('rechecks payout readiness before starting paid sales',async()=>{results=[{data:row('closed')}];mockPayout.mockResolvedValue({ready:false});await expect(performTicketAction({...action,expected:'closed'},scope)).rejects.toThrow('payout');expect(requests.every(r=>r.method==='read')).toBe(true);});
it.each(['remove-tier','remove-extra','remove-promo'] as const)('confirms %s only from its exact deletion receipt or authorized absence',async kind=>{results=[{data:{id:'tier',event_id:'event'}},{data:{id:'tier',event_id:'event'}}];expect(await performTicketAction({...action,kind},scope)).toBe('confirmed');expect(requests[1].method).toBe('delete');});
it.each(['remove-question','remove-faq'] as const)('preserves soft retirement for %s',async kind=>{results=[{data:{id:'tier',event_id:'event',is_active:true}},{data:{id:'tier',event_id:'event',is_active:false}}];expect(await performTicketAction({...action,kind},scope)).toBe('confirmed');expect(requests[1].value).toEqual({is_active:false});});
it.each([{kind:'extra-sale',expected:'on_sale',desired:{status:'draft'}},{kind:'promo-active',expected:true,desired:{active:false}}] as const)('preserves $kind state rules',async entry=>{const field=entry.kind==='extra-sale'?'status':'active';results=[{data:{id:'tier',event_id:'event',[field]:entry.expected}},{data:{id:'tier',event_id:'event',...entry.desired}}];expect(await performTicketAction({...action,...entry},scope)).toBe('confirmed');expect(requests[1].value).toEqual(entry.desired);});

const pageExtra:TicketAction={kind:'remove-extra',eventId:'event',recordId:'extra',label:'Blanket',pageId:'page',requestId:'request'};
function settle(outcome:string,patch={},error:any=null){mockRpc.mockImplementation((name:string,args:any)=>({setHeader:()=>Promise.resolve(name==='settle_creator_page_extra_removal'?{error,data:{outcome,page_id:args.p_page_id,event_id:args.p_event_id,user_id:scope.userId,extra_id:args.p_extra_id,request_id:args.p_request_id,...patch}}:{data:true,error:null})}));}
it.each(['in_use','confirmed'])('page-extra %s settlement finishes without a DELETE or record read',async outcome=>{settle(outcome);expect(await performTicketAction(pageExtra,scope,true)).toBe(outcome);expect(mockFrom).not.toHaveBeenCalled();expect(mockRpc).toHaveBeenCalledWith('settle_creator_page_extra_removal',{p_page_id:'page',p_event_id:'event',p_extra_id:'extra',p_request_id:'request'});});
it('unreferenced page-extra check does not remove anything',async()=>{settle('unresolved');results=[{data:{id:'extra',event_id:'event'}}];expect(await performTicketAction(pageExtra,scope,true)).toBe('unchanged');expect(requests.every(r=>r.method==='read')).toBe(true);});
it('unreferenced explicit retry retains exact event and extra',async()=>{settle('unresolved');results=[{data:{id:'extra',event_id:'event'}},{data:{id:'extra',event_id:'event'}}];expect(await performTicketAction(pageExtra,scope)).toBe('confirmed');expect(requests[1].filters).toEqual([['event_id','event'],['id','extra']]);});
it.each([{user_id:'another'},{event_id:'another'},{page_id:'another'},{request_id:'another'},{extra_id:'another'},{outcome:'unknown'}])('mismatched settlement never permits deletion: %j',async patch=>{settle('in_use',patch);await expect(performTicketAction(pageExtra,scope)).rejects.toThrow('original removal');expect(mockFrom).not.toHaveBeenCalled();});
it('failed settlement and missing original request never fall back to DELETE',async()=>{settle('in_use',{},Error('offline'));await expect(performTicketAction(pageExtra,scope)).rejects.toThrow('original removal');await expect(performTicketAction({...pageExtra,requestId:undefined},scope)).rejects.toThrow('kept');expect(mockFrom).not.toHaveBeenCalled();});
