const mockSession=jest.fn(),mockRpc=jest.fn(),mockFrom=jest.fn(),mockQuestions=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(...a:any[])=>mockRpc(...a),from:(...a:any[])=>mockFrom(...a)}}));
jest.mock('../ticketing',()=>({...jest.requireActual('../ticketing'),getQuestions:(...a:any[])=>mockQuestions(...a)}));
import {saveCreatorQuestion,CreatorQuestionRejected,questionDraftProblem,type QuestionDraft} from '../creatorQuestionEditor';
const draft:QuestionDraft={prompt:'Which picnic?',qtype:'single_select',options:['Vegetarian','Classic'],required:true,scope:'per_attendee'};
const row=(patch={})=>({id:'question',event_id:'event',...draft,is_active:true,sort_order:0,created_at:'2026-09-15T00:00:00Z',updated_at:'2026-09-15T00:00:00Z',...patch});
let current=true,results:any[],requests:any[];const scope={userId:'creator',isCurrent:()=>current};
function chain(){const r:any={method:'read',filters:[],headers:[]};requests.push(r);const q:any={};for(const method of ['select','insert','update','eq','is','maybeSingle','setHeader'])q[method]=(...a:any[])=>{if(['insert','update'].includes(method)){r.method=method;r.value=a[0];}if(method==='eq'||method==='is')r.filters.push([method,...a]);if(method==='setHeader')r.headers.push(a);return q;};q.then=(ok:any,bad:any)=>{const result=results.shift();return (result instanceof Error?Promise.reject(result):Promise.resolve(result)).then(ok,bad);};return q;}
beforeEach(()=>{current=true;results=[];requests=[];jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'creator'},access_token:'token'}}});mockRpc.mockReturnValue({setHeader:()=>Promise.resolve({data:true})});mockFrom.mockImplementation(chain);mockQuestions.mockResolvedValue([]);});
it('creates with exact scope and stable question ID',async()=>{results=[{data:null},{data:row()}];await saveCreatorQuestion('event','question',draft,null,scope);expect(requests[1].value).toMatchObject({id:'question',event_id:'event',scope:'per_attendee',required:true});for(const r of requests)expect(r.headers).toContainEqual(['Authorization','Bearer token']);});
it('reconciles a committed save instead of inserting another question',async()=>{results=[{data:null},Error('lost'),{data:row()}];await saveCreatorQuestion('event','question',draft,null,scope);expect(requests.filter(r=>r.method==='insert')).toHaveLength(1);});
it('does not resurrect retired questions',async()=>{results=[{data:row({is_active:false})}];await expect(saveCreatorQuestion('event','question',draft,row(),scope)).rejects.toThrow('changed');expect(requests).toHaveLength(1);});
it('preserves ID/answer links while editing and checks JSON choices atomically',async()=>{const baseline=row({prompt:'Original'});results=[{data:baseline},{data:row()}];await saveCreatorQuestion('event','question',draft,baseline,scope);expect(requests[1].filters).toContainEqual(['eq','options',JSON.stringify(draft.options)]);expect(requests[1].value.updated_at).toBeDefined();expect(requests[1].value).not.toHaveProperty('id');expect(mockFrom.mock.calls.every(c=>c[0]==='ticket_questions')).toBe(true);});
it('refuses a stale changed question',async()=>{results=[{data:row({prompt:'Another edit'})}];await expect(saveCreatorQuestion('event','question',draft,row(),scope)).rejects.toThrow('changed');expect(requests).toHaveLength(1);});
it('enforces the existing 11 active question cap',async()=>{results=[{data:null}];mockQuestions.mockResolvedValue(Array(11).fill({}));await expect(saveCreatorQuestion('event','question',draft,null,scope)).rejects.toThrow('11');expect(requests).toHaveLength(1);});
it('rejects changed account before private reads',async()=>{mockSession.mockResolvedValue({data:{session:{user:{id:'other'},access_token:'other'}}});await expect(saveCreatorQuestion('event','question',draft,null,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it.each([{prompt:' '},{qtype:'unknown'},{options:['only one']},{options:Array(51).fill('choice')},{scope:'other'}])('rejects invalid draft %j',patch=>expect(questionDraftProblem({...draft,...patch} as QuestionDraft)).not.toBeNull());

it('read-only recovery never inserts or updates an unchanged original',async()=>{results=[{data:null}];await expect(saveCreatorQuestion('event','question',draft,null,scope,false)).rejects.toThrow('not yet confirmed');expect(requests.every(r=>r.method==='read')).toBe(true);expect(mockQuestions).not.toHaveBeenCalled();});

const fresh=()=>({previouslyDispatched:false,beforeDispatch:jest.fn(async()=>true)});
it('releases a fresh cap refusal without recording or sending a mutation',async()=>{results=[{data:null}];mockQuestions.mockResolvedValue(Array(11).fill({}));const dispatch=fresh();await expect(saveCreatorQuestion('event','question',draft,null,scope,true,dispatch)).rejects.toBeInstanceOf(CreatorQuestionRejected);expect(dispatch.beforeDispatch).not.toHaveBeenCalled();expect(requests).toHaveLength(1);});
it('keeps a previous uncertain save at the cap',async()=>{results=[{data:null}];mockQuestions.mockResolvedValue(Array(11).fill({}));const error=await saveCreatorQuestion('event','question',draft,null,scope,true,{...fresh(),previouslyDispatched:true}).catch(e=>e);expect(error).not.toBeInstanceOf(CreatorQuestionRejected);expect(error.message).toContain('still needs to be checked');});
it.each(['23514','23505','P0001'])('releases a fresh SQL %s rejection only after unchanged readback',async code=>{results=[{data:null},{data:null,error:{code}},{data:null}];const dispatch=fresh();await expect(saveCreatorQuestion('event','question',draft,null,scope,true,dispatch)).rejects.toBeInstanceOf(CreatorQuestionRejected);expect(dispatch.beforeDispatch).toHaveBeenCalledTimes(1);});
it('never releases an earlier ambiguous dispatch after a retry is rejected',async()=>{results=[{data:null},{data:null,error:{code:'23514'}},{data:null}];const error=await saveCreatorQuestion('event','question',draft,null,scope,true,{...fresh(),previouslyDispatched:true}).catch(e=>e);expect(error).not.toBeInstanceOf(CreatorQuestionRejected);expect(error.message).toContain('could not be confirmed');});
it('accepts exact saved evidence even after a rejected retry',async()=>{results=[{data:null},{data:null,error:{code:'23505'}},{data:row()}];await expect(saveCreatorQuestion('event','question',draft,null,scope,true,fresh())).resolves.toMatchObject({id:'question'});});
it.each([Error('timeout'),{data:null,error:{code:'500'}}])('keeps transport/server uncertainty locked',async failure=>{results=[{data:null},failure,{data:null}];const error=await saveCreatorQuestion('event','question',draft,null,scope,true,fresh()).catch(e=>e);expect(error).not.toBeInstanceOf(CreatorQuestionRejected);});
it('does not dispatch if durable dispatch recording fails',async()=>{results=[{data:null}];await expect(saveCreatorQuestion('event','question',draft,null,scope,true,{...fresh(),beforeDispatch:async()=>false})).rejects.toThrow('on this device');expect(requests.every(r=>r.method==='read')).toBe(true);});
it('does not release when rejection readback fails',async()=>{results=[{data:null},{data:null,error:{code:'23514'}},Error('offline')];const error=await saveCreatorQuestion('event','question',draft,null,scope,true,fresh()).catch(e=>e);expect(error).not.toBeInstanceOf(CreatorQuestionRejected);});
it('keeps read-only checks independent of dispatch recording',async()=>{results=[{data:null}];const dispatch=fresh();await expect(saveCreatorQuestion('event','question',draft,null,scope,false,dispatch)).rejects.toThrow('not yet confirmed');expect(dispatch.beforeDispatch).not.toHaveBeenCalled();});
