const mockSession=jest.fn(),mockRpc=jest.fn(),mockFrom=jest.fn(),mockReady=jest.fn(),mockTiers=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(...a:any[])=>mockRpc(...a),from:(...a:any[])=>mockFrom(...a)}}));
jest.mock('../ticketing',()=>({...jest.requireActual('../ticketing'),getPaidTicketEventReadiness:(...a:any[])=>mockReady(...a),getTiers:(...a:any[])=>mockTiers(...a)}));
import {saveCreatorTier,tierDraftProblem} from '../creatorTierEditor';
import type {TierDraft,TicketTier} from '../ticketing';
const draft:TierDraft={name:'Sunset entry',description:null,price_cents:1200,quantity_cap:24,per_order_min:1,per_order_max:4,visibility:'visible',status:'draft',sales_open_at:null,sales_close_at:null};
const row=(patch={})=>({id:'tier',event_id:'event',...draft,sort_order:0,opens_after_tier_id:null,...patch}) as TicketTier;
let current=true,results:any[],requests:any[];const scope={userId:'creator',isCurrent:()=>current};
function chain(){const r:any={method:'read',filters:[],headers:[]};requests.push(r);const q:any={};for(const method of ['select','insert','update','eq','is','maybeSingle','setHeader'])q[method]=(...a:any[])=>{if(['insert','update'].includes(method)){r.method=method;r.value=a[0];}if(method==='eq'||method==='is')r.filters.push([method,...a]);if(method==='setHeader')r.headers.push(a);return q;};q.then=(ok:any,bad:any)=>{const result=results.shift();return (result instanceof Error?Promise.reject(result):Promise.resolve(result)).then(ok,bad);};return q;}
beforeEach(()=>{current=true;results=[];requests=[];jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'creator'},access_token:'token'}}});mockRpc.mockReturnValue({setHeader:()=>Promise.resolve({data:true})});mockFrom.mockImplementation(chain);mockReady.mockResolvedValue({ok:true});mockTiers.mockResolvedValue([]);});
it('creates with a stable ID and confirms the exact returned draft',async()=>{results=[{data:null},{data:row()}];expect(await saveCreatorTier('event','tier',draft,null,scope)).toEqual(row());expect(requests[1].value).toMatchObject({id:'tier',event_id:'event',status:'draft'});for(const r of requests)expect(r.headers).toContainEqual(['Authorization','Bearer token']);});
it('returns a previously saved exact new ticket without inserting another',async()=>{results=[{data:row()}];await saveCreatorTier('event','tier',draft,null,scope);expect(requests.every(r=>r.method==='read')).toBe(true);});
it('reconciles a lost insert acknowledgement without a second write',async()=>{results=[{data:null},Error('lost'),{data:row()}];await saveCreatorTier('event','tier',draft,null,scope);expect(requests.filter(r=>r.method==='insert')).toHaveLength(1);});
it('preserves current sale status and checks original edited fields atomically',async()=>{const baseline=row({name:'Original',status:'on_sale'});results=[{data:baseline},{data:row({status:'closed'})}];await saveCreatorTier('event','tier',draft,baseline,scope);expect(requests[1].value).not.toHaveProperty('status');expect(requests[1].filters).toContainEqual(['eq','name','Original']);expect(requests[1].filters).toContainEqual(['is','description',null]);});
it('refuses to overwrite an edited field changed by another session',async()=>{results=[{data:row({name:'Someone else’s change'})}];await expect(saveCreatorTier('event','tier',draft,row({name:'Original'}),scope)).rejects.toThrow('changed');expect(requests.every(r=>r.method==='read')).toBe(true);});
it('retains the missing end time code and four-tier limit',async()=>{results=[{data:null}];mockReady.mockResolvedValue({ok:false,reason:'missing_end_time',message:'End time required'});await expect(saveCreatorTier('event','tier',draft,null,scope)).rejects.toMatchObject({code:'event_end_time_required'});mockReady.mockResolvedValue({ok:true});mockTiers.mockResolvedValue([1,2,3,4]);results=[{data:null}];await expect(saveCreatorTier('event','tier',draft,null,scope)).rejects.toThrow('four');});
it('rejects mismatched accounts before any record query',async()=>{mockSession.mockResolvedValue({data:{session:{user:{id:'other'},access_token:'other'}}});await expect(saveCreatorTier('event','tier',draft,null,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it.each([{price_cents:-500},{price_cents:1200.5},{quantity_cap:1.5},{per_order_max:0},{per_order_min:5,per_order_max:4}])('rejects malformed draft %j',patch=>expect(tierDraftProblem({...draft,...patch})).not.toBeNull());
