const mockStorage=new Map<string,string>(),mockGet=jest.fn(),mockSet=jest.fn(),mockRemove=jest.fn();
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:(...a:unknown[])=>mockGet(...a),setItem:(...a:unknown[])=>mockSet(...a),removeItem:(...a:unknown[])=>mockRemove(...a)}}));
jest.mock('expo-crypto',()=>({randomUUID:()=> '0fe10000-0000-4000-8000-000000000010'}));
jest.mock('../supabase',()=>({supabase:{}}));
jest.mock('../creatorPageEventSave',()=>({...jest.requireActual('../creatorPageEventSave'),getPageEventSaveState:jest.fn(),getPageEventSaveAttempt:jest.fn(),savePageEvent:jest.fn()}));
import {preparePageEventCopyStop,readPageEventCopyStop,resolvePageEventCopyStop,clearPageEventCopyStop} from '../creatorPageEventCopyStop';
import {getPageEventSaveState,getPageEventSaveAttempt,savePageEvent} from '../creatorPageEventSave';
const id=(n:number)=>`0fe10000-0000-4000-8000-${String(n).padStart(12,'0')}`,page=id(1),event=id(2),user=id(3),copyId=id(4),version='2026-09-15T01:00:00.123456Z';
let active=true,target:any,copy:any,originalReceipt:any,barrierReceipt:any;
const scope={userId:user,isCurrent:()=>active},read=jest.mocked(getPageEventSaveState),receipt=jest.mocked(getPageEventSaveAttempt),save=jest.mocked(savePageEvent);
const prepare=()=>preparePageEventCopyStop(copy,scope);
beforeEach(()=>{jest.resetAllMocks();mockStorage.clear();active=true;originalReceipt=null;barrierReceipt=null;
 mockGet.mockImplementation(async k=>mockStorage.get(k)??null);mockSet.mockImplementation(async(k,v)=>{mockStorage.set(k,v);});mockRemove.mockImplementation(async k=>{mockStorage.delete(k);});
 const fields={title:'Original draft',description:'',image_url:'',event_date:'',start_time:null,end_time:null,venue:'',venue_address:'',category:'community',external_url:'',ticket_price:'',public_name:'Page',pin_to_chat:true,description_blocks:[],confirmation_message:''};
 target={pageId:page,eventId:event,updatedAt:version,status:'Draft',fields,offerType:'free_event',ticketCapacity:20,latitude:null,longitude:null,canManageTickets:false};
 const input={fields,offerType:target.offerType,ticketCapacity:20,latitude:null,longitude:null,expectedUpdatedAt:version};
 copy={version:1,pageId:page,eventId:event,userId:user,requestId:copyId,destination:input,input:{...input,fields:{...fields,title:'Copied story',description:'Complete source'}}};
 read.mockImplementation(async()=>JSON.parse(JSON.stringify(target)));receipt.mockImplementation(async(_p,_e,r)=>r===copyId?originalReceipt:barrierReceipt);
 save.mockImplementation(async(_p,_e,r,input)=>{target={...target,updatedAt:'2026-09-15T01:00:00.123457Z'};barrierReceipt={...target,requestId:r,userId:user};return barrierReceipt;});
});
it('persists separate recovery using the existing preserve-body value before any write',async()=>{const a=await prepare();expect(a.created).toBe(true);expect(a.attempt.copyRequestId).toBe(copyId);expect(a.attempt.input.fields).toEqual({...target.fields,description_blocks:null});expect(save).not.toHaveBeenCalled();expect(await readPageEventCopyStop(page,event,scope)).toEqual(a.attempt);});
it('lost preparation response retains the same recovery identity without dispatch',async()=>{mockSet.mockImplementationOnce(async(k,v)=>{mockStorage.set(k,v);throw Error('Lost disk');});await expect(prepare()).rejects.toThrow('Lost');expect((await prepare()).created).toBe(false);expect(save).not.toHaveBeenCalled();});
it('Check alone cannot change an unchanged destination',async()=>{const {attempt}=await prepare();await expect(resolvePageEventCopyStop(attempt,scope,'check')).resolves.toEqual({state:'pending'});expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();});
it('explicit retry preserves content and advances the old copy version through existing atomic save',async()=>{const {attempt}=await prepare(),before=JSON.stringify(target.fields);await expect(resolvePageEventCopyStop(attempt,scope,'retry')).resolves.toMatchObject({state:'kept'});expect(save).toHaveBeenCalledWith(page,event,attempt.requestId,attempt.input,expect.objectContaining({userId:user,isCurrent:expect.any(Function)}));expect(JSON.stringify(target.fields)).toBe(before);expect(mockStorage.size).toBe(1);});
it('a newer destination is kept without replaying any content',async()=>{const {attempt}=await prepare();target={...target,updatedAt:'2026-09-16T00:00:00Z',fields:{...target.fields,title:'Other editor'}};await expect(resolvePageEventCopyStop(attempt,scope,'retry')).resolves.toMatchObject({state:'kept',event:{fields:{title:'Other editor'}}});expect(save).not.toHaveBeenCalled();});
it('a committed original wins before any recovery save',async()=>{const {attempt}=await prepare();originalReceipt={...target,...copy.input,requestId:copyId,userId:user};await expect(resolvePageEventCopyStop(attempt,scope,'retry')).resolves.toMatchObject({state:'saved'});expect(save).not.toHaveBeenCalled();});
it('the original winning the compare-and-save race is returned as saved',async()=>{const {attempt}=await prepare();save.mockImplementationOnce(async()=>{originalReceipt={...target,...copy.input,requestId:copyId,userId:user};target.updatedAt='2026-09-16T00:00:00Z';throw {code:'PT409'};});await expect(resolvePageEventCopyStop(attempt,scope,'retry')).resolves.toMatchObject({state:'saved'});expect(save).toHaveBeenCalledTimes(1);});
it('another editor winning the compare-and-save race is preserved',async()=>{const {attempt}=await prepare();save.mockImplementationOnce(async()=>{target={...target,updatedAt:'2026-09-16T00:00:00Z',fields:{...target.fields,title:'Newer content'}};throw {code:'PT409'};});await expect(resolvePageEventCopyStop(attempt,scope,'retry')).resolves.toMatchObject({state:'kept',event:{fields:{title:'Newer content'}}});});
it('lost committed recovery response is checked without a second write',async()=>{const {attempt}=await prepare();const original=save.getMockImplementation()!;save.mockImplementationOnce(async(...a)=>{await original(...a);throw Error('Lost response');});await expect(resolvePageEventCopyStop(attempt,scope,'retry')).rejects.toThrow('Lost');await expect(resolvePageEventCopyStop(attempt,scope,'check')).resolves.toMatchObject({state:'kept'});expect(save).toHaveBeenCalledTimes(1);});
it.each([Error('Offline'),{code:'42501'}])('unknown or denied recovery retains the intent %j',async error=>{const {attempt}=await prepare();save.mockRejectedValueOnce(error);await expect(resolvePageEventCopyStop(attempt,scope,'retry')).rejects.toEqual(error);expect(await readPageEventCopyStop(page,event,scope)).toEqual(attempt);expect(mockRemove).not.toHaveBeenCalled();});
it('a mismatched saved original cannot be reported as successful',async()=>{const {attempt}=await prepare();originalReceipt={...target,requestId:copyId,userId:user};await expect(resolvePageEventCopyStop(attempt,scope,'check')).rejects.toThrow('receipt');expect(save).not.toHaveBeenCalled();});
it('a recovery response that did not advance the version is not terminal',async()=>{const {attempt}=await prepare();save.mockResolvedValueOnce({...target,requestId:attempt.requestId,userId:user});await expect(resolvePageEventCopyStop(attempt,scope,'retry')).rejects.toThrow('advance');expect(mockRemove).not.toHaveBeenCalled();});
it('a retired visit cannot dispatch after a late destination read',async()=>{const {attempt}=await prepare();read.mockImplementationOnce(async()=>{active=false;return target;});await expect(resolvePageEventCopyStop(attempt,scope,'retry')).rejects.toThrow();expect(save).not.toHaveBeenCalled();});
it('pending recovery cannot be cleared; terminal optional cleanup failure is retryable',async()=>{const {attempt}=await prepare();await expect(clearPageEventCopyStop(attempt,scope)).rejects.toThrow('before clearing');await resolvePageEventCopyStop(attempt,scope,'retry');mockRemove.mockRejectedValueOnce(Error('Disk'));expect(await clearPageEventCopyStop(attempt,scope)).toBe(false);expect(await clearPageEventCopyStop(attempt,scope)).toBe(true);expect(mockStorage.size).toBe(0);expect(save).toHaveBeenCalledTimes(1);});
it('concurrent explicit retries share one durable barrier and dispatch only once',async()=>{const {attempt}=await prepare();const results=await Promise.all([resolvePageEventCopyStop(attempt,scope,'retry'),resolvePageEventCopyStop(attempt,scope,'retry')]);expect(results.every(r=>r.state==='kept')).toBe(true);expect(save).toHaveBeenCalledTimes(1);});
it('separate accounts never load another person’s recovery',async()=>{await prepare();expect(await readPageEventCopyStop(page,event,{...scope,userId:id(20)})).toBeNull();});
it('a reused copy ID with changed original content cannot adopt an earlier recovery',async()=>{await prepare();copy.input.fields.title='Different payload';await expect(prepare()).rejects.toThrow('different');expect(save).not.toHaveBeenCalled();});
it('a malformed barrier receipt cannot confirm recovery',async()=>{const {attempt}=await prepare();barrierReceipt={...target,updatedAt:'2026-09-16T00:00:00Z',fields:{...target.fields,title:'Unexpected'}};await expect(resolvePageEventCopyStop(attempt,scope,'check')).rejects.toThrow('confirmed');expect(save).not.toHaveBeenCalled();});
it('lost cleanup acknowledgement does not replay the terminal destination save',async()=>{const {attempt}=await prepare();await resolvePageEventCopyStop(attempt,scope,'retry');mockRemove.mockImplementationOnce(async k=>{mockStorage.delete(k);throw Error('Lost ack');});expect(await clearPageEventCopyStop(attempt,scope)).toBe(false);expect(await clearPageEventCopyStop(attempt,scope)).toBe(true);expect(save).toHaveBeenCalledTimes(1);});

it('a stalled Keep save retains its original barrier and becomes recoverable by Check',async()=>{
 jest.useFakeTimers();try{
  const {attempt}=await prepare();save.mockImplementationOnce(async()=>{target.updatedAt='2026-09-16T00:00:00Z';return new Promise(()=>{});});
  let failure:any;const pending=resolvePageEventCopyStop(attempt,scope,'retry').catch(e=>{failure=e;});
  await jest.advanceTimersByTimeAsync(25_001);expect(failure).toBeInstanceOf(Error);await pending;
  await expect(resolvePageEventCopyStop(attempt,scope,'check')).resolves.toMatchObject({state:'kept'});expect(save).toHaveBeenCalledTimes(1);expect(mockRemove).not.toHaveBeenCalled();
 }finally{jest.useRealTimers();}
});
