const mockStore=new Map<string,string>(),mockFiles=new Map<string,any>(),mockCopy=jest.fn(),mockDelete=jest.fn(),mockState=jest.fn(),mockReadRemote=jest.fn(),mockSet=jest.fn(),mockInfo=jest.fn();let mockId=0;
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:async(k:string)=>mockStore.get(k)??null,setItem:async(k:string,v:string)=>mockSet(k,v)}}));
jest.mock('expo-file-system/legacy',()=>({documentDirectory:'file:///private/app/',getInfoAsync:(...a:unknown[])=>mockInfo(...a),makeDirectoryAsync:async()=>{},copyAsync:(...a:unknown[])=>mockCopy(...a),deleteAsync:(...a:unknown[])=>mockDelete(...a)}));
jest.mock('expo-crypto',()=>({randomUUID:()=>`0fa40000-0000-4000-8000-${String(++mockId).padStart(12,'0')}`,CryptoDigestAlgorithm:{SHA256:'sha256'},digestStringAsync:async(_:string,s:string)=>require('crypto').createHash('sha256').update(s).digest('hex')}));
jest.mock('../creatorPageEventSave',()=>({getPageEventSaveState:(...a:unknown[])=>mockState(...a)}));
jest.mock('../creatorPageEventMedia',()=>({...jest.requireActual('../creatorPageEventMedia'),assertPageEventMediaAccount:async(s:any)=>{if(!s.isCurrent())throw Error('Retired');},getPageEventMediaAttempt:(...a:unknown[])=>mockReadRemote(...a)}));
import {preparePageEventMediaAttempt,readPageEventMediaAttempts,verifyPageEventMediaFile,clearPageEventMediaAttempt} from '../creatorPageEventMediaAttempt';
const page='f5d7644a-2ff5-4def-b0ab-d04b8250892b',event='0fa40000-0000-4000-8000-000000000100',user='753c5b17-ca8d-431f-ad8f-0d9b70c0dccb',source='file:///picker/original.mp4';let current=true;
const scope={userId:user,isCurrent:()=>current};
const prepare=()=>preparePageEventMediaAttempt(page,event,'video','video/mp4',source,scope);
beforeEach(()=>{jest.clearAllMocks();mockId=0;current=true;mockStore.clear();mockFiles.clear();mockFiles.set(source,{exists:true,isDirectory:false,size:1000,md5:'a'.repeat(32)});mockInfo.mockImplementation(async(p:string)=>mockFiles.get(p)??{exists:false});mockState.mockResolvedValue({status:'Draft'});mockCopy.mockImplementation(async({from,to})=>{mockFiles.set(to,{...mockFiles.get(from)});});mockDelete.mockImplementation(async(p:string)=>{mockFiles.delete(p);});mockSet.mockImplementation(async(k:string,v:string)=>{mockStore.set(k,v);});mockReadRemote.mockResolvedValue(null);});
it('copies the original file under the account/page/event before recording intent',async()=>{const {attempt:a}=await prepare();expect(a.fileUri).toContain(`/${user}/${page}/${event}/`);expect(mockFiles.has(a.fileUri)).toBe(true);expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([a]);expect(await verifyPageEventMediaFile(a,scope)).toBe(a.fileUri);expect(mockReadRemote).not.toHaveBeenCalled();});
it('serial repeated preparation reuses the original pending file and ID',async()=>{const [a,b]=await Promise.all([prepare(),prepare()]);expect(a.attempt).toEqual(b.attempt);expect(a.created).toBe(true);expect(b.created).toBe(false);expect(mockCopy).toHaveBeenCalledTimes(1);});
it('retains multiple distinct gallery/video files without overwriting earlier intents',async()=>{const a=await prepare();mockFiles.set(source,{exists:true,isDirectory:false,size:1001,md5:'b'.repeat(32)});const b=await prepare();expect(a.attempt.mediaId).not.toBe(b.attempt.mediaId);expect(await readPageEventMediaAttempts(page,event,scope)).toHaveLength(2);});
it('preserves a file and marker when persistence commits but its response is lost',async()=>{mockSet.mockImplementation(async(k:string,v:string)=>{mockStore.set(k,v);throw Error('Lost local acknowledgement');});await expect(prepare()).rejects.toThrow();const [a]=await readPageEventMediaAttempts(page,event,scope);expect(mockFiles.has(a.fileUri)).toBe(true);expect(mockDelete).not.toHaveBeenCalled();});
it('rejects changed original bytes before a retry',async()=>{const {attempt:a}=await prepare();mockFiles.set(a.fileUri,{exists:true,isDirectory:false,size:1000,md5:'b'.repeat(32)});await expect(verifyPageEventMediaFile(a,scope)).rejects.toThrow('changed');expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([a]);});
it('does not erase a corrupt stored attempt list',async()=>{await prepare();const k=[...mockStore.keys()][0];mockStore.set(k,'{broken');await expect(prepare()).rejects.toThrow();expect(mockStore.get(k)).toBe('{broken');});
it('a retired scope cannot prepare or read another account’s attempts',async()=>{await prepare();current=false;await expect(readPageEventMediaAttempts(page,event,scope)).rejects.toThrow();expect(()=>prepare()).toThrow();expect(mockStore.size).toBe(1);});
it('rejects a changed copy before persisting an upload intent',async()=>{mockCopy.mockImplementation(async({to})=>mockFiles.set(to,{exists:true,isDirectory:false,size:1001,md5:'b'.repeat(32)}));await expect(prepare()).rejects.toThrow('changed');expect(mockStore.size).toBe(0);expect(mockDelete).toHaveBeenCalledTimes(1);});
it('does not copy files when backend page access is unavailable',async()=>{mockState.mockRejectedValue(Error('Revoked'));await expect(prepare()).rejects.toThrow('Revoked');expect(mockCopy).not.toHaveBeenCalled();});
it('unknown backend attachment cannot delete the original file',async()=>{const {attempt:a}=await prepare();await expect(clearPageEventMediaAttempt(a,scope)).rejects.toThrow('Check');expect(mockDelete).not.toHaveBeenCalled();expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([a]);});
it('a fresh confirmed attachment clears only its exact original local attempt',async()=>{const {attempt:a}=await prepare();mockReadRemote.mockResolvedValue({...a,readyAt:'time',objectPresent:true,attached:true,abandonedAt:null});expect(await clearPageEventMediaAttempt(a,scope)).toBe(true);expect(mockReadRemote).toHaveBeenCalledWith(page,event,a,scope);expect(mockFiles.has(a.fileUri)).toBe(false);expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([]);});
it('failed local file deletion retains the recovery record',async()=>{const {attempt:a}=await prepare();mockReadRemote.mockResolvedValue({...a,readyAt:null,objectPresent:false,attached:false,abandonedAt:'time'});mockDelete.mockRejectedValue(Error('Disk'));await expect(clearPageEventMediaAttempt(a,scope)).rejects.toThrow('Disk');expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([a]);});
it('clearing fails closed for another receipt or missing confirmed bytes',async()=>{const {attempt:a}=await prepare();mockReadRemote.mockResolvedValue({...a,mediaId:event,readyAt:'time',objectPresent:true,attached:true});await expect(clearPageEventMediaAttempt(a,scope)).rejects.toThrow();mockReadRemote.mockResolvedValue({...a,readyAt:'time',objectPresent:false,attached:true});await expect(clearPageEventMediaAttempt(a,scope)).rejects.toThrow();expect(mockDelete).not.toHaveBeenCalled();});

it('rejects oversized video before allocating native checksum work',async()=>{mockFiles.set(source,{exists:true,isDirectory:false,size:104857601,md5:'a'.repeat(32)});await expect(prepare()).rejects.toThrow('size limit');expect(mockInfo.mock.calls.every(call=>!call[1]?.md5)).toBe(true);expect(mockCopy).not.toHaveBeenCalled();});

it('terminal cleanup cannot delete bytes while the exact native transfer lease remains active',async()=>{
 const {claimPageEventMediaReuseWork}=require('../creatorPageEventMediaReuseWork');const {attempt:a}=await prepare();
 mockReadRemote.mockResolvedValue({...a,readyAt:'time',objectPresent:true,attached:true,abandonedAt:null});
 const release=claimPageEventMediaReuseWork(user,page,event,a.mediaId);
 try{await expect(clearPageEventMediaAttempt(a,scope)).rejects.toThrow('already in progress');expect(mockDelete).not.toHaveBeenCalled();expect(await readPageEventMediaAttempts(page,event,scope)).toEqual([a]);}finally{release();}
 expect(await clearPageEventMediaAttempt(a,scope)).toBe(true);expect(mockFiles.has(a.fileUri)).toBe(false);
});
