const mockStorage=new Map<string,string>(),mockGet=jest.fn(),mockSet=jest.fn(),mockRemove=jest.fn();
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:(...a:unknown[])=>mockGet(...a),setItem:(...a:unknown[])=>mockSet(...a),removeItem:(...a:unknown[])=>mockRemove(...a)}}));
jest.mock('expo-crypto',()=>({randomUUID:()=> '0fc50000-0000-4000-8000-000000000010'}));
jest.mock('../creatorPageEventCopyCleanup',()=>({cleanupStoppedPageEventCopy:jest.fn()}));
jest.mock('../creatorPageEventCopyStop',()=>({readPageEventCopyStop:jest.fn(),preparePageEventCopyStop:jest.fn(),resolvePageEventCopyStop:jest.fn(),clearPageEventCopyStop:jest.fn()}));
import {cleanupStoppedPageEventCopy} from '../creatorPageEventCopyCleanup';
import {readPageEventCopyStop,preparePageEventCopyStop,resolvePageEventCopyStop,clearPageEventCopyStop} from '../creatorPageEventCopyStop';
jest.mock('../supabase',()=>({supabase:{}}));
jest.mock('../creatorPageEventSave',()=>({...jest.requireActual('../creatorPageEventSave'),getPageEventSaveState:jest.fn(),getPageEventSaveAttempt:jest.fn(),savePageEvent:jest.fn()}));
jest.mock('../creatorPageEventTemplate',()=>({getPageEventTemplate:jest.fn()}));
jest.mock('../creatorPageEventMediaReuseAttempt',()=>({readPageEventMediaReuseAttempts:jest.fn(),preparePageEventMediaReuseAttempt:jest.fn(),clearPageEventMediaReuseAttempt:jest.fn()}));
jest.mock('../creatorPageEventMediaReuse',()=>({getPageEventMediaReuseAttempt:jest.fn()}));
jest.mock('../creatorPageEventMediaReuseTransfer',()=>({startPageEventMediaReuseTransfer:jest.fn()}));
jest.mock('../legacyEventMediaSource',()=>({...jest.requireActual('../legacyEventMediaSource'),getLegacyEventMediaSource:jest.fn(),assertLegacyEventMediaSource:jest.fn()}));
jest.mock('../legacyEventMediaImport',()=>({startLegacyEventMediaImport:jest.fn(),clearLegacyEventMediaImport:jest.fn()}));
import {preparePageEventReuse,readPageEventReuse,startPageEventReuse,acknowledgeKeptPageEventReuse} from '../creatorPageEventReuse';
import {getPageEventSaveState,getPageEventSaveAttempt,savePageEvent} from '../creatorPageEventSave';
import {getPageEventTemplate} from '../creatorPageEventTemplate';
import {planPageEventReuse} from '../creatorPageEventReusePlan';
import {readPageEventMediaReuseAttempts,preparePageEventMediaReuseAttempt,clearPageEventMediaReuseAttempt} from '../creatorPageEventMediaReuseAttempt';
import {getPageEventMediaReuseAttempt} from '../creatorPageEventMediaReuse';
import {startPageEventMediaReuseTransfer} from '../creatorPageEventMediaReuseTransfer';
import {getLegacyEventMediaSource,assertLegacyEventMediaSource} from '../legacyEventMediaSource';
import {startLegacyEventMediaImport,clearLegacyEventMediaImport} from '../legacyEventMediaImport';
const id=(n:number)=>`0fc50000-0000-4000-8000-${String(n).padStart(12,'0')}`,pa=id(1),ea=id(2),pb=id(3),eb=id(4),user=id(5),request=id(10),version='2026-09-15T00:00:00Z';
let active=true,original:any,target:any,remote:any,mediaAttempts:any[];
const scope={userId:user,isCurrent:()=>active},source={kind:'event' as const,pageId:pa,eventId:ea};
const state=jest.mocked(getPageEventSaveState),getSave=jest.mocked(getPageEventSaveAttempt),save=jest.mocked(savePageEvent),getTemplate=jest.mocked(getPageEventTemplate),prepareMedia=jest.mocked(preparePageEventMediaReuseAttempt),getMedia=jest.mocked(getPageEventMediaReuseAttempt),clearMedia=jest.mocked(clearPageEventMediaReuseAttempt),readMedia=jest.mocked(readPageEventMediaReuseAttempts),transfer=jest.mocked(startPageEventMediaReuseTransfer);
const fields=()=>({title:'Saved story',description:'Full overview',image_url:'creator-event-media:'+ea+'/private-'+id(40)+'.jpg',event_date:'2027-01-01',start_time:'2027-01-01T20:00:00Z',end_time:'2027-01-01T21:00:00Z',venue:'LA room',venue_address:'Los Angeles',category:'community',external_url:'',ticket_price:'50',public_name:'Source page',pin_to_chat:true,description_blocks:[{type:'text',content:'Full first story'},{type:'image',path:ea+'/private-'+id(41)+'.jpg',alt:'Photo'},{type:'text',content:'Between media'},{type:'video',path:ea+'/private-'+id(42)+'.mp4',poster:ea+'/private-'+id(43)+'.jpg',alt:'Clip'},{type:'faq'}],confirmation_message:'Arrival details'});
const receipt=(a:any)=>({...a,objectName:eb+'/private-'+a.mediaId+(a.purpose==='video'?'.mp4':'.jpg'),byteSize:a.source.byteSize,mimeType:a.source.mimeType,contentDigest:a.source.contentDigest,source:a.source,readyAt:version,objectPresent:true,abandonedAt:null,attached:false});
const prepare=()=>preparePageEventReuse(pb,eb,source,scope);
const legacySource=jest.mocked(getLegacyEventMediaSource),legacyImport=jest.mocked(startLegacyEventMediaImport),legacyClear=jest.mocked(clearLegacyEventMediaImport);
const run=(action:'retry'|'check'|'keep'='retry')=>startPageEventReuse(pb,eb,request,scope,action).done;
beforeEach(()=>{
 jest.resetAllMocks();mockStorage.clear();active=true;
 jest.mocked(readPageEventCopyStop).mockResolvedValue(null);jest.mocked(preparePageEventCopyStop).mockImplementation(async()=>({created:true,attempt:{copyRequestId:request} as any}));jest.mocked(resolvePageEventCopyStop).mockImplementation(async()=>({state:'kept',event:target}));jest.mocked(clearPageEventCopyStop).mockResolvedValue(true);jest.mocked(cleanupStoppedPageEventCopy).mockResolvedValue(undefined);remote=null;mediaAttempts=[];
 original={pageId:pa,eventId:ea,status:'Completed',updatedAt:version,fields:fields(),offerType:'free_event',ticketCapacity:50,latitude:34,longitude:-118,canManageTickets:true};
 target={pageId:pb,eventId:eb,status:'Draft',updatedAt:version,fields:{...fields(),title:'New draft',description:'',image_url:'',description_blocks:[],event_date:'',start_time:null,end_time:null,venue:'',venue_address:'',ticket_price:'',public_name:'Destination page'},offerType:'ticketed_event',ticketCapacity:20,latitude:null,longitude:null,canManageTickets:false};
 mockGet.mockImplementation(async k=>mockStorage.get(k)??null);mockSet.mockImplementation(async(k,v)=>{mockStorage.set(k,v);});mockRemove.mockImplementation(async k=>{mockStorage.delete(k);});
 state.mockImplementation(async(page)=>JSON.parse(JSON.stringify(page===pa?original:target)));getSave.mockImplementation(async()=>remote);
 save.mockImplementation(async(page,event,requestId,input)=>{remote={...target,fields:input.fields,offerType:input.offerType,ticketCapacity:input.ticketCapacity,latitude:input.latitude,longitude:input.longitude,requestId,userId:user};return remote;});
 getTemplate.mockImplementation(async()=>({sourceUpdatedAt:version,reusePlan:planPageEventReuse(pa,ea,original.fields)}) as any);
 prepareMedia.mockImplementation(async(page,event,purpose,s)=>{let a=mediaAttempts.find(v=>v.purpose===purpose&&v.source.mediaId===s.mediaId);if(a)return{attempt:a,created:false};a={version:1,pageId:pb,eventId:eb,userId:user,mediaId:id(100+mediaAttempts.length),purpose,source:{...s,purpose,byteSize:100,mimeType:purpose==='video'?'video/mp4':'image/jpeg',contentDigest:'a'.repeat(64),objectName:ea+'/private-'+s.mediaId+(purpose==='video'?'.mp4':'.jpg')}};mediaAttempts.push(a);return{attempt:a,created:true};});
 getMedia.mockImplementation(async(_p,_e,a)=>receipt(a));readMedia.mockImplementation(async()=>[...mediaAttempts]);clearMedia.mockImplementation(async a=>{mediaAttempts=mediaAttempts.filter(v=>v.mediaId!==a.mediaId);return true;});
 transfer.mockImplementation(a=>({done:Promise.resolve({receipt:receipt(a)} as any),cancel:jest.fn()}));
 legacySource.mockRejectedValue(Error('Source metadata unavailable'));jest.mocked(assertLegacyEventMediaSource).mockResolvedValue(undefined);legacyClear.mockResolvedValue(undefined);
});
it('persists one source and saved destination before any media or event write',async()=>{const r=await prepare();expect(r.created).toBe(true);expect((await readPageEventReuse(pb,eb,scope))?.source).toEqual(source);expect(prepareMedia).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();});
it('concurrent preparations keep the first source and original identity',async()=>{const [a,b]=await Promise.all([prepare(),preparePageEventReuse(pb,eb,{kind:'template',pageId:pa,eventId:ea,templateId:id(90)},scope)]);expect(a.created).toBe(true);expect(b.created).toBe(false);expect(a.attempt).toEqual(b.attempt);expect(getTemplate).not.toHaveBeenCalled();});
it('lost local preparation response recovers the same original intent',async()=>{mockSet.mockImplementationOnce(async(k,v)=>{mockStorage.set(k,v);throw Error('Lost disk response');});await expect(prepare()).rejects.toThrow('Lost');expect((await prepare()).created).toBe(false);expect(save).not.toHaveBeenCalled();});
it.each(['Live','description','image','body','date','venue'])('preserves existing destination content/status: %s',async kind=>{if(kind==='Live')target.status='Live';if(kind==='description')target.fields.description='Keep';if(kind==='image')target.fields.image_url='https://example.invalid/image';if(kind==='body')target.fields.description_blocks=[{type:'text',content:'Keep'}];if(kind==='date')target.fields.event_date='2027-01-01';if(kind==='venue')target.fields.venue='Keep';await expect(prepare()).rejects.toThrow('new saved draft');expect(mockSet).not.toHaveBeenCalled();});
it('unconfirmed legacy source metadata prevents persisting a new copy intent',async()=>{original.fields.description_blocks=[{type:'image',path:ea+'/old.jpg'}];await expect(prepare()).rejects.toThrow('metadata');expect(mockSet).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();});
it('mixed legacy/private content records original import association before one complete save and terminal cleanup',async()=>{
 original.fields.description_blocks=[{type:'text',content:'Retained story'},{type:'image',path:ea+'/old.jpg',alt:'Old photo'}];
 const descriptor:any={source,reference:ea+'/old.jpg',purpose:'image',objectId:id(201),objectVersion:id(202),lastModified:version,byteSize:100,mimeType:'image/jpeg',etag:'"'+'a'.repeat(32)+'"'};
 legacySource.mockResolvedValue(descriptor);
 legacyImport.mockImplementation(input=>({cancel:jest.fn(),done:(async()=>{await input.onDownloadPrepared({runId:id(203)});const a:any={version:1,userId:user,pageId:pb,eventId:eb,mediaId:id(204),purpose:'image',byteSize:100,mimeType:'image/jpeg',contentDigest:'b'.repeat(64),fileMd5:'a'.repeat(32),fileUri:'file:///original.jpg'};await input.onOriginalPrepared(a);return{source:descriptor,original:a,receipt:{...a,objectName:eb+'/private-'+a.mediaId+'.jpg',readyAt:version,objectPresent:true,attached:false,abandonedAt:null}};})()}));
 await prepare();await expect(run()).resolves.toMatchObject({state:'saved',cleanupPending:false});expect(save.mock.calls[0][3].fields.description_blocks).toEqual([{type:'text',content:'Retained story'},{type:'image',path:eb+'/private-'+id(204)+'.jpg',alt:'Old photo'}]);expect(legacyClear).toHaveBeenCalledWith(pb,eb,descriptor,expect.objectContaining({mediaId:id(204)}),[{runId:id(203)}],expect.anything());expect(save).toHaveBeenCalledTimes(1);
});
it('one complete save preserves story/order/poster/confirmation, clears dates, and keeps destination identity and financial settings',async()=>{await prepare();await expect(run()).resolves.toMatchObject({state:'saved',cleanupPending:false});const input=save.mock.calls[0][3];expect(input.fields.description_blocks).toHaveLength(5);expect(input.fields.description_blocks?.[2]).toEqual({type:'text',content:'Between media'});expect(input.fields.confirmation_message).toBe('Arrival details');expect(input.fields.event_date).toBe('');expect(input.fields.start_time).toBeNull();expect(input.fields.end_time).toBeNull();expect(input.fields.public_name).toBe('Destination page');expect(input.fields.ticket_price).toBe('');expect(input.offerType).toBe('ticketed_event');expect(input.ticketCapacity).toBe(20);expect(input.latitude).toBe(34);expect(input.longitude).toBe(-118);expect(save).toHaveBeenCalledTimes(1);expect(clearMedia).toHaveBeenCalledTimes(4);expect(await readPageEventReuse(pb,eb,scope)).toBeNull();});
it('templates preserve the saved content snapshot without borrowing changed source coordinates',async()=>{await preparePageEventReuse(pb,eb,{kind:'template',pageId:pa,eventId:ea,templateId:id(90)},scope);await run();expect(save.mock.calls[0][3]).toMatchObject({latitude:null,longitude:null});expect(getTemplate).toHaveBeenCalled();});
it('ready original media receipts reuse the existing copies without retransferring bytes',async()=>{await prepare();await run();expect(prepareMedia).toHaveBeenCalledTimes(4);expect(transfer).not.toHaveBeenCalled();});
it('unconfirmed media uses the existing transfer coordinator before saving',async()=>{await prepare();getMedia.mockResolvedValue(null);await run();expect(transfer).toHaveBeenCalledTimes(4);expect(save).toHaveBeenCalledTimes(1);});
it('partial media failure cannot issue a truncated event save',async()=>{await prepare();getMedia.mockResolvedValue(null);transfer.mockImplementationOnce(a=>({done:Promise.resolve({receipt:receipt(a)} as any),cancel:jest.fn()})).mockImplementationOnce(()=>({done:Promise.reject(Error('Offline copy')),cancel:jest.fn()}));await expect(run()).rejects.toThrow('Offline');expect(save).not.toHaveBeenCalled();expect((await readPageEventReuse(pb,eb,scope))?.requestId).toBe(request);});
it('check only reads a pending save and leaves every original attempt intact',async()=>{await prepare();await expect(run('check')).resolves.toMatchObject({state:'pending'});expect(prepareMedia).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();});
it('pending check reauthorizes the source instead of exposing a cached private snapshot after revocation',async()=>{await prepare();state.mockRejectedValue({code:'42501'});await expect(run('check')).rejects.toMatchObject({code:'42501'});expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();});
it.each(['source','destination'])('a changed %s stops before copying and preserves the saved intent',async kind=>{await prepare();(kind==='source'?original:target).updatedAt='2026-09-16T00:00:00Z';await expect(run()).rejects.toThrow('changed');expect(prepareMedia).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();expect(await readPageEventReuse(pb,eb,scope)).not.toBeNull();});
it('a lost durable complete-payload response cannot dispatch an uncertain save',async()=>{await prepare();mockSet.mockImplementationOnce(async(k,v)=>{mockStorage.set(k,v);throw Error('Lost payload acknowledgement');});await expect(run()).rejects.toThrow('Lost');expect(save).not.toHaveBeenCalled();expect((await readPageEventReuse(pb,eb,scope))?.input?.fields.description_blocks).toHaveLength(5);await expect(run()).resolves.toMatchObject({state:'saved'});expect(save).toHaveBeenCalledTimes(1);});
it('lost committed complete-save response recovers read-only, even after source access is revoked',async()=>{await prepare();save.mockImplementationOnce(async(_p,_e,requestId,input)=>{remote={...target,fields:input.fields,latitude:input.latitude,longitude:input.longitude,requestId,userId:user};throw Error('Lost save response');});await expect(run()).rejects.toThrow('Lost');state.mockRejectedValue({code:'42501'});await expect(run('check')).resolves.toMatchObject({state:'saved'});expect(save).toHaveBeenCalledTimes(1);expect(await readPageEventReuse(pb,eb,scope)).toBeNull();});
it('a confirmed save stays final while partial local media cleanup can be retried',async()=>{await prepare();clearMedia.mockRejectedValueOnce(Error('Busy original'));await expect(run()).resolves.toMatchObject({state:'saved',cleanupPending:true});expect(await readPageEventReuse(pb,eb,scope)).not.toBeNull();await expect(run('check')).resolves.toMatchObject({state:'saved',cleanupPending:false});expect(save).toHaveBeenCalledTimes(1);});
it('cancel stops remaining media and leaves the destination unchanged',async()=>{await prepare();let task:ReturnType<typeof startPageEventReuse>;task=startPageEventReuse(pb,eb,request,scope,'retry',p=>{if(p.completed===1)task.cancel();});await expect(task.done).rejects.toThrow();expect(prepareMedia).toHaveBeenCalledTimes(1);expect(save).not.toHaveBeenCalled();expect(await readPageEventReuse(pb,eb,scope)).not.toBeNull();});
it('overlapping work is rejected while the original attempt owns the destination',async()=>{await prepare();const task=startPageEventReuse(pb,eb,request,scope,'check');expect(()=>startPageEventReuse(pb,eb,request,scope,'retry')).toThrow('progress');await task.done;expect(save).not.toHaveBeenCalled();});
it('foreign account and retired page cannot dispatch this attempt',async()=>{await prepare();expect(await readPageEventReuse(pb,eb,{...scope,userId:id(90)})).toBeNull();active=false;expect(()=>startPageEventReuse(pb,eb,request,scope,'retry')).toThrow();expect(save).not.toHaveBeenCalled();});

it('entry source version must still match before a whole-copy journal is created',async()=>{
 await expect(preparePageEventReuse(pb,eb,source,scope,'2026-09-15T01:00:00Z')).rejects.toThrow('selected source changed');
 expect(mockStorage.size).toBe(0);expect(prepareMedia).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();
});
it('a matching entry source version preserves the complete original plan',async()=>{
 const prepared=await preparePageEventReuse(pb,eb,source,scope,version);expect(prepared.created).toBe(true);expect(prepared.attempt.sourceUpdatedAt).toBe(version);expect(prepared.attempt.plan.fields.description_blocks).toEqual(original.fields.description_blocks);
});

it.each(['source','destination'] as const)('Check identifies changed %s without another transfer or save',async reason=>{await prepare();(reason==='source'?original:target).updatedAt='2026-09-15T00:00:00.000001Z';await expect(run('check')).resolves.toMatchObject({state:'conflict',reason});expect(getSave).toHaveBeenCalledTimes(2);expect(prepareMedia).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();});
it('Check recognizes changed source content even if the version is unchanged',async()=>{await prepare();original.fields.description='New story';await expect(run('check')).resolves.toMatchObject({state:'conflict',reason:'source'});expect(save).not.toHaveBeenCalled();});
it('a completed original discovered after the destination read wins over a conflict',async()=>{await prepare();const writer=save.getMockImplementation()!;save.mockImplementationOnce(async(...args)=>{await writer(...args);throw Error('Lost response');});await expect(run()).rejects.toThrow('Lost');target.updatedAt='2026-09-15T00:00:00.000001Z';getSave.mockResolvedValueOnce(null);await expect(run('check')).resolves.toMatchObject({state:'saved'});expect(save).toHaveBeenCalledTimes(1);expect(await readPageEventReuse(pb,eb,scope)).toBeNull();});
it('an unknown second receipt check retains the complete intent',async()=>{await prepare();target.updatedAt='2026-09-15T00:00:00.000001Z';getSave.mockResolvedValueOnce(null).mockRejectedValueOnce(Error('Offline'));await expect(run('check')).rejects.toThrow('Offline');expect(mockRemove).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();});
it('equivalent source/destination timestamp encodings do not create a false conflict',async()=>{await prepare();original.updatedAt='2026-09-14T17:00:00.000000-07:00';target.updatedAt='2026-09-15T00:00:00.000000+00:00';await expect(run('check')).resolves.toMatchObject({state:'pending'});});
it('one microsecond of source change blocks initial preparation',async()=>{await expect(preparePageEventReuse(pb,eb,source,scope,'2026-09-15T00:00:00.000001Z')).rejects.toThrow('changed');expect(mockStorage.size).toBe(0);});

it('Keep stops ordinary copy retries and retains the whole pointer until parent acknowledgement',async()=>{await prepare();await expect(run('keep')).resolves.toMatchObject({state:'kept',cleanupPending:false});expect(save).not.toHaveBeenCalled();expect(prepareMedia).not.toHaveBeenCalled();expect((await readPageEventReuse(pb,eb,scope))?.keeping).toBe(true);jest.mocked(readPageEventCopyStop).mockResolvedValue({copyRequestId:request} as any);await expect(run('retry')).resolves.toMatchObject({state:'kept'});expect(resolvePageEventCopyStop).toHaveBeenLastCalledWith(expect.anything(),expect.anything(),'check');expect(await acknowledgeKeptPageEventReuse(pb,eb,request,scope)).toBe(true);expect(await readPageEventReuse(pb,eb,scope)).toBeNull();});
it('lost keep-intent persistence cannot dispatch the recovery save or copy',async()=>{await prepare();mockSet.mockImplementationOnce(async(k,v)=>{mockStorage.set(k,v);throw Error('Lost keep ack');});await expect(run('keep')).rejects.toThrow('Lost');expect(preparePageEventCopyStop).not.toHaveBeenCalled();await expect(run('retry')).resolves.toMatchObject({state:'stopping'});expect(save).not.toHaveBeenCalled();expect(prepareMedia).not.toHaveBeenCalled();});
it('unknown recovery keeps the stop marker and never replays ordinary copy work',async()=>{await prepare();jest.mocked(resolvePageEventCopyStop).mockRejectedValueOnce(Error('Lost recovery'));await expect(run('keep')).rejects.toThrow('Lost');expect((await readPageEventReuse(pb,eb,scope))?.keeping).toBe(true);expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();});
it('optional stopped-media cleanup failure keeps the confirmed destination and all whole metadata',async()=>{await prepare();jest.mocked(cleanupStoppedPageEventCopy).mockRejectedValueOnce(Error('Source permission lost'));await expect(run('keep')).resolves.toMatchObject({state:'kept',cleanupPending:true});expect(await readPageEventReuse(pb,eb,scope)).not.toBeNull();expect(save).not.toHaveBeenCalled();});
it('a concurrent keep cannot overlap an active copy',async()=>{await prepare();const task=startPageEventReuse(pb,eb,request,scope,'check');expect(()=>startPageEventReuse(pb,eb,request,scope,'keep')).toThrow('progress');await task.done;});


it('a stalled saved-receipt read releases the whole-copy queue and ignores the retired response',async()=>{
 jest.useFakeTimers();try{
  await prepare();let finish!:(value:any)=>void;getSave.mockReturnValueOnce(new Promise(r=>{finish=r;}));
  let failure:any;const pending=run('check').catch(e=>{failure=e;});await jest.advanceTimersByTimeAsync(12_001);
  expect(failure).toBeInstanceOf(Error);await expect(run('check')).resolves.toMatchObject({state:'pending'});
  finish(null);await pending;expect(save).not.toHaveBeenCalled();expect(mockRemove).not.toHaveBeenCalled();
 }finally{jest.useRealTimers();}
});

it('cancelling an import cannot release the copy journal while its original metadata write is settling',async()=>{
 original.fields.description_blocks=[{type:'image',path:ea+'/old.jpg',alt:'Old photo'}];
 const descriptor:any={source,reference:ea+'/old.jpg',purpose:'image',objectId:id(201),objectVersion:id(202),lastModified:version,byteSize:100,mimeType:'image/jpeg',etag:'"'+'a'.repeat(32)+'"'};
 legacySource.mockResolvedValue(descriptor);await prepare();
 let settle!:(value?:unknown)=>void;mockSet.mockImplementationOnce((k,v)=>new Promise(resolve=>{settle=()=>{mockStorage.set(k,v);resolve(undefined);};}));
 const cancel=jest.fn();legacyImport.mockImplementationOnce(input=>({cancel,done:(async()=>{
  await input.onDownloadPrepared({runId:id(203)});throw Error('Paused import');
 })()}));
 const task=startPageEventReuse(pb,eb,request,scope,'retry'),pending=task.done.catch(e=>e);
 while(!settle)await Promise.resolve();task.cancel();await Promise.resolve();await Promise.resolve();
 expect(cancel).toHaveBeenCalled();expect(()=>startPageEventReuse(pb,eb,request,scope,'check')).toThrow('progress');
 settle();await pending;expect((await readPageEventReuse(pb,eb,scope))?.legacyImports?.[0].downloads).toEqual([{runId:id(203)}]);expect(save).not.toHaveBeenCalled();
});
