const mockSession=jest.fn(),mockRpc=jest.fn(),mockFrom=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(...a:any[])=>mockRpc(...a),from:(...a:any[])=>mockFrom(...a)}}));
import {saveCreatorPromo,saveCreatorFaq} from '../creatorTicketDetailsSave';
import type {PromoDraft} from '../ticketPromosAddons';
const draft:PromoDraft={code:'EARLYBIRD',discount_type:'percent',discount_value:25,max_uses:null,starts_at:null,ends_at:null,unlocks_hidden:false,active:true};
const row=()=>({id:'code',event_id:'event',...draft});
let current=true,results:any[],requests:any[];const scope={userId:'creator',isCurrent:()=>current};
function chain(){const r:any={method:'read',filters:[],headers:[]};requests.push(r);const q:any={};for(const method of ['select','insert','eq','maybeSingle','setHeader'])q[method]=(...a:any[])=>{if(method==='insert'){r.method=method;r.value=a[0];}if(method==='eq')r.filters.push(a);if(method==='setHeader')r.headers.push(a);return q;};q.then=(ok:any,bad:any)=>{const result=results.shift();return (result instanceof Error?Promise.reject(result):Promise.resolve(result)).then(ok,bad);};return q;}
beforeEach(()=>{current=true;results=[];requests=[];jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'creator'},access_token:'token'}}});mockRpc.mockReturnValue({setHeader:()=>Promise.resolve({data:true})});mockFrom.mockImplementation(chain);});
it('confirms a normalized promo receipt and pins every request to the initiating token',async()=>{results=[{data:null},{data:row()}];await saveCreatorPromo('event','code',{...draft,code:' earlybird '},scope);expect(requests[1].value).toEqual(row());for(const r of requests)expect(r.headers).toContainEqual(['Authorization','Bearer token']);});
it('reads an existing exact promo without a new insert',async()=>{results=[{data:row()}];await saveCreatorPromo('event','code',draft,scope);expect(requests).toHaveLength(1);});
it('recovers a committed promo after a lost response',async()=>{results=[{data:null},Error('lost'),{data:row()}];await saveCreatorPromo('event','code',draft,scope);expect(requests.filter(r=>r.method==='insert')).toHaveLength(1);});
it('keeps an unknown result unresolved',async()=>{results=[{data:null},Error('lost'),Error('offline')];await expect(saveCreatorPromo('event','code',draft,scope)).rejects.toThrow();expect(requests.filter(r=>r.method==='insert')).toHaveLength(1);});
it('does not overwrite a different saved code',async()=>{results=[{data:{...row(),discount_value:30}}];await expect(saveCreatorPromo('event','code',draft,scope)).rejects.toThrow('earlier version');expect(requests).toHaveLength(1);});
it('recovers an FAQ without duplicating its sort position',async()=>{const faq={id:'faq',event_id:'event',question:'Where?',answer:'By the pier.',sort_order:2,is_active:true};results=[{data:null},Error('lost'),{data:faq}];await saveCreatorFaq('event','faq',' Where? ',' By the pier. ',2,scope);expect(requests[1].value).toEqual(faq);expect(requests.filter(r=>r.method==='insert')).toHaveLength(1);});
it('denies a different signed-in account before querying',async()=>{mockSession.mockResolvedValue({data:{session:{user:{id:'other'},access_token:'other'}}});await expect(saveCreatorPromo('event','code',draft,scope)).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it('denies missing ticket authority before querying',async()=>{mockRpc.mockReturnValue({setHeader:()=>Promise.resolve({data:false})});await expect(saveCreatorFaq('event','faq','Where?','Here',0,scope)).rejects.toThrow('access');expect(mockFrom).not.toHaveBeenCalled();});
