import { createHash } from 'crypto';
const mockPage='774c2329-e22e-4113-8a2a-67ca854dd2c9',mockUser='42c626b4-75e3-40f1-af31-7cd04cd5f809',mockId='0c400000-0000-4000-8000-000000000001',mockMember='0c400000-0000-4000-8000-000000000002';
let mockLive=true,mockAccount=mockUser,mockStore:Record<string,string>={},mockReceipt:any=null,mockRows:Record<string,any>={};
const mockStorage={getItem:jest.fn(async(k:string)=>mockStore[k]??null),setItem:jest.fn(async(k:string,v:string)=>{mockStore[k]=v;}),removeItem:jest.fn(async(k:string)=>{delete mockStore[k];})};
const mockAuth=jest.fn(async()=>({data:{user:{id:mockAccount}},error:null}));
const mockRpc=jest.fn(async(name:string,args:any)=>{
 if(name==='get_creator_community_join_request')return {data:mockReceipt,error:null};
 if(name==='request_creator_community_join')mockReceipt={id:args.p_request_id,page_id:args.p_page_id,user_id:mockUser,settings_version:args.p_settings_version,member_id:mockMember,outcome:'submitted',current_status:'active',created_at:'2026-09-15T07:00:00Z'};
 if(name==='cancel_creator_community_join_request')mockReceipt=mockReceipt??{id:args.p_request_id,page_id:args.p_page_id,user_id:mockUser,settings_version:null,member_id:null,outcome:'cancelled',current_status:null,created_at:'2026-09-15T07:00:00Z'};
 return {data:mockReceipt,error:null};
});
const mockFrom=jest.fn((table:string)=>{const q:any={select:jest.fn(()=>q),eq:jest.fn(()=>q),maybeSingle:jest.fn(async()=>mockRows[table]??{data:null,error:null})};return q;});
jest.mock('../supabase',()=>({supabase:{auth:{getUser:(...a:any[])=>mockAuth(...a as [])},from:(t:string)=>mockFrom(t),rpc:(n:string,a:any)=>mockRpc(n,a)}}));
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:(k:string)=>mockStorage.getItem(k),setItem:(k:string,v:string)=>mockStorage.setItem(k,v),removeItem:(k:string)=>mockStorage.removeItem(k)}}));
jest.mock('expo-crypto',()=>({randomUUID:()=>mockId,CryptoDigestAlgorithm:{SHA256:'SHA256'},digestStringAsync:async(_a:string,s:string)=>require('crypto').createHash('sha256').update(s).digest('hex')}));
import * as service from '../creatorCommunityJoin';
const gate:service.CreatorCommunityJoinGate={communityId:mockPage,name:'Sunday Table',welcomeMessage:null,introQuestion:'Introduce yourself',guidelinesUrl:null,askReason:true,askSource:false,askRulesConfirm:false,openQuestion:null,creatorPageVersion:2,creatorPagePolicy:'open'};
const answers={first_name:'Juniper',last_name:'Synthetic',email:'private@example.invalid',zip:'90026',intro_answer:'I like drawing',guidelines_accepted:true,reason_answer:'Private reason'};
const scope=()=>({userId:mockUser,isCurrent:()=>mockLive});
beforeEach(()=>{jest.clearAllMocks();mockLive=true;mockAccount=mockUser;mockStore={};mockReceipt=null;mockStorage.getItem.mockImplementation(async k=>mockStore[k]??null);mockStorage.setItem.mockImplementation(async(k,v)=>{mockStore[k]=v;});mockRows={creator_page_publications:{data:{page_id:mockPage,page_kind:'community'},error:null},communities:{data:{id:mockPage,name:'Sunday Table',join_welcome_message:null,join_intro_question:'Introduce yourself',guidelines_url:null,join_policy:'open',join_ask_reason:true,join_ask_source:false,join_ask_rules_confirm:false,join_open_question:null,creator_page_join_settings_version:2},error:null}};});
it('reads all displayed questions and the revision together for this published page',async()=>{expect(await service.readCreatorCommunityJoinGate(mockPage,scope())).toEqual(gate);expect(mockFrom.mock.results[1].value.select.mock.calls[0][0]).toContain('creator_page_join_settings_version');});
it('does not turn unavailable or malformed required-question configuration into disabled fields',async()=>{mockRows.communities.error=Error('Unavailable');await expect(service.readCreatorCommunityJoinGate(mockPage,scope())).rejects.toThrow();mockRows.communities.error=null;delete mockRows.communities.data.join_ask_reason;await expect(service.readCreatorCommunityJoinGate(mockPage,scope())).rejects.toThrow('unavailable');});
it('distinguishes no authorized publication from a failed publication read',async()=>{mockRows.creator_page_publications={data:null,error:null};expect(await service.readCreatorCommunityJoinGate(mockPage,scope())).toBeNull();mockRows.creator_page_publications.error=Error('Read failed');await expect(service.readCreatorCommunityJoinGate(mockPage,scope())).rejects.toThrow('Read failed');});
it('checks identity before and after reading page questions',async()=>{mockAuth.mockImplementationOnce(async()=>({data:{user:{id:mockUser}},error:null})).mockImplementationOnce(async()=>({data:{user:{id:'another'}},error:null}));await expect(service.readCreatorCommunityJoinGate(mockPage,scope())).rejects.toThrow();expect(mockFrom).toHaveBeenCalledTimes(1);});
it('validates enabled answers before retaining an attempt or sending',async()=>{await expect(service.sendCommunityJoinRequest(gate,{...answers,reason_answer:''},scope())).rejects.toThrow('why');expect(mockRpc).not.toHaveBeenCalled();expect(mockStorage.setItem).not.toHaveBeenCalled();});
it('persists metadata before dispatch without storing names, contact or answers',async()=>{const result=await service.sendCommunityJoinRequest(gate,answers,scope());expect(result.current_status).toBe('active');expect(mockStorage.setItem.mock.invocationCallOrder[0]).toBeLessThan(mockRpc.mock.invocationCallOrder[0]);const raw=Object.values(mockStore)[0];for(const value of Object.values(answers).filter(v=>typeof v==='string'))expect(raw).not.toContain(value);expect(JSON.parse(raw)).toEqual({id:mockId,pageId:mockPage,userId:mockUser,version:2,answerHash:createHash('sha256').update(JSON.stringify(answers)).digest('hex')});});
it('does not dispatch if the private metadata cannot be persisted',async()=>{mockStorage.setItem.mockRejectedValueOnce(Error('Storage full'));await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow('Storage full');expect(mockRpc).not.toHaveBeenCalled();});
it('keeps a lost result pending and checks the exact receipt without resending',async()=>{const real=mockRpc.getMockImplementation()!;mockRpc.mockImplementationOnce(async(n,a)=>{await real(n,a);throw Error('Lost response');});await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow('Lost response');expect(await service.readCommunityJoinAttempt(mockPage,scope())).not.toBeNull();expect((await service.checkCommunityJoinRequest(mockPage,scope()))?.id).toBe(mockId);expect(mockRpc.mock.calls.filter(([n])=>n==='request_creator_community_join')).toHaveLength(1);});
it('retries the same retained ID, version and normalized answers',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());await service.sendCommunityJoinRequest(gate,{...answers,first_name:' Juniper '},scope());const requests=mockRpc.mock.calls.filter(([n])=>n==='request_creator_community_join');expect(requests[1][1]).toEqual(requests[0][1]);});
it('refuses changed answers or question versions while the original attempt remains',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());await expect(service.sendCommunityJoinRequest(gate,{...answers,intro_answer:'Different'},scope())).rejects.toThrow('earlier request');await expect(service.sendCommunityJoinRequest({...gate,creatorPageVersion:3},answers,scope())).rejects.toThrow('earlier request');expect(mockRpc).toHaveBeenCalledTimes(1);});
it('missing receipt stays unknown and cannot clear the local attempt',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());mockReceipt=null;expect(await service.checkCommunityJoinRequest(mockPage,scope())).toBeNull();await expect(service.finishCommunityJoinRequest(mockPage,scope())).rejects.toThrow('still unconfirmed');expect(mockStorage.removeItem).not.toHaveBeenCalled();});
it('cancellation returns an existing committed outcome without clearing or leaving membership',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());expect((await service.cancelCommunityJoinRequest(mockPage,scope())).current_status).toBe('active');expect(mockStorage.removeItem).not.toHaveBeenCalled();expect(mockRpc.mock.calls.some(([n])=>n==='leave_community')).toBe(false);});
it('confirmed cancellation is recoverable, then explicit finish removes metadata',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());mockReceipt=null;expect((await service.cancelCommunityJoinRequest(mockPage,scope())).outcome).toBe('cancelled');expect((await service.finishCommunityJoinRequest(mockPage,scope()))?.outcome).toBe('cancelled');expect(await service.readCommunityJoinAttempt(mockPage,scope())).toBeNull();});
it('a receipt for another account or attempt cannot establish success',async()=>{await service.sendCommunityJoinRequest(gate,answers,scope());mockReceipt.user_id='another';await expect(service.checkCommunityJoinRequest(mockPage,scope())).rejects.toThrow('could not be confirmed');expect(mockStorage.removeItem).not.toHaveBeenCalled();});
it('account change after dispatch retains the original account recovery marker',async()=>{const real=mockRpc.getMockImplementation()!;mockRpc.mockImplementationOnce(async(n,a)=>{const r=await real(n,a);mockAccount='another';return r;});await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow();expect(Object.keys(mockStore)[0]).toContain(mockUser);expect(mockStorage.removeItem).not.toHaveBeenCalled();});
it('account or visit retirement before dispatch prevents mutation',async()=>{mockStorage.setItem.mockImplementationOnce(async(k,v)=>{mockStore[k]=v;mockLive=false;});await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow();expect(mockRpc).not.toHaveBeenCalled();});
it('corrupt or cross-page metadata never becomes an editable fresh attempt',async()=>{mockStore[`creator-community-join:v1:${mockUser}:${mockPage}`]='{"id":"bad"}';await expect(service.readCommunityJoinAttempt(mockPage,scope())).rejects.toThrow('could not be read');await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow('could not be read');expect(mockRpc).not.toHaveBeenCalled();});
it('membership read failures remain distinct from no membership and validate account identity',async()=>{expect(await service.readOwnCommunityMembership(mockPage,scope())).toBeNull();mockRows.community_members={data:null,error:Error('Failed read')};await expect(service.readOwnCommunityMembership(mockPage,scope())).rejects.toThrow('Failed read');mockRows.community_members={data:{id:mockMember,community_id:mockPage,user_id:'other',status:'active',role:'member'},error:null};await expect(service.readOwnCommunityMembership(mockPage,scope())).rejects.toThrow('could not be checked');});

// Exercise the unchanged real service mutex/storage with the UI deadline adapter.
import { waitForCommunityJoin } from '../communityJoinWait';
import { RequestDeadlineError } from '../requestWithDeadline';
function deferred<T=any>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>{resolve=yes});return{promise,resolve};}
async function flush(){for(let i=0;i<30;i++)await Promise.resolve();}
afterEach(()=>jest.useRealTimers());
it('a timed-out metadata write keeps its mutex and exact identity until real storage settles',async()=>{
 jest.useFakeTimers();const storage=deferred<void>();let originalKey='',originalRaw='';
 mockStorage.setItem.mockImplementationOnce(async(k,v)=>{originalKey=k;originalRaw=v;await storage.promise;mockStore[k]=v;});
 const waiting=waitForCommunityJoin(scope(),owned=>service.sendCommunityJoinRequest(gate,answers,owned));const timeout=expect(waiting).rejects.toBeInstanceOf(RequestDeadlineError);
 await flush();expect(mockStorage.setItem).toHaveBeenCalledTimes(1);expect(mockRpc).not.toHaveBeenCalled();jest.advanceTimersByTime(12_001);await timeout;
 await expect(service.sendCommunityJoinRequest(gate,answers,scope())).rejects.toThrow('still being checked');expect(mockStorage.setItem).toHaveBeenCalledTimes(1);
 storage.resolve();await flush();expect(mockStore[originalKey]).toBe(originalRaw);expect(mockRpc).not.toHaveBeenCalled();
 expect((await service.readCommunityJoinAttempt(mockPage,scope()))?.id).toBe(mockId);
 await service.sendCommunityJoinRequest(gate,answers,scope());expect(mockStorage.setItem).toHaveBeenCalledTimes(1);expect(mockRpc).toHaveBeenCalledTimes(1);expect(mockRpc.mock.calls[0][1].p_request_id).toBe(mockId);
});
it('a timed-out receipt check keeps the service locked until its real auth read retires',async()=>{
 await service.sendCommunityJoinRequest(gate,answers,scope());mockRpc.mockClear();jest.useFakeTimers();const auth=deferred<any>();mockAuth.mockReturnValueOnce(auth.promise);
 const checking=waitForCommunityJoin(scope(),owned=>service.checkCommunityJoinRequest(mockPage,owned));const timeout=expect(checking).rejects.toBeInstanceOf(RequestDeadlineError);
 await flush();jest.advanceTimersByTime(12_001);await timeout;await expect(service.checkCommunityJoinRequest(mockPage,scope())).rejects.toThrow('still being checked');
 auth.resolve({data:{user:{id:mockUser}},error:null});await flush();expect(mockRpc).not.toHaveBeenCalled();expect((await service.checkCommunityJoinRequest(mockPage,scope()))?.id).toBe(mockId);
 expect(mockRpc.mock.calls.map(([name])=>name)).toEqual(['get_creator_community_join_request']);
});
it('a timed-out dispatched request retains metadata and requires read-only receipt recovery',async()=>{
 jest.useFakeTimers();const dispatched=deferred<any>();const real=mockRpc.getMockImplementation()!;
 mockRpc.mockImplementationOnce(async(name,args)=>{const result=await real(name,args);await dispatched.promise;return result});
 const sending=waitForCommunityJoin(scope(),owned=>service.sendCommunityJoinRequest(gate,answers,owned));const timeout=expect(sending).rejects.toBeInstanceOf(RequestDeadlineError);
 await flush();expect(mockRpc).toHaveBeenCalledTimes(1);jest.advanceTimersByTime(12_001);await timeout;
 await expect(service.cancelCommunityJoinRequest(mockPage,scope())).rejects.toThrow('still being checked');
 dispatched.resolve(null);await flush();expect((await service.checkCommunityJoinRequest(mockPage,scope()))?.current_status).toBe('active');
 expect(mockRpc.mock.calls.filter(([name])=>name==='request_creator_community_join')).toHaveLength(1);expect(mockStorage.removeItem).not.toHaveBeenCalled();
});
