const mockRpc=jest.fn();
jest.mock('../supabase',()=>({supabase:{rpc:(...a:unknown[])=>mockRpc(...a)}}));
jest.mock('../creatorTicketRead',()=>({scopedTicketRequest:async(_scope:unknown,make:()=>unknown)=>make()}));
import {reminderDeliveryCopy,readReminderSettings,saveEventReminders,loadEventReminders,ReminderAccessDenied,ReminderConflict} from '../eventReminders';
const event='8ecc2940-0000-4000-8000-000000000001',page='8ecc2940-0000-4000-8000-000000000002',revision='8ecc2940-0000-4000-8000-000000000003';
const settings={eventId:event,pageId:page,revision:null,updatedAt:null,startsAt:'2099-09-18T18:00:00Z',eventStatus:'Live',deliveryReady:false,dayBeforeOn:true,dayOfOn:true};
const scope={userId:'creator',isCurrent:()=>true};
beforeEach(()=>mockRpc.mockReset());
it('rejects missing versions, false confirmations and wrong event identities',()=>{for(const change of [{revision:undefined},{revision,updatedAt:null},{startsAt:'garbage'},{dayOfOn:'false'},{eventId:page},{deliveryReady:undefined}])expect(readReminderSettings({...settings,...change},event)).toBeNull();});
it('does not claim a successful save from a malformed or mismatched receipt',async()=>{for(const change of [{},{revision,updatedAt:'2026-09-17T04:00:00Z',dayBeforeOn:false},{revision,updatedAt:'2026-09-17T04:00:00Z',pageId:event}]){mockRpc.mockResolvedValueOnce({data:{...settings,...change},error:null});await expect(saveEventReminders(event,settings,settings,scope)).rejects.toThrow('could not be confirmed');}});
it('distinguishes access loss and stale edits from uncertain network results',async()=>{mockRpc.mockResolvedValueOnce({data:null,error:{code:'42501'}});await expect(loadEventReminders(event,scope)).rejects.toBeInstanceOf(ReminderAccessDenied);mockRpc.mockResolvedValueOnce({data:null,error:{code:'P0001',message:'Reminder settings changed. Review the saved settings first.'}});await expect(saveEventReminders(event,settings,settings,scope)).rejects.toBeInstanceOf(ReminderConflict);mockRpc.mockResolvedValueOnce({data:null,error:{code:'offline'}});await expect(saveEventReminders(event,settings,settings,scope)).rejects.toThrow('could not be confirmed');});

it('accepts only bounded aggregate delivery status and discards private fields',()=>{const row={timing:'day_before',queuedCount:12,stoppedCount:2,lastQueuedAt:'2026-09-17T05:00:00Z'};expect(readReminderSettings({...settings,deliverySummary:[{...row,userId:'private'}]},event)?.deliverySummary).toEqual([row]);for(const summary of [null,[row,row],[{...row,stoppedCount:13}],[{...row,queuedCount:'12'}],[{...row,lastQueuedAt:'bad'}],[{...row,timing:'promotional'}]])expect(readReminderSettings({...settings,deliverySummary:summary},event)).toBeNull();});
it('status distinguishes paused, unpublished, disabled and ended without promising delivery',()=>{expect(reminderDeliveryCopy(settings)).toContain('paused');expect(reminderDeliveryCopy({...settings,deliveryReady:true,eventStatus:'Draft'})).toContain('Publish');expect(reminderDeliveryCopy({...settings,deliveryReady:true,dayBeforeOn:false,dayOfOn:false})).toContain('Both reminders are off');expect(reminderDeliveryCopy({...settings,eventStatus:'Cancelled'})).toContain('No new reminders');expect(reminderDeliveryCopy({...settings,startsAt:'2000-01-01T00:00:00Z'})).toContain('No new reminders');});
