const mockSession=jest.fn(),mockRpc=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(...a:any[])=>mockRpc(...a)}}));
import { reviewEventInvitation,submitEventInvitation,readEventInvitationStatus,readInvitationReview,InvitationRejected,type InvitationReview } from '../eventInvitationSend';
const event='8ecc2920-0000-4000-8000-000000000001',page='8ecc2920-0000-4000-8000-000000000002',request='8ecc2920-0000-4000-8000-000000000003';
const message={audience:'followers' as const,body:'A picnic by the sea'};
const review=():InvitationReview=>({context:{eventId:event,pageId:page,eventTitle:'Sunday picnic',eventImage:null,eventStatus:'Live',pageName:'Sunset Social',pageKind:'organization'},message,recipientCount:2,reviewHash:'a'.repeat(64),channel:'in_app_push',providerDeliveryConfirmed:false,sendingEnabled:true});
const receipt=()=>({id:'8ecc2920-0000-4000-8000-000000000004',eventId:event,pageId:page,requestId:request,recipientCount:2,pushQueuedCount:2,deliveryStatus:'queued',createdAt:'2026-09-16T20:00:00Z',providerDeliveryConfirmed:false});
let scope={userId:'creator',isCurrent:()=>true};const headers:any[]=[];
function chain(data:any,error:any=null){const q:any={setHeader:(...a:any[])=>{headers.push(a);return q;},then:(resolve:any)=>Promise.resolve({data,error}).then(resolve)};return q;}
beforeEach(()=>{jest.clearAllMocks();headers.length=0;scope={userId:'creator',isCurrent:()=>true};mockSession.mockResolvedValue({data:{session:{user:{id:'creator'},access_token:'test-token'}}});mockRpc.mockImplementation(()=>chain(review()));});
it('pins reviewed content to the initiating account and preserves disabled delivery',async()=>{mockRpc.mockImplementation(()=>chain({...review(),sendingEnabled:false}));expect((await reviewEventInvitation(event,message,scope)).sendingEnabled).toBe(false);expect(mockRpc).toHaveBeenCalledWith('review_event_invitation',{p_event_id:event,p_message:message});expect(headers).toEqual([['Authorization','Bearer test-token']]);});
it.each([
 ['wrong event',{context:{...review().context,eventId:page}}],['changed text',{message:{...message,body:'Different'}}],['wrong page audience',{context:{...review().context,pageKind:'community'}}],
 ['missing hash',{reviewHash:null}],['unknown count',{recipientCount:null}],['unknown policy',{sendingEnabled:null}],['false delivery claim',{providerDeliveryConfirmed:true}],
])('rejects %s in review',(_label,patch)=>{expect(readInvitationReview({...review(),...patch},event,message)).toBeNull();});
it('sends only the exact saved message/hash/key, never a client recipient list',async()=>{mockRpc.mockImplementation(()=>chain(receipt()));expect(await submitEventInvitation(event,page,request,review(),scope)).toEqual(receipt());expect(mockRpc).toHaveBeenCalledWith('submit_event_invitation',{p_event_id:event,p_request_id:request,p_message:message,p_review_hash:'a'.repeat(64)});});
it('refuses disabled or empty reviewed sends before dispatch',async()=>{await expect(submitEventInvitation(event,page,request,{...review(),sendingEnabled:false},scope)).rejects.toThrow();await expect(submitEventInvitation(event,page,request,{...review(),recipientCount:0},scope)).rejects.toThrow();expect(mockRpc).not.toHaveBeenCalled();});
it('account change cannot dispatch a saved invitation',async()=>{mockSession.mockResolvedValue({data:{session:{user:{id:'other'},access_token:'other'}}});await expect(submitEventInvitation(event,page,request,review(),scope)).rejects.toThrow();expect(mockRpc).not.toHaveBeenCalled();});
it('only explicit post-lookup rejection proves the attempt unrecorded',async()=>{mockRpc.mockImplementation(()=>chain(null,{code:'P0001',message:'Page invitation limit reached'}));await expect(submitEventInvitation(event,page,request,review(),scope)).rejects.toBeInstanceOf(InvitationRejected);});
it.each([{code:'42501',message:'Invitation access denied'},{code:'P0001',message:'Invitation request already belongs to another message'},{code:'504',message:'Gateway timeout'}])('keeps ambiguous error $code unresolved',async error=>{mockRpc.mockImplementation(()=>chain(null,error));await expect(submitEventInvitation(event,page,request,review(),scope)).rejects.not.toBeInstanceOf(InvitationRejected);});
it('checks original receipt read-only and distinguishes absent from malformed',async()=>{mockRpc.mockImplementation(()=>chain(null));expect(await readEventInvitationStatus(event,page,request,scope)).toBeNull();expect(mockRpc).toHaveBeenCalledWith('get_event_invitation_receipt',{p_request_id:request});mockRpc.mockImplementation(()=>chain({...receipt(),pageId:event}));await expect(readEventInvitationStatus(event,page,request,scope)).rejects.toThrow('did not match');mockRpc.mockImplementation(()=>chain(receipt()));expect(await readEventInvitationStatus(event,page,request,scope)).toEqual(receipt());});
it('rejects partial queue or retired visit results',async()=>{mockRpc.mockImplementation(()=>chain({...receipt(),pushQueuedCount:1}));await expect(submitEventInvitation(event,page,request,review(),scope)).rejects.toThrow('could not be confirmed');mockRpc.mockImplementation(()=>{scope.isCurrent=()=>false;return chain(receipt());});await expect(readEventInvitationStatus(event,page,request,scope)).rejects.toThrow();});
