import AsyncStorage from '@react-native-async-storage/async-storage';
const mockUser=jest.fn(),mockRpc=jest.fn(),mockFrom=jest.fn();let mockId=0;
jest.mock('expo-crypto',()=>({randomUUID:()=>`aaaaaaaa-aaaa-4aaa-8aaa-${String(++mockId).padStart(12,'0')}`}));
jest.mock('../supabase',()=>({supabase:{auth:{getUser:()=>mockUser()},rpc:(...a:unknown[])=>mockRpc(...a),from:(...a:unknown[])=>mockFrom(...a)}}));
jest.mock('../publishedPageIdentity',()=>({checkPublishedPageScope:async(scope:any)=>{if(!scope.isCurrent())throw new Error('Retired');}}));
import {prepareOrganizationFollow,sendOrganizationFollowAttempt,readPendingOrganizationFollow,checkOrganizationFollowAttempt,resolveOrganizationFollowAttempt,readOrganizationFollowState,readOrganizationFollowerCount} from '../organizationPageFollow';
const page='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222';
const scope={userId:user,isCurrent:()=>true};
const state=(following=false,version=0)=>({page_id:page,user_id:user,following,version});
const receipt=(a:any)=>({id:a.id,page_id:a.pageId,user_id:a.userId,expected_version:a.expectedVersion,following:a.following,result_version:a.expectedVersion+1});
function q(data:unknown){const result:any={};for(const k of ['select','eq','maybeSingle'])result[k]=()=>result;result.then=(r:any)=>Promise.resolve({data,error:null}).then(r);return result;}
beforeEach(async()=>{jest.clearAllMocks();mockId=0;await AsyncStorage.clear();mockUser.mockResolvedValue({data:{user:{id:user}},error:null});mockRpc.mockImplementation(async name=>({data:name==='get_creator_page_follow_state'?state():0,error:null}));mockFrom.mockImplementation(()=>q(null));});
it('persists one exact intent before any mutation and blocks a competing intent',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);expect(mockRpc).not.toHaveBeenCalled();await expect(prepareOrganizationFollow(state(),false,scope)).rejects.toThrow('saved follow attempt');});
it('does not send if the durable journal failed or the original attempt is missing',async()=>{jest.mocked(AsyncStorage.setItem).mockRejectedValueOnce(new Error('Disk full'));await expect(prepareOrganizationFollow(state(),true,scope)).rejects.toThrow('Disk full');expect(mockRpc).not.toHaveBeenCalled();await expect(sendOrganizationFollowAttempt({id:'aaaaaaaa-aaaa-4aaa-8aaa-000000000001',pageId:page,userId:user,following:true,expectedVersion:0},scope)).rejects.toThrow('saved first');});
it('retains an unknown result without retrying or reporting following as confirmed',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);mockRpc.mockResolvedValueOnce({data:null,error:new Error('Lost response')});await expect(sendOrganizationFollowAttempt(a,scope)).rejects.toThrow('Lost response');expect(mockRpc).toHaveBeenCalledTimes(1);expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);});
it('reconciles a known older receipt with the newer actual state without a mutation',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);mockFrom.mockImplementation(()=>q(receipt(a)));mockRpc.mockResolvedValue({data:state(false,2),error:null});const found=await checkOrganizationFollowAttempt(a,scope);expect(found.receipt?.following).toBe(true);expect(found.state).toEqual(state(false,2));expect(mockRpc.mock.calls.every(c=>c[0]==='get_creator_page_follow_state')).toBe(true);const current=await resolveOrganizationFollowAttempt(a,scope);expect(current.following).toBe(false);expect(await readPendingOrganizationFollow(page,scope)).toBeNull();});
it('does not erase an unresolved same-version attempt',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);await expect(resolveOrganizationFollowAttempt(a,scope)).rejects.toThrow('still uncertain');expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);});
it('allows explicit reconciliation of a rejected stale-version attempt without reapplying its intent',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);mockRpc.mockResolvedValue({data:state(false,2),error:null});expect((await checkOrganizationFollowAttempt(a,scope)).conflict).toBe(true);expect(await resolveOrganizationFollowAttempt(a,scope)).toEqual(state(false,2));expect(mockRpc.mock.calls.every(c=>c[0]==='get_creator_page_follow_state')).toBe(true);});
it('rejects a wrong receipt and preserves recovery',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);mockRpc.mockResolvedValueOnce({data:{...receipt(a),page_id:'another'},error:null});await expect(sendOrganizationFollowAttempt(a,scope)).rejects.toThrow('could not be confirmed');expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);});
it('serializes same-page sends and preserves the attempt until explicit confirmed cleanup',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);let resolve:any;mockRpc.mockImplementationOnce(()=>new Promise(r=>{resolve=r;})).mockResolvedValue({data:state(true,1),error:null});const sending=sendOrganizationFollowAttempt(a,scope);await expect(sendOrganizationFollowAttempt(a,scope)).rejects.toThrow('still finishing');while(!resolve)await Promise.resolve();resolve({data:receipt(a),error:null});expect((await sending).state.following).toBe(true);expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);});
it('rejects a changed current user or retired visit before a mutation can dispatch',async()=>{const a=await prepareOrganizationFollow(state(),true,scope);mockUser.mockResolvedValueOnce({data:{user:{id:'other'}},error:null});await expect(sendOrganizationFollowAttempt(a,scope)).rejects.toThrow();await expect(sendOrganizationFollowAttempt(a,{...scope,isCurrent:()=>false})).rejects.toThrow();expect(mockRpc).not.toHaveBeenCalled();});
it('distinguishes unavailable count from zero and validates the current state identity',async()=>{mockRpc.mockResolvedValueOnce({data:null,error:null});expect(await readOrganizationFollowerCount(page,{userId:null,isCurrent:()=>true})).toBeNull();expect(await readOrganizationFollowerCount(page,scope)).toBe(0);mockRpc.mockResolvedValueOnce({data:{...state(),user_id:'other'},error:null});await expect(readOrganizationFollowState(page,scope)).rejects.toThrow();});
it('retains confirmed following when marker cleanup fails and safely replaces that resolved marker on the next choice',async()=>{
 const a=await prepareOrganizationFollow(state(),true,scope);mockFrom.mockImplementation(()=>q(receipt(a)));mockRpc.mockResolvedValue({data:state(true,1),error:null});
 jest.mocked(AsyncStorage.removeItem).mockRejectedValueOnce(new Error('Cleanup failed'));
 expect(await resolveOrganizationFollowAttempt(a,scope)).toEqual(state(true,1));expect(await readPendingOrganizationFollow(page,scope)).toEqual(a);
 const next=await prepareOrganizationFollow(state(true,1),false,scope);expect(next.id).not.toBe(a.id);expect(next.expectedVersion).toBe(1);expect(next.following).toBe(false);
 expect(await readPendingOrganizationFollow(page,scope)).toEqual(next);expect(mockRpc.mock.calls.every(c=>c[0]==='get_creator_page_follow_state')).toBe(true);
});
