const mockSession=jest.fn(),mockFrom=jest.fn(),mockCovers=jest.fn();
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},from:(...a:unknown[])=>mockFrom(...a)}}));
jest.mock('../publishedPageCover',()=>({getPublishedCoverMediaIds:(...a:unknown[])=>mockCovers(...a)}));
jest.mock('../organizerProfile',()=>({}));jest.mock('../communityLeader',()=>({}));
import {loadPublishedPageIdentity,loadPublishedEventPageIdentities,publishedPageRoute} from '../publishedPageIdentity';
import {loadPublishedOrganizationPage} from '../publishedOrganizationPage';
const owner='11111111-1111-4111-8111-111111111111',page='22222222-2222-4222-8222-222222222222',otherPage='33333333-3333-4333-8333-333333333333';
const event='44444444-4444-4444-8444-444444444444',otherEvent='55555555-5555-4555-8555-555555555555';
const scope={userId:owner,isCurrent:()=>true};
const identity=(id=page)=>({page_id:id,owner_id:owner,page_kind:'organization',name:id===page?'Sunday Table':'Another page',purpose:'Neighbors together',city:'Los Angeles',description:null,photo_url:'legacy-page-image',published_at:'2026-09-14T00:00:00Z'});
const row=(id=event,extra={})=>({id,title:'Saved gathering',status:'Live',community_id:null,event_date:'2026-09-20',start_time:'2026-09-20T17:00:00Z',end_time:null,venue:'Los Angeles',image_url:null,category:'community',ticket_price:0,...extra});
const calls:any[]=[];
function query(table:string,data:unknown,error:unknown=null){const q:any={};for(const key of ['select','in','eq','is','order','range'])q[key]=(...args:unknown[])=>{calls.push({table,key,args});return q;};q.then=(r:any)=>Promise.resolve({data,error}).then(r);return q;}
beforeEach(()=>{jest.clearAllMocks();calls.length=0;mockSession.mockResolvedValue({data:{session:{user:{id:owner}}},error:null});mockCovers.mockResolvedValue(new Map([[page,'cover-id']]));mockFrom.mockImplementation(table=>query(table,table==='creator_page_publications'?[identity()]:table==='creator_page_events'?[{event_id:event,page_id:page}]:[row()]));});
it('resolves published identity by page ID, retains owner separately and suppresses legacy image fallback',async()=>{const result=await loadPublishedPageIdentity(page,scope);expect(result).toMatchObject({pageId:page,ownerId:owner,name:'Sunday Table',coverMediaId:'cover-id',photoUrl:null});expect(mockFrom.mock.calls.map(a=>a[0])).toEqual(['creator_page_publications']);expect(publishedPageRoute(result!)).toBe(`/organization/${page}?identity=page`);});
it('does not substitute the account profile when a page is private, inaccessible or absent',async()=>{mockFrom.mockImplementation(table=>query(table,[]));expect(await loadPublishedOrganizationPage(page,scope)).toBeNull();expect(mockFrom.mock.calls.map(a=>a[0])).toEqual(['creator_page_publications']);});
it('surfaces a failed publication read rather than treating it as a legacy identity',async()=>{mockFrom.mockImplementation(table=>query(table,null,new Error('Read failed')));await expect(loadPublishedPageIdentity(page,scope)).rejects.toThrow('Read failed');expect(mockCovers).not.toHaveBeenCalled();});
it('only requests exact page-linked Live standalone events and uses Scene’s end-time-first clock',async()=>{mockFrom.mockImplementation(table=>query(table,table==='creator_page_publications'?[identity()]:table==='creator_page_events'?[{event_id:event,page_id:page},{event_id:otherEvent,page_id:page}]:[row(event,{start_time:'2026-09-14T00:00:00Z',end_time:'2026-09-15T04:00:00Z'}),row(otherEvent,{end_time:'2026-09-14T00:00:00Z'})]));const result=await loadPublishedOrganizationPage(page,scope,Date.parse('2026-09-15T00:00:00Z'));expect(result?.upcomingEvents.map(e=>e.id)).toEqual([event]);expect(result?.pastEvents.map(e=>e.id)).toEqual([otherEvent]);expect(calls).toEqual(expect.arrayContaining([{table:'creator_page_events',key:'eq',args:['page_id',page]},{table:'explore_events',key:'in',args:['id',[event,otherEvent]]},{table:'explore_events',key:'eq',args:['status','Live']},{table:'explore_events',key:'is',args:['community_id',null]}]));expect(calls.some(c=>c.args[0]==='host_user_id')).toBe(false);});
it('rejects another page’s event linkage instead of mixing an owner’s pages',async()=>{mockFrom.mockImplementation(table=>query(table,table==='creator_page_publications'?[identity()]:[{event_id:otherEvent,page_id:otherPage}]));await expect(loadPublishedOrganizationPage(page,scope)).rejects.toThrow('this page');expect(mockFrom).not.toHaveBeenCalledWith('explore_events');});
it('does not let an owner’s private event appear in a public projection',async()=>{mockFrom.mockImplementation(table=>query(table,table==='creator_page_publications'?[identity()]:table==='creator_page_events'?[{event_id:event,page_id:page}]:[row(event,{status:'Draft'})]));await expect(loadPublishedOrganizationPage(page,scope)).rejects.toThrow('public events');});
it('keeps each event attached to its own page even when both pages share the same owner',async()=>{mockFrom.mockImplementation(table=>query(table,table==='creator_page_events'?[{event_id:event,page_id:page},{event_id:otherEvent,page_id:otherPage}]:[identity(),identity(otherPage)]));const result=await loadPublishedEventPageIdentities([event,otherEvent],scope);expect(result.get(event)?.page?.name).toBe('Sunday Table');expect(result.get(otherEvent)?.page?.name).toBe('Another page');});
it('distinguishes a legacy event from known unpublished page linkage',async()=>{mockFrom.mockImplementation(table=>query(table,table==='creator_page_events'?[{event_id:event,page_id:page}]:[]));const result=await loadPublishedEventPageIdentities([event,otherEvent],scope);expect(result.get(event)).toEqual({pageId:page,page:null});expect(result.has(otherEvent)).toBe(false);});
it('checks account scope again after reads and drops late account data',async()=>{mockSession.mockResolvedValueOnce({data:{session:{user:{id:owner}}}}).mockResolvedValueOnce({data:{session:{user:{id:'new-account'}}}});await expect(loadPublishedPageIdentity(page,scope)).rejects.toThrow();});
it('supports a confirmed signed-out viewer without claiming private draft access',async()=>{mockSession.mockResolvedValue({data:{session:null},error:null});const result=await loadPublishedOrganizationPage(page,{userId:null,isCurrent:()=>true});expect(result?.page.pageId).toBe(page);expect(mockFrom).not.toHaveBeenCalledWith('creator_page_drafts');});
it('loads linked events beyond one backend page instead of silently truncating the organization',async()=>{
 const links=Array.from({length:101},(_,i)=>({event_id:`aaaaaaaa-aaaa-4aaa-8aaa-${String(i).padStart(12,'0')}`,page_id:page}));
 let linkReads=0;
 mockFrom.mockImplementation(table=>{
  if(table==='creator_page_publications')return query(table,[identity()]);
  if(table==='creator_page_events')return query(table,linkReads++===0?links.slice(0,100):links.slice(100));
  const q=query(table,[]);q.in=(_key:string,ids:string[])=>{q.then=(r:any)=>Promise.resolve({data:ids.map(id=>row(id)),error:null}).then(r);return q;};return q;
 });
 const result=await loadPublishedOrganizationPage(page,scope,Date.parse('2026-09-14T00:00:00Z'));
 expect(result?.upcomingEvents).toHaveLength(101);expect(new Set(result?.upcomingEvents.map(e=>e.id)).size).toBe(101);expect(linkReads).toBe(2);
});
