const mockSession=jest.fn(),mockUser=jest.fn(),mockFrom=jest.fn();
jest.mock('../supabase',()=>({SUPABASE_URL:'http://127.0.0.1:55321',SUPABASE_ANON_KEY:'anonymous-test-key',supabase:{auth:{getSession:()=>mockSession(),getUser:()=>mockUser()},from:(...a:unknown[])=>mockFrom(...a)}}));
import {loadPublishedPageCoverSource,getPublishedCoverMediaIds,communityCoverReference} from '../publishedPageCover';
const page='11111111-1111-4111-8111-111111111111',media='22222222-2222-4222-8222-222222222222';
const publication={page_id:page,media_id:media},metadata={id:media,page_id:page,object_name:`${page}/${media}.jpg`,mime_type:'image/jpeg',ready_at:'ready'};
const scope={userId:'member',isCurrent:()=>true};
function query(data:unknown,error:unknown=null){const q:any={};for(const k of ['select','eq','in','maybeSingle'])q[k]=()=>q;q.then=(r:any)=>Promise.resolve({data,error}).then(r);return q;}
beforeEach(()=>{jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'member'},access_token:'member-token'}},error:null});mockUser.mockResolvedValue({data:{user:{id:'member'}},error:null});mockFrom.mockImplementation(table=>query(table==='creator_page_cover_publications'?publication:metadata));});
it('checks exact publication and current account before returning authenticated bytes URL',async()=>{const result=await loadPublishedPageCoverSource(page,media,scope);expect(result.uri).toContain(`/object/authenticated/creator-page-media/${page}/${media}.jpg`);expect(result.headers.Authorization).toBe('Bearer member-token');expect(mockFrom.mock.calls.map(a=>a[0])).toEqual(['creator_page_cover_publications','creator_page_media']);expect(mockUser).toHaveBeenCalledTimes(2);});
it('supports signed-out browsing through the anon-key authenticated route when RLS returns the publication',async()=>{mockSession.mockResolvedValue({data:{session:null},error:null});const result=await loadPublishedPageCoverSource(page,media,{userId:null,isCurrent:()=>true});expect(result.headers.Authorization).toBe('Bearer anonymous-test-key');expect(mockUser).not.toHaveBeenCalled();});
it('does not reveal a private or removed cover even to an owner who could read its media',async()=>{mockFrom.mockImplementation(()=>query(null));await expect(loadPublishedPageCoverSource(page,media,scope)).rejects.toThrow('published cover');expect(mockFrom).toHaveBeenCalledTimes(1);});
it('rejects an older or unselected cover instead of displaying it in a published page',async()=>{mockFrom.mockImplementation(()=>query({...publication,media_id:'another'}));await expect(loadPublishedPageCoverSource(page,media,scope)).rejects.toThrow();expect(mockFrom).toHaveBeenCalledTimes(1);});
it('rejects arbitrary object paths and unready metadata',async()=>{mockFrom.mockImplementation(table=>query(table==='creator_page_cover_publications'?publication:{...metadata,object_name:'different/public.jpg'}));await expect(loadPublishedPageCoverSource(page,media,scope)).rejects.toThrow('unavailable');mockFrom.mockImplementation(table=>query(table==='creator_page_cover_publications'?publication:{...metadata,ready_at:null}));await expect(loadPublishedPageCoverSource(page,media,scope)).rejects.toThrow();});
it('drops late data after an account change and rejects stale identity before reading',async()=>{let active=true;mockFrom.mockImplementation(()=>{active=false;return query(publication);});await expect(loadPublishedPageCoverSource(page,media,{...scope,isCurrent:()=>active})).rejects.toThrow();expect(mockFrom).toHaveBeenCalledTimes(1);mockFrom.mockClear();await expect(loadPublishedPageCoverSource(page,media,{userId:'other',isCurrent:()=>true})).rejects.toThrow();expect(mockFrom).not.toHaveBeenCalled();});
it('does not put a replacement account token into the image request',async()=>{mockSession.mockResolvedValueOnce({data:{session:{user:{id:'member'},access_token:'member-token'}}}).mockResolvedValueOnce({data:{session:{user:{id:'other'},access_token:'other-token'}}});await expect(loadPublishedPageCoverSource(page,media,scope)).rejects.toThrow();});
it('batches only the supplied visible page IDs and surfaces enrichment failures',async()=>{mockFrom.mockImplementation(()=>query([publication]));expect(await getPublishedCoverMediaIds([page,page])).toEqual(new Map([[page,media]]));mockFrom.mockImplementation(()=>query(null,new Error('Unavailable')));await expect(getPublishedCoverMediaIds([page])).rejects.toThrow('Unavailable');});
it('preserves old galleries but gives a protected reference precedence over any legacy fallback',()=>{expect(communityCoverReference({images:['one','two']})).toEqual({mediaId:null,images:['one','two'],hasCover:true});expect(communityCoverReference({cover_media_id:media,images:['old-public']})).toEqual({mediaId:media,images:[],hasCover:true});expect(communityCoverReference({images:[]})).toEqual({mediaId:null,images:[],hasCover:false});});
