import { readPurchaseExtras } from '../purchaseExtras';
const mockSession=jest.fn(),mockRequest=jest.fn();const requests:any[]=[];
jest.mock('../supabase',()=>({supabase:{auth:{getSession:(...args:any[])=>mockSession(...args)},from:(table:string)=>{const call:any={table,filters:[]};requests.push(call);const query:any={select:(cols:string)=>{call.columns=cols;return query;},eq:(key:string,value:string)=>{call.filters.push([key,value]);return query;},in:(key:string,value:string[])=>{call.ids=value;return query;},setHeader:(key:string,value:string)=>{call.authorization=value;return mockRequest(call);}};return query;}}}));
let active=true;const owner={userId:'buyer',isCurrent:()=>active};
const extra={id:'extra',qty:2,unit_price_cents:1200,name_snapshot:'Original picnic',variation_id:'vegan',variation_label_snapshot:'Original vegan option'};
const row={id:'order',event_id:'event',order_add_ons:[extra]};
beforeEach(()=>{active=true;requests.length=0;jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'buyer'},access_token:'synthetic-token'}}});mockRequest.mockResolvedValue({data:[row]});});
it('reads snapshots with exact buyer, event, order and initiating token',async()=>{
 expect((await readPurchaseExtras('event',['order'],owner)).get('order')).toEqual([{id:'extra',name:'Original picnic',quantity:2,unitPriceCents:1200,optionLabel:'Original vegan option'}]);
 expect(requests[0].filters).toEqual([['event_id','event'],['buyer_user_id','buyer']]);expect(requests[0].ids).toEqual(['order']);expect(requests[0].authorization).toBe('Bearer synthetic-token');expect(requests[0].columns).not.toContain('event_add_ons');
});
it('missing or forbidden orders never masquerade as no extras',async()=>{mockRequest.mockResolvedValue({data:[]});await expect(readPurchaseExtras('event',['order'],owner)).rejects.toThrow('could not be loaded');});
it('confirms empty extras from a readable order',async()=>{mockRequest.mockResolvedValue({data:[{...row,order_add_ons:[]}]});expect((await readPurchaseExtras('event',['order'],owner)).get('order')).toEqual([]);});
it('rejects incomplete option snapshots and API failures',async()=>{mockRequest.mockResolvedValue({data:[{...row,order_add_ons:[{...extra,variation_label_snapshot:null}]}]});await expect(readPurchaseExtras('event',['order'],owner)).rejects.toThrow('could not be loaded');mockRequest.mockResolvedValue({error:Error('offline')});await expect(readPurchaseExtras('event',['order'],owner)).rejects.toThrow('could not be loaded');});
it('reads creator batches without dropping orders or adding a buyer filter',async()=>{const ids=Array.from({length:81},(_,i)=>'order-'+i);mockRequest.mockImplementation(async request=>({data:request.ids.map((id:string)=>({...row,id}))}));const result=await readPurchaseExtras('event',ids,owner,false);expect(result.size).toBe(81);expect(requests.map(r=>r.ids.length)).toEqual([40,40,1]);expect(requests.every(r=>r.filters.length===1)).toBe(true);});
it('stops late reads and prevents dispatch with another signed-in account',async()=>{mockRequest.mockImplementation(async()=>{active=false;return {data:[row]};});await expect(readPurchaseExtras('event',['order'],owner)).rejects.toThrow('no longer active');active=true;mockSession.mockResolvedValue({data:{session:{user:{id:'other'},access_token:'other'}}});await expect(readPurchaseExtras('event',['order'],owner)).rejects.toThrow('sign-in');expect(requests).toHaveLength(1);});
