const mockFrom=jest.fn(),mockSession=jest.fn();
jest.mock('../supabase',()=>({supabase:{from:(...args:any[])=>mockFrom(...args),auth:{getSession:()=>mockSession()}}}));
import {getAnsweredQuestionIds,getConfirmationMessage,recordAnswer} from '../ticketing';
function response(value:any){const builder:any={select:()=>builder,eq:()=>builder,maybeSingle:async()=>value,then:(resolve:any,reject:any)=>Promise.resolve(value).then(resolve,reject),insert:jest.fn(async()=>value)};mockFrom.mockReturnValue(builder);return builder;}
beforeEach(()=>{jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{user:{id:'buyer'}}},error:null});});
it('strict answer read rejects a backend failure while the legacy reader stays compatible',async()=>{response({data:null,error:Error('offline')});await expect(getAnsweredQuestionIds('order',true)).rejects.toThrow('offline');expect(await getAnsweredQuestionIds('order')).toEqual(new Map());});
it('strict empty answers are a successful empty result, preserving per-order and per-seat slots',async()=>{response({data:[{question_id:'one',attendee_index:null},{question_id:'two',attendee_index:2}],error:null});expect(await getAnsweredQuestionIds('order',true)).toEqual(new Map<string, Set<number | null>>([['one',new Set([null])],['two',new Set([2])]]));response({data:[],error:null});expect(await getAnsweredQuestionIds('order',true)).toEqual(new Map());});
it('strict note failures and unavailable events are distinct from an intentionally empty note',async()=>{response({data:null,error:Error('offline')});await expect(getConfirmationMessage('event',true)).rejects.toThrow('offline');expect(await getConfirmationMessage('event')).toBeNull();response({data:null,error:null});await expect(getConfirmationMessage('event',true)).rejects.toThrow();response({data:{confirmation_message:null},error:null});expect(await getConfirmationMessage('event',true)).toBeNull();});
it('refuses answer dispatch after account mismatch',async()=>{const b=response({error:null});expect((await recordAnswer('order','q',{text:'private'},null,{userId:'other',isCurrent:()=>true})).ok).toBe(false);expect(b.insert).not.toHaveBeenCalled();});
it('refuses a scope retired while checking its session',async()=>{let current=true;mockSession.mockImplementation(async()=>{current=false;return {data:{session:{user:{id:'buyer'}}}};});const b=response({error:null});await recordAnswer('order','q',{text:'private'},1,{userId:'buyer',isCurrent:()=>current});expect(b.insert).not.toHaveBeenCalled();});
it('keeps the original insert-only answer write and legacy call shape',async()=>{const b=response({error:null});expect((await recordAnswer('order','q',{text:'private'},1)).ok).toBe(true);expect(mockSession).not.toHaveBeenCalled();expect(b.insert).toHaveBeenCalledWith({order_id:'order',question_id:'q',attendee_index:1,value:{text:'private'}});});
