import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Crypto from 'expo-crypto';
const mockRpc=jest.fn(),mockSession=jest.fn(),mockRead=jest.fn();const reads:any[]=[];
jest.mock('../supabase',()=>({supabase:{auth:{getSession:()=>mockSession()},rpc:(name:string,args:any)=>({setHeader:(_k:string,value:string)=>mockRpc(name,args,value)}),from:()=>{const call:any={};reads.push(call);const q:any={select:(columns:string)=>{call.columns=columns;return q;},in:(key:string,value:string[])=>{call.ids=value;return q;},eq:(key:string,value:string)=>{call.filter=[key,value];return q;},setHeader:(_k:string,value:string)=>{call.authorization=value;return mockRead(call);}};return q;}}}));
import {readLegacyCheckins,confirmLegacyCheckins,listQueued,type CheckinContext} from '../ticketDoor';
const user='11111111-1111-4111-8111-111111111111',event='22222222-2222-4222-8222-222222222222',page='33333333-3333-4333-8333-333333333333';let current=true;
const context:CheckinContext={eventId:event,pageId:page,scope:{userId:user,isCurrent:()=>current}};
const key='ticket_checkin_queue_v1',queuedAt='2026-09-16T20:00:00Z';let original:string;
async function legacy(code:string){return {code,queuedAt,signature:await Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256,`device:${code}:${queuedAt}`)};}
beforeEach(async()=>{jest.clearAllMocks();reads.length=0;current=true;await AsyncStorage.clear();await AsyncStorage.setItem('ticket_checkin_device_key_v1','device');original=JSON.stringify([await legacy('ENTRY234'),await legacy('OTHER234'),{code:'BROKEN',signature:'invalid'}]);await AsyncStorage.setItem(key,original);mockSession.mockResolvedValue({data:{session:{user:{id:user},access_token:'synthetic'}}});mockRpc.mockImplementation(async name=>name==='is_ticketing_organizer'?{data:true}:{data:{result:'duplicate',admitted_at:queuedAt}});mockRead.mockResolvedValue({data:[{reference_code:'ENTRY234',ticket_orders:{event_id:event}}]});});
it('read-only preview reveals only signed codes matched to current event by backend',async()=>{expect(await readLegacyCheckins(context)).toEqual([{code:'ENTRY234',queuedAt}]);expect(reads[0]).toMatchObject({filter:['ticket_orders.event_id',event],authorization:'Bearer synthetic',ids:['ENTRY234','OTHER234']});expect(mockRpc.mock.calls.every(c=>c[0]==='is_ticketing_organizer')).toBe(true);expect(await AsyncStorage.getItem(key)).toBe(original);});
it('explicit confirmation revalidates then clears only the exact server-confirmed old record',async()=>{const selected=await readLegacyCheckins(context);const result=await confirmLegacyCheckins(context,selected);expect(result.remaining).toBe(0);expect(result.processed[0].outcome).toMatchObject({kind:'result',result:'duplicate'});expect(JSON.parse((await AsyncStorage.getItem(key))!)).toEqual([JSON.parse(original)[1],JSON.parse(original)[2]]);});
it('permission revoked after preview prevents replay and preserves every old record',async()=>{const selected=await readLegacyCheckins(context);mockRpc.mockResolvedValue({data:false});await expect(confirmLegacyCheckins(context,selected)).rejects.toThrow('access');expect(mockRpc.mock.calls.every(c=>c[0]==='is_ticketing_organizer')).toBe(true);expect(await AsyncStorage.getItem(key)).toBe(original);});
it('lost acknowledgement retains old record and a scoped pending copy until confirmed retry',async()=>{mockRpc.mockImplementation(async name=>name==='is_ticketing_organizer'?{data:true}:Promise.reject(Error('lost reply')));const selected=await readLegacyCheckins(context);expect((await confirmLegacyCheckins(context,selected)).remaining).toBe(1);expect(await AsyncStorage.getItem(key)).toBe(original);expect(await listQueued(context)).toEqual([expect.objectContaining({code:'ENTRY234'})]);mockRpc.mockImplementation(async name=>name==='is_ticketing_organizer'?{data:true}:{data:{result:'duplicate',admitted_at:queuedAt}});await confirmLegacyCheckins(context,selected);expect(await listQueued(context)).toEqual([]);expect(JSON.parse((await AsyncStorage.getItem(key))!)).toHaveLength(2);});
it('rejects an arbitrary code not present in the fresh authorized preview',async()=>{await expect(confirmLegacyCheckins(context,[{code:'OTHER234',queuedAt}])).rejects.toThrow('changed');expect(mockRpc.mock.calls.every(c=>c[0]==='is_ticketing_organizer')).toBe(true);expect(await AsyncStorage.getItem(key)).toBe(original);});
it('failed legacy removal preserves the record for duplicate-safe retry',async()=>{const selected=await readLegacyCheckins(context);const setter=AsyncStorage.setItem as jest.Mock;const base=setter.getMockImplementation()!;setter.mockImplementation((k,v)=>k===key?Promise.reject(Error('storage full')):base(k,v));try{await expect(confirmLegacyCheckins(context,selected)).rejects.toThrow('storage full');expect(await AsyncStorage.getItem(key)).toBe(original);}finally{setter.mockImplementation(base);}});
it('unreadable data and failed matching never silently discard or replay records',async()=>{mockRead.mockResolvedValue({error:Error('offline')});await expect(readLegacyCheckins(context)).rejects.toThrow('matched');expect(await AsyncStorage.getItem(key)).toBe(original);await AsyncStorage.setItem(key,'broken json');await expect(readLegacyCheckins(context)).rejects.toThrow();expect(await AsyncStorage.getItem(key)).toBe('broken json');});
it('retired account cannot confirm a previously displayed preview',async()=>{const selected=await readLegacyCheckins(context);current=false;await expect(confirmLegacyCheckins(context,selected)).rejects.toThrow('no longer active');expect(await AsyncStorage.getItem(key)).toBe(original);});

it('missing original device key never generates a replacement during read-only preview',async()=>{await AsyncStorage.removeItem('ticket_checkin_device_key_v1');await expect(readLegacyCheckins(context)).rejects.toThrow('kept');expect(await AsyncStorage.getItem('ticket_checkin_device_key_v1')).toBeNull();expect(await AsyncStorage.getItem(key)).toBe(original);});
it('records added after preview survive exact-record cleanup',async()=>{const selected=await readLegacyCheckins(context);const added=await legacy('LATER234');mockRpc.mockImplementation(async name=>{if(name==='is_ticketing_organizer')return{data:true};await AsyncStorage.setItem(key,JSON.stringify([...JSON.parse(original),added]));return{data:{result:'duplicate',admitted_at:queuedAt}};});await confirmLegacyCheckins(context,selected);expect(JSON.parse((await AsyncStorage.getItem(key))!)).toEqual([JSON.parse(original)[1],JSON.parse(original)[2],added]);});
