const mockSession=jest.fn(),mockTask=jest.fn(),mockRun=jest.fn(),mockCancel=jest.fn();
jest.mock('expo-file-system/legacy',()=>({FileSystemUploadType:{BINARY_CONTENT:'binary'},createUploadTask:(...a:unknown[])=>mockTask(...a)}));
jest.mock('../supabase',()=>({SUPABASE_URL:'https://storage.test.invalid',supabase:{auth:{getSession:()=>mockSession()},storage:{from:()=>({getPublicUrl:()=>({data:{publicUrl:'confirmed'}})})}}}));
import {uploadUriToStorage} from '../uploadPhoto';
beforeEach(()=>{jest.clearAllMocks();mockSession.mockResolvedValue({data:{session:{access_token:'synthetic-token'}}});mockTask.mockReturnValue({uploadAsync:mockRun,cancelAsync:mockCancel});mockRun.mockResolvedValue({status:200});mockCancel.mockResolvedValue(undefined);});
it('checks the page guard after session retrieval and before creating a native upload task',async()=>{const guard=jest.fn(async()=>{expect(mockSession).toHaveBeenCalled();expect(mockTask).not.toHaveBeenCalled();});const task=uploadUriToStorage('event-content','event/clip.mp4','local','video/mp4',undefined,guard);expect(await task.done).toBe('confirmed');expect(guard).toHaveBeenCalledTimes(1);expect(mockTask).toHaveBeenCalledTimes(1);});
it('rejects a changed page scope before dispatching native bytes',async()=>{const task=uploadUriToStorage('event-content','event/clip.mp4','local','video/mp4',undefined,async()=>{throw Error('Retired');});await expect(task.done).rejects.toThrow('Retired');expect(mockTask).not.toHaveBeenCalled();});
it('cancel during the final guard prevents native dispatch',async()=>{let finish:any;const task=uploadUriToStorage('event-content','event/clip.mp4','local','video/mp4',undefined,()=>new Promise(r=>{finish=r;}));await Promise.resolve();task.cancel();finish();expect(await task.done).toBeNull();expect(mockTask).not.toHaveBeenCalled();});
it('existing unguarded callers retain binary streaming and cancel',async()=>{let finish:any;mockRun.mockImplementation(()=>new Promise(r=>{finish=r;}));const task=uploadUriToStorage('event-content','event/clip.mp4','local','video/mp4');await Promise.resolve();await Promise.resolve();expect(mockTask.mock.calls[0][2]).toEqual(expect.objectContaining({uploadType:'binary',httpMethod:'POST'}));task.cancel();finish({status:200});expect(await task.done).toBeNull();expect(mockCancel).toHaveBeenCalledTimes(1);});
