import React from 'react';
import {act,create} from 'react-test-renderer';
const mockPerform=jest.fn(),mockSet=jest.fn(),mockRemove=jest.fn(),mockGet=jest.fn();const mockMemory=new Map<string,string>();
jest.mock('@react-native-async-storage/async-storage',()=>({__esModule:true,default:{getItem:(k:string)=>mockGet(k),setItem:(k:string,v:string)=>mockSet(k,v),removeItem:(k:string)=>mockRemove(k)}}));
jest.mock('expo-crypto',()=>({randomUUID:()=> '44444444-4444-4444-8444-444444444444'}));
jest.mock('../../lib/creatorTicketAction',()=>({performTicketAction:(...a:any[])=>mockPerform(...a)}));
import {useCreatorTicketAction} from '../useCreatorTicketAction';
let api:ReturnType<typeof useCreatorTicketAction>,tree:any,current=true;const done=jest.fn();let scope={userId:'creator',isCurrent:()=>current};
const action={kind:'tier-sale' as const,eventId:'event',recordId:'tier',label:'Entry',expected:'on_sale'};
let eventId:string|undefined;function Probe(){api=useCreatorTicketAction(scope,done,eventId);return null;}
beforeEach(()=>{eventId=undefined;mockMemory.clear();mockGet.mockImplementation(async k=>mockMemory.get(k)??null);mockSet.mockImplementation(async(k,v)=>{mockMemory.set(k,v);});mockRemove.mockImplementation(async k=>{mockMemory.delete(k);});current=true;scope={userId:'creator',isCurrent:()=>current};jest.clearAllMocks();act(()=>{tree=create(<Probe/>);});});
afterEach(()=>act(()=>tree.unmount()));
it('blocks double taps synchronously and preserves a single original intent',async()=>{let finish:any;mockPerform.mockImplementation(()=>new Promise(r=>finish=r));const old=api!;let pending:any;act(()=>{pending=old.run(action);void old.run({...action,recordId:'another'});});expect(mockPerform).toHaveBeenCalledTimes(1);await act(async()=>{finish('unknown');await pending;});await act(async()=>{await old.run({...action,recordId:'another'});});expect(mockPerform).toHaveBeenCalledTimes(1);expect(api!.recovery?.action).toEqual(action);});
it('checks an unknown result without writing and retries only a confirmed unchanged intent',async()=>{mockPerform.mockResolvedValueOnce('unknown').mockResolvedValueOnce('unchanged').mockResolvedValueOnce('confirmed');await act(async()=>{await api!.run(action);});await act(async()=>{await api!.retry();});expect(mockPerform).toHaveBeenCalledTimes(1);await act(async()=>{await api!.check();});expect(mockPerform.mock.calls[1][2]).toBe(true);await act(async()=>{await api!.retry();});expect(mockPerform.mock.calls[2][0]).toBe(action);expect(mockPerform.mock.calls[2][2]).toBe(false);expect(done).toHaveBeenCalledTimes(1);expect(api!.recovery).toBeNull();});
it('suppresses retired success and retains read-only recovery after focus returns',async()=>{let finish:any;mockPerform.mockImplementationOnce(()=>new Promise(r=>finish=r));let pending:any;act(()=>{pending=api!.run(action);});current=false;await act(async()=>{finish('confirmed');await pending;});expect(done).not.toHaveBeenCalled();expect(api!.recovery?.state).toBe('unknown');current=true;scope={userId:'creator',isCurrent:()=>current};act(()=>tree.update(<Probe/>));mockPerform.mockResolvedValue('confirmed');await act(async()=>{await api!.check();});expect(done).toHaveBeenCalledTimes(1);});
it('requires a reload after a concurrent change, and does not allow an unsafe retry',async()=>{mockPerform.mockResolvedValue('changed');await act(async()=>{await api!.run(action);await api!.retry();});expect(mockPerform).toHaveBeenCalledTimes(1);act(()=>api!.dismiss());expect(api!.blocked).toBe(false);});

it('allows leaving a checked unchanged action without trapping all management',async()=>{mockPerform.mockResolvedValue('unchanged');await act(async()=>{await api!.run(action);});act(()=>api!.dismiss());expect(api!.blocked).toBe(false);expect(mockPerform).toHaveBeenCalledTimes(1);});

const event='11111111-1111-4111-8111-111111111111',page='22222222-2222-4222-8222-222222222222',user='33333333-3333-4333-8333-333333333333',extra='55555555-5555-4555-8555-555555555555';
const pageAction={kind:'remove-extra' as const,eventId:event,recordId:extra,label:'Blanket',pageId:page};
async function pageMount(){act(()=>tree.unmount());eventId=event;scope={userId:user,isCurrent:()=>current};await act(async()=>{tree=create(<Probe/>);await new Promise(r=>setTimeout(r,0));});}
it('persists page removal before calling the service and restores it without dispatch on reopening',async()=>{await pageMount();mockPerform.mockImplementationOnce(async(a:any)=>{expect(JSON.parse([...mockMemory.values()][0]).action.requestId).toBe(a.requestId);return 'unknown';});await act(async()=>{await api!.run(pageAction);});const original=mockPerform.mock.calls[0][0];await pageMount();expect(mockPerform).toHaveBeenCalledTimes(1);expect(api!.recovery?.action).toEqual(original);mockPerform.mockResolvedValueOnce('in_use');await act(async()=>{await api!.check();});expect(mockPerform.mock.calls[1][0]).toEqual(original);expect(mockPerform.mock.calls[1][2]).toBe(true);expect(api!.blocked).toBe(false);expect(api!.notice).toContain('linked to an order');expect(mockMemory.size).toBe(0);});
it('a failed device write prevents page-extra dispatch',async()=>{await pageMount();mockSet.mockRejectedValueOnce(Error('storage full'));await act(async()=>{await api!.run(pageAction);});expect(mockPerform).not.toHaveBeenCalled();expect(api!.blocked).toBe(true);mockPerform.mockResolvedValueOnce('unchanged');await act(async()=>{await api!.check();});expect(mockPerform.mock.calls[0][2]).toBe(true);});
it('failed cleanup retains the same original recovery until Check succeeds',async()=>{await pageMount();mockPerform.mockResolvedValue('in_use');mockRemove.mockRejectedValueOnce(Error('locked'));await act(async()=>{await api!.run(pageAction);});expect(api!.blocked).toBe(true);expect(done).not.toHaveBeenCalled();await act(async()=>{await api!.check();});expect(api!.blocked).toBe(false);expect(done).toHaveBeenCalledTimes(1);expect(mockPerform.mock.calls[1][0]).toEqual(mockPerform.mock.calls[0][0]);});
it('an uncertain page removal cannot be forgotten from an unchanged observation',async()=>{await pageMount();mockPerform.mockResolvedValue('unchanged');await act(async()=>{await api!.run(pageAction);});act(()=>api!.dismiss());expect(api!.blocked).toBe(true);expect(mockMemory.size).toBe(1);});
it('storage-read failure blocks new management until explicit reload succeeds',async()=>{mockGet.mockRejectedValueOnce(Error('unavailable'));await pageMount();expect(api!.blocked).toBe(true);expect(api!.storageError).toContain('couldn’t be loaded');await act(async()=>{await api!.run(pageAction);});expect(mockPerform).not.toHaveBeenCalled();await act(async()=>{await api!.reload();});expect(api!.blocked).toBe(false);});
it('stale callbacks cannot start another action while device recovery reloads',async()=>{await pageMount();const old=api!;let release!:(v:null)=>void;mockGet.mockImplementationOnce(()=>new Promise(r=>{release=r;}));let reloading:Promise<void>;act(()=>{reloading=api!.reload();});await act(async()=>{await old.run(pageAction);});await act(async()=>{release(null);await reloading!;});expect(mockPerform).not.toHaveBeenCalled();expect(api!.blocked).toBe(false);});
