import React from 'react';
import { act, create } from 'react-test-renderer';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useCreatorCommunityGroups } from '../useCreatorCommunityGroups';
import { canManageCommunityGroups, createCreatorCommunityGroup, getCreatorGroupCreation, renameCreatorCommunityRoom } from '../../lib/creatorCommunityGroups';
import { clearCreatorGroupAttempt, prepareCreatorGroupAttempt, readCreatorGroupAttempt } from '../../lib/creatorCommunityGroupAttempt';
import { getCommunityRoomIdentities, type CommunityRoomIdentity } from '../../lib/communityRoomHistory';
import type { ObservedUser } from '../useObservedUser';
jest.mock('../../lib/creatorCommunityGroups',()=>({canManageCommunityGroups:jest.fn(),createCreatorCommunityGroup:jest.fn(),getCreatorGroupCreation:jest.fn(),renameCreatorCommunityRoom:jest.fn(),normalizeCommunityRoomName:(name:string)=>{if(!name.trim())throw Error('Use a name');return name.trim();}}));
jest.mock('../../lib/creatorCommunityGroupAttempt',()=>({clearCreatorGroupAttempt:jest.fn(),prepareCreatorGroupAttempt:jest.fn(),readCreatorGroupAttempt:jest.fn()}));
jest.mock('../../lib/communityRoomHistory',()=>({getCommunityRoomIdentities:jest.fn()}));
const allowed=jest.mocked(canManageCommunityGroups),write=jest.mocked(createCreatorCommunityGroup),check=jest.mocked(getCreatorGroupCreation),rename=jest.mocked(renameCreatorCommunityRoom),prepare=jest.mocked(prepareCreatorGroupAttempt),saved=jest.mocked(readCreatorGroupAttempt),clear=jest.mocked(clearCreatorGroupAttempt),rooms=jest.mocked(getCommunityRoomIdentities);
const attempt={communityId:'page',requestId:'request',name:'Walks'},receipt={...attempt,currentName:'Walks',status:'available' as const};
const room={id:'room',role:'optional',storage:'topic',name:'Coffee',joined:true,included:false,notifications_on:false} as CommunityRoomIdentity;
const close:Array<()=>void>=[];async function flush(){for(let i=0;i<3;i++)await act(async()=>{await new Promise(r=>setTimeout(r,0));});}
const deferred=<T,>()=>{let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{resolve,promise};};
function mount(){const client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:Infinity}}});let result!:ReturnType<typeof useCreatorCommunityGroups>,tree!:ReturnType<typeof create>,id='a',epoch=1,enabled=true;
 function Harness(){const captured=id;result=useCreatorCommunityGroups('page',{viewerId:id,epoch,error:null,isLoading:false,retry:async()=>{},isCurrent:()=>captured===id} as ObservedUser,enabled);return null;}
 const node=()=> <QueryClientProvider client={client}><Harness/></QueryClientProvider>;
 act(()=>{tree=create(node());});close.push(()=>{act(()=>tree.unmount());client.clear();});
 return{get result(){return result;},account:(value:string)=>{id=value;epoch++;act(()=>tree.update(node()));},focus:(value:boolean)=>{enabled=value;act(()=>tree.update(node()));},unmount:()=>{act(()=>tree.unmount());}};
}
beforeEach(()=>{jest.clearAllMocks();[allowed,write,check,rename,prepare,saved,clear,rooms].forEach(mock=>mock.mockReset());allowed.mockResolvedValue(true);saved.mockResolvedValue(null);prepare.mockResolvedValue({attempt,created:true});write.mockResolvedValue(receipt);check.mockResolvedValue(null);clear.mockResolvedValue(undefined);rename.mockResolvedValue({...room,name:'Sunsets'});rooms.mockResolvedValue({communityId:'page',name:'Community',rooms:[room]});});
afterEach(async()=>{close.splice(0).forEach(f=>f());await flush();});
async function createForm(f:ReturnType<typeof mount>){await flush();act(()=>f.result.startCreate());act(()=>f.result.setDraft('Walks'));}
it('ordinary members cannot open or dispatch creator forms',async()=>{allowed.mockResolvedValue(false);const f=mount();await flush();act(()=>{f.result.startCreate();f.result.startRename(room);});await f.result.submit();expect(f.result.form).toBeNull();expect(prepare).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();});
it('reopens saved creation for checking without silently publishing it',async()=>{saved.mockResolvedValue(attempt);const f=mount();await flush();expect(f.result.form).toMatchObject({kind:'create',pending:true,retryReady:false,attempt});expect(write).not.toHaveBeenCalled();expect(check).not.toHaveBeenCalled();});
it('persists before network dispatch, serializes rapid taps and clears confirmed work',async()=>{const pending=deferred<typeof receipt>();write.mockReturnValue(pending.promise);const f=mount();await createForm(f);let operation:any;act(()=>{operation=f.result.submit();void f.result.submit();});await flush();expect(write).toHaveBeenCalledTimes(1);expect(prepare.mock.invocationCallOrder[0]).toBeLessThan(write.mock.invocationCallOrder[0]);expect(clear).not.toHaveBeenCalled();await act(async()=>{pending.resolve(receipt);await operation;});expect(f.result.form).toBeNull();expect(clear).toHaveBeenCalledWith(receipt,expect.anything());});
it('does not send an attempt recovered from another simultaneous form until checking',async()=>{prepare.mockResolvedValue({attempt,created:false});const f=mount();await createForm(f);await act(async()=>{await f.result.submit();});expect(write).not.toHaveBeenCalled();expect(f.result.form?.pending).toBe(true);});
it('checks a lost committed response read-only and clears the original attempt',async()=>{write.mockRejectedValue(Error('Lost response'));const f=mount();await createForm(f);await act(async()=>{await f.result.submit();await f.result.retry();});expect(write).toHaveBeenCalledTimes(1);expect(f.result.form?.retryReady).toBe(false);check.mockResolvedValue(receipt);await act(async()=>{await f.result.check();});expect(write).toHaveBeenCalledTimes(1);expect(f.result.form).toBeNull();});
it('retries only the same persisted request after a negative read and an explicit tap',async()=>{write.mockRejectedValueOnce(Error('Disconnected')).mockResolvedValue(receipt);const f=mount();await createForm(f);await act(async()=>{await f.result.submit();await f.result.check();});expect(f.result.form?.retryReady).toBe(true);act(()=>f.result.setDraft('Different'));await act(async()=>{await f.result.retry();});expect(write).toHaveBeenCalledTimes(2);expect(write.mock.calls[1][0]).toEqual(attempt);expect(prepare).toHaveBeenCalledTimes(1);});
it('storage failure never sends creation and checking can recover its saved attempt',async()=>{prepare.mockRejectedValue(Error('Storage result lost'));const f=mount();await createForm(f);await act(async()=>{await f.result.submit();});expect(write).not.toHaveBeenCalled();saved.mockResolvedValue(attempt);await act(async()=>{await f.result.check();});expect(f.result.form).toMatchObject({attempt,retryReady:true});expect(write).not.toHaveBeenCalled();});
it('never recreates a deleted or archived saved group',async()=>{saved.mockResolvedValue(attempt);const f=mount();await flush();check.mockResolvedValue({...receipt,currentName:null,status:'unavailable'});await act(async()=>{await f.result.check();});expect(f.result.notice).toContain('no longer available');expect(f.result.form).toBeNull();expect(write).not.toHaveBeenCalled();});
it('keeps unknown creation on blur and ignores its late response until checking on return',async()=>{const pending=deferred<typeof receipt>();write.mockReturnValue(pending.promise);const f=mount();await createForm(f);let operation:any;act(()=>{operation=f.result.submit();});await flush();f.focus(false);await act(async()=>{pending.resolve(receipt);await operation;});expect(clear).not.toHaveBeenCalled();f.focus(true);await flush();expect(f.result.form?.pending).toBe(true);expect(write).toHaveBeenCalledTimes(1);});
it('retires old account callbacks and never clears its saved work after switching',async()=>{const pending=deferred<typeof receipt>();write.mockReturnValue(pending.promise);const f=mount();await createForm(f);const old=f.result;let operation:any;act(()=>{operation=old.submit();});await flush();f.account('b');await flush();await act(async()=>{pending.resolve(receipt);await operation;await old.retry();});expect(clear).not.toHaveBeenCalled();expect(f.result.form).toBeNull();expect(write).toHaveBeenCalledTimes(1);});
it('renames the existing identity and confirms an unknown rename through a read',async()=>{rename.mockRejectedValue(Error('Response lost'));const f=mount();await flush();act(()=>f.result.startRename(room));act(()=>f.result.setDraft('Sunsets'));await act(async()=>{await f.result.submit();});expect(rename).toHaveBeenCalledWith('page',room,'Sunsets',expect.anything());rooms.mockResolvedValue({communityId:'page',name:'Community',rooms:[{...room,name:'Sunsets'}]});await act(async()=>{await f.result.check();});expect(rename).toHaveBeenCalledTimes(1);expect(f.result.form).toBeNull();expect(f.result.notice).toBe('Chat name saved.');});
it('retains the draft on a newer rename and requires reviewing the fresh name before saving',async()=>{rename.mockRejectedValue(Error('Conflict'));const f=mount();await flush();act(()=>f.result.startRename(room));act(()=>f.result.setDraft('Sunsets'));await act(async()=>{await f.result.submit();});rooms.mockResolvedValue({communityId:'page',name:'Community',rooms:[{...room,name:'Newer name'}]});await act(async()=>{await f.result.check();await f.result.retry();});expect(rename).toHaveBeenCalledTimes(1);expect(f.result.form).toMatchObject({pending:false,draft:'Sunsets',room:{name:'Newer name'}});expect(f.result.notice).toContain('Review your name');});
it('keeps failed checking unresolved and does not offer a blind retry',async()=>{saved.mockResolvedValue(attempt);check.mockRejectedValue(Error('Offline'));const f=mount();await flush();await act(async()=>{await f.result.check();await f.result.retry();});expect(f.result.form?.retryReady).toBe(false);expect(write).not.toHaveBeenCalled();expect(f.result.error).toContain('Couldn’t confirm');});
