import React from 'react';import {act,create,type ReactTestRenderer} from 'react-test-renderer';
const mockRead=jest.fn(),mockPrepare=jest.fn(),mockClear=jest.fn(),mockGet=jest.fn(),mockReserve=jest.fn(),mockAbandon=jest.fn(),mockStart=jest.fn(),mockReady=jest.fn(),mockDiscard=jest.fn(),mockCancel=jest.fn();
jest.mock('../../lib/creatorPageEventMediaAttempt',()=>({readPageEventMediaAttempts:(...a:unknown[])=>mockRead(...a),preparePageEventMediaAttempt:(...a:unknown[])=>mockPrepare(...a),clearPageEventMediaAttempt:(...a:unknown[])=>mockClear(...a)}));
jest.mock('../../lib/creatorPageEventMedia',()=>({getPageEventMediaAttempt:(...a:unknown[])=>mockGet(...a),reservePageEventMedia:(...a:unknown[])=>mockReserve(...a),abandonPageEventMedia:(...a:unknown[])=>mockAbandon(...a)}));
jest.mock('../../lib/creatorPageEventMediaTransfer',()=>({startPageEventMediaTransfer:(...a:unknown[])=>mockStart(...a)}));
import {useCreatorPageMediaUpload} from '../useCreatorPageMediaUpload';
const page='page',event='event',scope={userId:'user',isCurrent:()=>current},guard={check:jest.fn(),assertCurrent:jest.fn()};let current=true,stored:any[]=[],api:ReturnType<typeof useCreatorPageMediaUpload>,tree:ReactTestRenderer;
const attempt:any={mediaId:'original',pageId:page,eventId:event,userId:'user',purpose:'image'},receipt=()=>({objectName:'event/private-original.jpg',readyAt:'time',objectPresent:true,attached:false,abandonedAt:null});
function Harness({saved,enabled=true}:{saved?:string;enabled?:boolean}){api=useCreatorPageMediaUpload(enabled?page:undefined,enabled?event:undefined,enabled?scope:undefined,enabled?guard:undefined,mockReady,mockDiscard,saved?[saved]:[],'image');return null;}
const flush=async()=>{for(let i=0;i<35;i++)await Promise.resolve();};const mount=async(saved?:string,enabled=true)=>{await act(async()=>{tree=create(<Harness saved={saved} enabled={enabled}/>);await flush();});};
beforeEach(()=>{jest.resetAllMocks();current=true;stored=[];guard.check.mockResolvedValue(undefined);mockRead.mockImplementation(async()=>stored);mockPrepare.mockImplementation(async()=>{stored=[attempt];return{attempt,created:true};});mockGet.mockResolvedValue(receipt());mockReserve.mockResolvedValue(receipt());mockClear.mockImplementation(async()=>{stored=[];return true;});mockAbandon.mockResolvedValue({...receipt(),abandonedAt:'time'});mockStart.mockImplementation(()=>({done:Promise.resolve(receipt()),cancel:mockCancel}));});
afterEach(()=>{if(tree)act(()=>tree.unmount());});

it('body upload prepares image purpose and returns to the ordered batch without inserting twice',async()=>{await mount();let ref:any;await act(async()=>{ref=await api.upload('file:///photo.jpg');});expect(mockPrepare).toHaveBeenCalledWith(page,event,'image','image/jpeg','file:///photo.jpg',scope);expect(ref).toBe('event/private-original.jpg');expect(mockReady).not.toHaveBeenCalled();expect(api.attempts).toEqual([attempt]);});
it('explicit recovery adds only the original photo reference without preparing another attempt',async()=>{stored=[attempt];await mount();await act(async()=>{await api.retry(attempt);});expect(mockPrepare).not.toHaveBeenCalled();expect(mockReady).toHaveBeenCalledWith('event/private-original.jpg');});
it('body recovery does not offer pending covers as photos',async()=>{stored=[attempt,{...attempt,mediaId:'cover',purpose:'cover'}];await mount();expect(api.attempts).toEqual([attempt]);});
it('unknown attachment keeps the original photo file and recovery record',async()=>{stored=[attempt];mockGet.mockRejectedValue(Error('unavailable'));await mount('event/private-original.jpg');expect(mockClear).not.toHaveBeenCalled();expect(api.error).toContain('local upload');expect(api.attempts).toEqual([attempt]);});
it('confirmed saved body photo attachment clears its local attempt',async()=>{stored=[attempt];mockGet.mockResolvedValue({...receipt(),attached:true});await mount('event/private-original.jpg');expect(mockClear).toHaveBeenCalledWith(attempt,scope);expect(api.attempts).toEqual([]);});
it('a newer full body can reject recovered insertion without losing the saved attempt',async()=>{stored=[attempt];mockReady.mockImplementation(()=>{throw Error('full');});await mount();await act(async()=>{await expect(api.retry(attempt)).rejects.toThrow('full');});expect(mockClear).not.toHaveBeenCalled();expect(api.attempts).toEqual([attempt]);expect(api.error).toContain('saved attempt');});
