import React from 'react';
import {act,create} from 'react-test-renderer';
import {usePlanInvitation} from '../usePlanInvitation';
const mockAuth=jest.fn(),mockRead=jest.fn(),mockWrite=jest.fn(),mockMember=jest.fn(),mockInvalidate=jest.fn();
let mockFocus:any,mockBlur:any;
jest.mock('expo-router',()=>({useFocusEffect:(cb:any)=>require('react').useEffect(()=>{mockFocus=cb;mockBlur=cb();return()=>mockBlur?.();},[cb])}));
jest.mock('@tanstack/react-query',()=>({useQueryClient:()=>({invalidateQueries:mockInvalidate})}));
jest.mock('../../lib/logger',()=>({logError:jest.fn()}));
jest.mock('../../lib/supabase',()=>({supabase:{auth:{getUser:()=>mockAuth()},from:(table:string)=>{
 let payload:any;const filters:any[]=[],ordering:any[]=[];let limit:any;const q:any={select:()=>q,eq:(...args:any[])=>{filters.push(args);return q;},order:(...args:any[])=>{ordering.push(args);return q;},limit:(n:number)=>{limit=n;return q;},update:(p:any)=>{payload=p;return q;},maybeSingle:()=>table==='event_members'?mockMember(filters):payload?mockWrite(payload,filters):mockRead(filters,ordering,limit)};return q;
}}}));
const invite={id:'invite',event_id:'plan',recipient_id:'alice',status:'pending'};
const result=(data:any)=>({data,error:null});const auth=()=>({data:{user:{id:'alice'}},error:null});
const deferred=()=>{let resolve!:(x:any)=>void;const promise=new Promise<any>(r=>resolve=r);return{promise,resolve};};
let tree:ReturnType<typeof create>|undefined;
async function mount(){let current!:ReturnType<typeof usePlanInvitation>,epoch=1,allowed=true;
 function Harness(){const captured=epoch;current=usePlanInvitation({eventId:'plan',viewerId:'alice',epoch,isCurrent:()=>epoch===captured,canRespond:()=>allowed});return null;}
 await act(async()=>{tree=create(<Harness/>);});return{get current(){return current;},retire:()=>epoch++,deny:()=>{allowed=false;},rerender:async()=>{epoch++;await act(async()=>tree!.update(<Harness/>));},blur:()=>act(()=>mockBlur?.()),focus:async()=>{await act(async()=>{mockBlur=mockFocus();});}};
}
beforeEach(()=>{mockAuth.mockReset().mockResolvedValue(auth());mockRead.mockReset().mockResolvedValue(result(invite));mockMember.mockReset().mockResolvedValue(result({event_id:'plan',user_id:'alice',status:'joined'}));mockWrite.mockReset().mockImplementation(async(payload)=>result({...invite,status:payload.status}));mockInvalidate.mockReset().mockResolvedValue(undefined);});
afterEach(()=>{if(tree)act(()=>tree!.unmount());tree=undefined;});
it('chooses one own pending invitation deterministically across multiple senders',async()=>{const h=await mount();expect(mockRead).toHaveBeenCalledWith([['event_id','plan'],['recipient_id','alice'],['status','pending']],[['created_at',{ascending:true}],['id',{ascending:true}]],1);expect(h.current.invitation).toEqual(invite);});
it('does not write or read membership when preparing the joining handoff',async()=>{const h=await mount();expect(h.current.prepareAcceptance()).toEqual(expect.any(Function));expect(mockWrite).not.toHaveBeenCalled();expect(mockMember).not.toHaveBeenCalled();});
it('acknowledges acceptance only after an exact joined membership read',async()=>{const h=await mount();const complete=h.current.prepareAcceptance()!;await act(async()=>{complete();complete();});expect(mockMember).toHaveBeenCalledWith([['event_id','plan'],['user_id','alice']]);expect(mockWrite).toHaveBeenCalledTimes(1);expect(mockWrite.mock.calls[0][0].status).toBe('accepted');expect(h.current.invitation).toBeNull();});
it.each([null,{event_id:'plan',user_id:'alice',status:'left'},{event_id:'other',user_id:'alice',status:'joined'},{event_id:'plan',user_id:'other',status:'joined'}])('does not accept from invalid membership %p',async(data)=>{mockMember.mockResolvedValue(result(data));const h=await mount();await act(async()=>h.current.prepareAcceptance()!());expect(mockWrite).not.toHaveBeenCalled();expect(h.current.attempt?.phase).toBe('failed');});
it('keeps a failed membership read retryable without admission writes',async()=>{mockMember.mockRejectedValueOnce(new Error('offline'));const h=await mount();await act(async()=>h.current.prepareAcceptance()!());expect(mockWrite).not.toHaveBeenCalled();await act(async()=>h.current.retry());expect(mockWrite).toHaveBeenCalledTimes(1);expect(mockWrite.mock.calls[0][0].status).toBe('accepted');});
it('declines only the exact pending invitation for this recipient',async()=>{const h=await mount();await act(async()=>h.current.decline());expect(mockMember).not.toHaveBeenCalled();expect(mockWrite).toHaveBeenCalledWith(expect.objectContaining({status:'declined'}),[['id','invite'],['event_id','plan'],['recipient_id','alice'],['status','pending']]);});
it('locks before authentication for repeated replies',async()=>{const h=await mount(),p=deferred();mockAuth.mockReturnValueOnce(p.promise);let work!:Promise<void>;act(()=>{work=h.current.decline();void h.current.decline();});expect(h.current.busy).toBe(true);await act(async()=>{p.resolve(auth());await work;});expect(mockWrite).toHaveBeenCalledTimes(1);});
it('retains the original declined reply after a known rejection',async()=>{mockWrite.mockResolvedValueOnce({data:null,error:{code:'42501'}});const h=await mount();await act(async()=>h.current.decline());expect(h.current.invitation).toEqual(invite);expect(h.current.prepareAcceptance()).toBeNull();await act(async()=>h.current.retry());expect(mockWrite.mock.calls.map(x=>x[0].status)).toEqual(['declined','declined']);});
it.each([null,[],{...invite,id:'other',status:'declined'},{...invite,recipient_id:'other',status:'declined'},{...invite,status:'accepted'}])('keeps uncertain reply receipt %p from enabling resubmission',async(data)=>{mockWrite.mockResolvedValue(result(data));const h=await mount();await act(async()=>h.current.decline());await act(async()=>h.current.retry());await act(async()=>h.current.decline());expect(mockWrite).toHaveBeenCalledTimes(1);expect(h.current.attempt?.phase).toBe('unknown');});
it('checks the exact invitation after a lost reply, without another write',async()=>{mockWrite.mockRejectedValue(new Error('lost'));const h=await mount();await act(async()=>h.current.decline());mockRead.mockResolvedValue(result({...invite,status:'declined'}));await act(async()=>h.current.refresh());expect(mockRead.mock.calls[1][0]).toEqual([['event_id','plan'],['recipient_id','alice'],['id','invite']]);expect(mockWrite).toHaveBeenCalledTimes(1);expect(h.current.attempt).toBeNull();expect(h.current.invitation).toBeNull();});
it('keeps a still-pending fresh read uncertain',async()=>{mockWrite.mockResolvedValue(result(null));const h=await mount();await act(async()=>h.current.decline());await act(async()=>h.current.refresh());expect(h.current.attempt?.phase).toBe('unknown');expect(h.current.error).toContain('still can’t confirm');});
it('does not treat missing invitation during checking as a saved reply',async()=>{mockWrite.mockResolvedValue(result(null));const h=await mount();await act(async()=>h.current.decline());mockRead.mockResolvedValue(result(null));await act(async()=>h.current.refresh());expect(h.current.ready).toBe(false);expect(h.current.attempt?.phase).toBe('unknown');});
it('respects an opposite terminal response instead of overwriting it',async()=>{mockWrite.mockResolvedValue(result(null));const h=await mount();await act(async()=>h.current.decline());mockRead.mockResolvedValue(result({...invite,status:'accepted'}));await act(async()=>h.current.refresh());expect(h.current.invitation).toBeNull();expect(h.current.attempt).toBeNull();expect(h.current.error).toBe('This invitation was already answered.');expect(mockWrite).toHaveBeenCalledTimes(1);});
it('distinguishes a read rejection from no invitation',async()=>{mockRead.mockRejectedValue(new Error('offline'));const h=await mount();expect(h.current.ready).toBe(false);expect(h.current.error).toContain('Couldn’t check');expect(h.current.prepareAcceptance()).toBeNull();});
it('rejects an unrelated read row',async()=>{mockRead.mockResolvedValue(result({...invite,recipient_id:'other'}));const h=await mount();expect(h.current.ready).toBe(false);expect(h.current.invitation).toBeNull();});
it('ignores an old read after account replacement',async()=>{const h=await mount(),p=deferred();mockRead.mockReturnValueOnce(p.promise);let read!:Promise<void>;await act(async()=>{read=h.current.refresh();});expect(mockRead).toHaveBeenCalledTimes(2);await h.rerender();await act(async()=>{p.resolve(result(null));await read;});expect(h.current.invitation).toEqual(invite);});
it('does not dispatch when eligibility retires during authentication',async()=>{const h=await mount(),p=deferred();mockAuth.mockReturnValueOnce(p.promise);let work!:Promise<void>;act(()=>{work=h.current.decline();});h.deny();await act(async()=>{p.resolve(auth());await work;});expect(mockWrite).not.toHaveBeenCalled();});
it('does not dispatch acceptance from an abandoned visit',async()=>{const h=await mount(),complete=h.current.prepareAcceptance()!;h.blur();await h.focus();await act(async()=>complete());expect(mockWrite).not.toHaveBeenCalled();});
it('does not dispatch after account retirement during membership checking',async()=>{const h=await mount(),p=deferred();mockMember.mockReturnValueOnce(p.promise);await act(async()=>h.current.prepareAcceptance()!());h.retire();await act(async()=>p.resolve(result({event_id:'plan',user_id:'alice',status:'joined'})));expect(mockWrite).not.toHaveBeenCalled();});
it('keeps the unknown reply on a later visit to the same mounted route',async()=>{const h=await mount(),p=deferred();mockWrite.mockReturnValueOnce(p.promise);let work!:Promise<void>;await act(async()=>{work=h.current.decline();});h.blur();await act(async()=>{p.resolve(result(null));await work;});await h.focus();expect(h.current.attempt?.phase).toBe('unknown');expect(mockWrite).toHaveBeenCalledTimes(1);});

it('does not prepare joining after its account retires',async()=>{const h=await mount();h.retire();expect(h.current.prepareAcceptance()).toBeNull();expect(mockWrite).not.toHaveBeenCalled();});

it('allows keeping an invitation only after a known rejected decline',async()=>{mockWrite.mockResolvedValueOnce({data:null,error:{code:'42501'}});const h=await mount();await act(async()=>h.current.decline());act(()=>h.current.keepInvitation());expect(h.current.attempt).toBeNull();expect(h.current.invitation).toEqual(invite);expect(h.current.prepareAcceptance()).toEqual(expect.any(Function));expect(mockWrite).toHaveBeenCalledTimes(1);});
it('cannot discard an uncertain decline as though it failed',async()=>{mockWrite.mockResolvedValue(result(null));const h=await mount();await act(async()=>h.current.decline());act(()=>h.current.keepInvitation());expect(h.current.attempt?.phase).toBe('unknown');});
