-- Durable audience consent provenance and provider suppression handling.
-- The service-only outbox stores normalized raw email because its worker must
-- address the provider. Evidence, suppression, and operational receipts store
-- hashes or identifiers only, never raw email.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS marketing_opt_in_source text,
  ADD COLUMN IF NOT EXISTS marketing_opt_in_at timestamptz,
  ADD COLUMN IF NOT EXISTS marketing_consent_revision bigint NOT NULL DEFAULT 0;

CREATE OR REPLACE FUNCTION public.audience_normalize_email(p_email text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT NULLIF(lower(btrim(p_email)), '')
$$;

CREATE TABLE IF NOT EXISTS public.audience_consent_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  email_hash text CHECK (email_hash ~ '^[0-9a-f]{64}$'),
  email_consent boolean NOT NULL,
  marketing_opt_in boolean NOT NULL,
  consent_source text NOT NULL,
  consent_revision bigint NOT NULL DEFAULT 1 CHECK (consent_revision > 0),
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audience_consent_events_profile_idx
  ON public.audience_consent_events (profile_id, occurred_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.audience_sync_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  normalized_email text NOT NULL UNIQUE,
  profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  desired_marketing_opt_in boolean NOT NULL,
  revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'delivered', 'failed', 'cancelled')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  terminal_at timestamptz,
  purge_after timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audience_sync_outbox_claim_idx
  ON public.audience_sync_outbox (status, available_at, attempts, id)
  WHERE status IN ('pending', 'processing');

CREATE TABLE IF NOT EXISTS public.audience_suppression_events (
  provider_event_id text PRIMARY KEY,
  event_type text NOT NULL CHECK (event_type IN
    ('contact.updated', 'email.bounced', 'email.complained', 'email.suppressed')),
  email_hash text NOT NULL CHECK (email_hash ~ '^[0-9a-f]{64}$'),
  received_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audience_provider_preferences (
  profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  email_hash text NOT NULL CHECK (email_hash ~ '^[0-9a-f]{64}$'),
  unsubscribed boolean NOT NULL,
  local_consent_revision bigint NOT NULL CHECK (local_consent_revision >= 0),
  provider_event_id text,
  confirmed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audience_contact_reconciliation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_event_id text NOT NULL UNIQUE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  normalized_email text NOT NULL,
  email_hash text NOT NULL CHECK (email_hash ~ '^[0-9a-f]{64}$'),
  provider_contact_id text NOT NULL,
  expected_audience_id text NOT NULL,
  local_consent_revision bigint NOT NULL CHECK (local_consent_revision >= 0),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'delivered', 'cancelled', 'failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  last_error text,
  terminal_at timestamptz,
  purge_after timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audience_contact_reconciliation_claim_idx
  ON public.audience_contact_reconciliation(status, available_at, id)
  WHERE status IN ('pending', 'processing');

CREATE TABLE IF NOT EXISTS public.audience_webhook_quarantine (
  provider_event_id text PRIMARY KEY,
  event_type text NOT NULL,
  email_hash text CHECK (email_hash ~ '^[0-9a-f]{64}$'),
  provider_message_id text,
  application_tag text,
  hard_eligible boolean NOT NULL DEFAULT false,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'expired')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz NOT NULL DEFAULT now(),
  last_checked_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT now() + interval '30 days'
);

ALTER TABLE public.audience_consent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_sync_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_suppression_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_provider_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_contact_reconciliation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audience_webhook_quarantine ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.audience_consent_events, public.audience_sync_outbox,
  public.audience_suppression_events, public.audience_provider_preferences,
  public.audience_contact_reconciliation, public.audience_webhook_quarantine
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.audience_consent_events, public.audience_sync_outbox,
  public.audience_suppression_events, public.audience_provider_preferences,
  public.audience_contact_reconciliation, public.audience_webhook_quarantine
  TO service_role;

CREATE OR REPLACE FUNCTION public.enqueue_audience_sync_for_email(
  p_email text,
  p_marketing_opt_in boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(p_email);
  v_desired boolean := coalesce(p_marketing_opt_in, false);
BEGIN
  IF v_email IS NULL THEN RETURN; END IF;
  IF EXISTS (
    SELECT 1 FROM public.audience_suppression_events
     WHERE email_hash = encode(digest(v_email, 'sha256'), 'hex')
  ) THEN
    v_desired := false;
  END IF;
  INSERT INTO public.audience_sync_outbox
    (normalized_email, desired_marketing_opt_in, status, available_at, updated_at)
  VALUES (v_email, v_desired, 'pending', now(), now())
  ON CONFLICT (normalized_email) DO UPDATE
    SET desired_marketing_opt_in = EXCLUDED.desired_marketing_opt_in,
        revision = public.audience_sync_outbox.revision +
          CASE WHEN public.audience_sync_outbox.desired_marketing_opt_in
                    IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
                    OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
               THEN 1 ELSE 0 END,
        status = CASE
          WHEN public.audience_sync_outbox.desired_marketing_opt_in
                 IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
               AND public.audience_sync_outbox.status = 'processing'
            THEN 'processing'
          WHEN public.audience_sync_outbox.desired_marketing_opt_in
                 IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
               OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
            THEN 'pending'
          ELSE public.audience_sync_outbox.status END,
        attempts = CASE WHEN
          (public.audience_sync_outbox.desired_marketing_opt_in
             IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
           AND public.audience_sync_outbox.status <> 'processing')
          OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
          THEN 0 ELSE public.audience_sync_outbox.attempts END,
        available_at = CASE WHEN
          (public.audience_sync_outbox.desired_marketing_opt_in
             IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
           AND public.audience_sync_outbox.status <> 'processing')
          OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
          THEN now() ELSE public.audience_sync_outbox.available_at END,
        claimed_at = CASE WHEN
          (public.audience_sync_outbox.desired_marketing_opt_in
             IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
           AND public.audience_sync_outbox.status <> 'processing')
          OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
          THEN NULL ELSE public.audience_sync_outbox.claimed_at END,
        delivered_at = CASE WHEN
          (public.audience_sync_outbox.desired_marketing_opt_in
             IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
           AND public.audience_sync_outbox.status <> 'processing')
          OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
          THEN NULL ELSE public.audience_sync_outbox.delivered_at END,
        last_error = CASE WHEN
          (public.audience_sync_outbox.desired_marketing_opt_in
             IS DISTINCT FROM EXCLUDED.desired_marketing_opt_in
           AND public.audience_sync_outbox.status <> 'processing')
          OR public.audience_sync_outbox.status IN ('failed', 'cancelled')
          THEN NULL ELSE public.audience_sync_outbox.last_error END,
        updated_at = now();
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_profile_consent_evidence()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_changed boolean;
  v_source text;
  v_suppressed boolean := false;
BEGIN
  IF public.audience_normalize_email(NEW.email) IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.audience_suppression_events
       WHERE email_hash = encode(digest(public.audience_normalize_email(NEW.email), 'sha256'), 'hex')
    ) INTO v_suppressed;
  END IF;
  IF v_suppressed AND coalesce(NEW.marketing_opt_in, false) THEN
    NEW.marketing_opt_in := false;
  END IF;
  IF TG_OP = 'INSERT' THEN
    v_changed := true;
  ELSE
    v_changed := OLD.email IS DISTINCT FROM NEW.email
      OR OLD.marketing_opt_in IS DISTINCT FROM NEW.marketing_opt_in;
  END IF;
  IF NOT v_changed THEN
    NEW.marketing_opt_in_source := OLD.marketing_opt_in_source;
    RETURN NEW;
  END IF;
  v_source := CASE
    WHEN v_suppressed THEN 'provider_suppression'
    WHEN TG_OP = 'INSERT' THEN 'profile_insert'
    ELSE 'profile_change'
  END;
  NEW.marketing_opt_in_source := v_source;
  IF TG_OP = 'INSERT' THEN
    NEW.marketing_opt_in_at := now();
  ELSIF OLD.marketing_opt_in IS DISTINCT FROM NEW.marketing_opt_in THEN
    NEW.marketing_opt_in_at := now();
  END IF;
  INSERT INTO public.audience_consent_events
    (profile_id, email_hash, email_consent, marketing_opt_in, consent_source)
  VALUES (NEW.id, encode(digest(public.audience_normalize_email(NEW.email), 'sha256'), 'hex'), NEW.email IS NOT NULL,
          coalesce(NEW.marketing_opt_in, false), v_source);
  IF TG_OP = 'UPDATE' THEN
    IF OLD.email IS DISTINCT FROM NEW.email THEN
      PERFORM public.enqueue_audience_sync_for_email(OLD.email, false);
    END IF;
  END IF;
  PERFORM public.enqueue_audience_sync_for_email(NEW.email, coalesce(NEW.marketing_opt_in, false));
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS profile_consent_evidence_trigger ON public.profiles;
CREATE TRIGGER profile_consent_evidence_trigger
BEFORE INSERT OR UPDATE OF email, marketing_opt_in, marketing_opt_in_source
ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.record_profile_consent_evidence();

CREATE OR REPLACE FUNCTION public.record_audience_suppression(
  p_provider_event_id text,
  p_event_type text,
  p_email text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(p_email);
  v_hash text;
  v_inserted boolean;
BEGIN
  IF nullif(btrim(p_provider_event_id), '') IS NULL OR v_email IS NULL THEN
    RAISE EXCEPTION 'provider event id and email are required' USING ERRCODE = '22023';
  END IF;
  v_hash := encode(digest(v_email, 'sha256'), 'hex');
  INSERT INTO public.audience_suppression_events(provider_event_id, event_type, email_hash)
  VALUES (p_provider_event_id, p_event_type, v_hash)
  ON CONFLICT (provider_event_id) DO NOTHING;
  v_inserted := FOUND;
  IF v_inserted THEN
    PERFORM public.enqueue_audience_sync_for_email(v_email, false);
    UPDATE public.profiles
       SET marketing_opt_in = false,
           marketing_opt_in_source = 'provider_suppression'
     WHERE public.audience_normalize_email(email) = v_email
       AND marketing_opt_in IS DISTINCT FROM false;
  END IF;
  RETURN v_inserted;
END;
$function$;

CREATE OR REPLACE FUNCTION public.enqueue_current_profile_audience_sync(p_profile_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_profile public.profiles%ROWTYPE;
BEGIN
  SELECT * INTO v_profile FROM public.profiles WHERE id = p_profile_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'profile not found' USING ERRCODE = '22023'; END IF;
  PERFORM public.enqueue_audience_sync_for_profile(
    v_profile.id, v_profile.email, v_profile.marketing_opt_in
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.claim_audience_sync_jobs(
  p_batch_size integer DEFAULT 10,
  p_lease_seconds integer DEFAULT 600
)
RETURNS SETOF public.audience_sync_outbox
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_limit integer := least(greatest(coalesce(p_batch_size, 10), 1), 10);
  v_lease integer := least(greatest(coalesce(p_lease_seconds, 600), 300), 3600);
BEGIN
  RETURN QUERY
  WITH chosen AS (
    SELECT id FROM public.audience_sync_outbox
    WHERE (status = 'pending' AND available_at <= now())
       OR (status = 'processing' AND claimed_at < now() - make_interval(secs => v_lease))
    ORDER BY available_at, id
    LIMIT v_limit
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.audience_sync_outbox o
     SET status = 'processing', attempts = o.attempts + 1,
         claimed_at = now(), updated_at = now()
    FROM chosen c WHERE o.id = c.id
  RETURNING o.*;
END;
$function$;

CREATE OR REPLACE FUNCTION public.complete_audience_sync_job(
  p_id bigint,
  p_revision bigint,
  p_outcome text,
  p_confirmed boolean DEFAULT false,
  p_error text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_attempts integer;
  v_current_revision bigint;
  v_status text;
BEGIN
  IF p_outcome NOT IN ('succeeded', 'retryable', 'terminal') THEN
    RAISE EXCEPTION 'invalid audience sync outcome' USING ERRCODE = '22023';
  END IF;
  SELECT revision, status, attempts
    INTO v_current_revision, v_status, v_attempts
    FROM public.audience_sync_outbox
   WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RETURN false; END IF;
  IF v_current_revision IS DISTINCT FROM p_revision THEN
    UPDATE public.audience_sync_outbox
       SET status = 'pending', attempts = 0, available_at = now(),
           claimed_at = NULL, delivered_at = NULL,
           terminal_at = NULL, purge_after = NULL,
           last_error = format('reconcile after stale provider completion revision %s', p_revision),
           updated_at = now()
     WHERE id = p_id;
    RETURN false;
  END IF;
  IF v_status <> 'processing' THEN RETURN false; END IF;
  UPDATE public.audience_sync_outbox
     SET status = CASE WHEN p_outcome = 'succeeded' AND p_confirmed THEN 'delivered'
                       WHEN p_outcome = 'terminal' THEN 'failed' ELSE 'pending' END,
         available_at = CASE WHEN p_outcome = 'retryable'
                             THEN now() + make_interval(secs => least(3600, greatest(30, 30 * (2 ^ least(v_attempts, 7)))))
                             ELSE now() END,
         claimed_at = NULL,
         delivered_at = CASE WHEN p_outcome = 'succeeded' AND p_confirmed THEN now() ELSE NULL END,
         terminal_at = CASE
           WHEN (p_outcome = 'succeeded' AND p_confirmed) OR p_outcome = 'terminal' THEN now()
           ELSE NULL END,
         purge_after = CASE
           WHEN (p_outcome = 'succeeded' AND p_confirmed) OR p_outcome = 'terminal'
             THEN now() + interval '30 days'
           ELSE NULL END,
         last_error = CASE WHEN p_outcome = 'succeeded' AND p_confirmed THEN NULL ELSE p_error END,
         updated_at = now()
   WHERE id = p_id AND revision = p_revision AND status = 'processing';
  RETURN FOUND;
END;
$function$;

-- G0 remediation: metadata mutation stays BEFORE the profile write, while all
-- child-table evidence and queue work runs AFTER the parent row exists.
CREATE OR REPLACE FUNCTION public.profile_consent_metadata_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(NEW.email);
  v_changed boolean;
  v_hard_suppressed boolean := false;
BEGIN
  IF v_email IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.audience_suppression_events
       WHERE email_hash = encode(digest(v_email, 'sha256'), 'hex')
         AND event_type IN ('email.bounced', 'email.complained', 'email.suppressed')
    ) INTO v_hard_suppressed;
  END IF;

  IF TG_OP = 'INSERT' THEN
    v_changed := true;
  ELSE
    v_changed := OLD.email IS DISTINCT FROM NEW.email
      OR OLD.marketing_opt_in IS DISTINCT FROM NEW.marketing_opt_in;
  END IF;

  IF NOT v_changed THEN
    NEW.marketing_opt_in_source := OLD.marketing_opt_in_source;
    NEW.marketing_opt_in_at := OLD.marketing_opt_in_at;
    NEW.marketing_consent_revision := OLD.marketing_consent_revision;
    RETURN NEW;
  END IF;

  IF v_hard_suppressed AND coalesce(NEW.marketing_opt_in, false) THEN
    NEW.marketing_opt_in := false;
    NEW.marketing_opt_in_source := 'provider_hard_suppression';
  ELSIF TG_OP = 'INSERT' THEN
    NEW.marketing_opt_in_source := 'profile_insert';
  ELSE
    NEW.marketing_opt_in_source := 'profile_change';
  END IF;
  NEW.marketing_opt_in_at := now();
  NEW.marketing_consent_revision := CASE
    WHEN TG_OP = 'INSERT' THEN 1
    ELSE OLD.marketing_consent_revision + 1
  END;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.enqueue_audience_sync_for_profile(
  p_profile_id uuid,
  p_email text,
  p_marketing_opt_in boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(p_email);
BEGIN
  IF v_email IS NULL THEN RETURN; END IF;
  PERFORM public.enqueue_audience_sync_for_email(v_email, p_marketing_opt_in);
  UPDATE public.audience_sync_outbox
     SET profile_id = p_profile_id, updated_at = now()
   WHERE normalized_email = v_email;
END;
$function$;

CREATE OR REPLACE FUNCTION public.profile_consent_evidence_enqueue()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_changed boolean;
  v_email text := public.audience_normalize_email(NEW.email);
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_changed := true;
  ELSE
    v_changed := OLD.email IS DISTINCT FROM NEW.email
      OR OLD.marketing_opt_in IS DISTINCT FROM NEW.marketing_opt_in;
  END IF;
  IF NOT v_changed THEN RETURN NEW; END IF;

  INSERT INTO public.audience_consent_events(
    profile_id, email_hash, email_consent, marketing_opt_in,
    consent_source, consent_revision
  ) VALUES (
    NEW.id,
    CASE WHEN v_email IS NULL THEN NULL ELSE encode(digest(v_email, 'sha256'), 'hex') END,
    v_email IS NOT NULL,
    coalesce(NEW.marketing_opt_in, false),
    NEW.marketing_opt_in_source,
    NEW.marketing_consent_revision
  );

  IF TG_OP = 'UPDATE' AND OLD.email IS DISTINCT FROM NEW.email THEN
    PERFORM public.enqueue_audience_sync_for_email(OLD.email, false);
  END IF;
  PERFORM public.enqueue_audience_sync_for_profile(
    NEW.id, NEW.email, coalesce(NEW.marketing_opt_in, false)
  );

  IF coalesce(NEW.marketing_opt_in, false) THEN
    UPDATE public.audience_provider_preferences
       SET unsubscribed = false,
           local_consent_revision = NEW.marketing_consent_revision,
           confirmed_at = now()
     WHERE profile_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS profile_consent_evidence_trigger ON public.profiles;
DROP TRIGGER IF EXISTS profile_consent_metadata_guard_trigger ON public.profiles;
DROP TRIGGER IF EXISTS profile_consent_evidence_enqueue_trigger ON public.profiles;
CREATE TRIGGER profile_consent_metadata_guard_trigger
BEFORE INSERT OR UPDATE OF email, marketing_opt_in, marketing_opt_in_source
ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.profile_consent_metadata_guard();
CREATE TRIGGER profile_consent_evidence_enqueue_trigger
AFTER INSERT OR UPDATE OF email, marketing_opt_in
ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.profile_consent_evidence_enqueue();

-- Ordinary contact.updated events are reversible preferences and must be
-- reconciled against current provider state. They never enter this hard block.
CREATE OR REPLACE FUNCTION public.record_audience_suppression(
  p_provider_event_id text,
  p_event_type text,
  p_email text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(p_email);
  v_inserted boolean;
BEGIN
  IF p_event_type NOT IN ('email.bounced', 'email.complained', 'email.suppressed') THEN
    RAISE EXCEPTION 'event is not a hard suppression' USING ERRCODE = '22023';
  END IF;
  IF nullif(btrim(p_provider_event_id), '') IS NULL OR v_email IS NULL THEN
    RAISE EXCEPTION 'provider event id and email are required' USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.audience_suppression_events(provider_event_id, event_type, email_hash)
  VALUES (p_provider_event_id, p_event_type, encode(digest(v_email, 'sha256'), 'hex'))
  ON CONFLICT (provider_event_id) DO NOTHING;
  v_inserted := FOUND;
  IF v_inserted THEN
    UPDATE public.profiles
       SET marketing_opt_in = false,
           marketing_opt_in_source = 'provider_hard_suppression'
     WHERE public.audience_normalize_email(email) = v_email
       AND marketing_opt_in IS DISTINCT FROM false;
    PERFORM public.enqueue_audience_sync_for_email(v_email, false);
  END IF;
  RETURN v_inserted;
END;
$function$;

CREATE OR REPLACE FUNCTION public.quarantine_audience_webhook(
  p_provider_event_id text,
  p_event_type text,
  p_email text,
  p_reason text,
  p_provider_message_id text DEFAULT NULL,
  p_application_tag text DEFAULT NULL,
  p_hard_eligible boolean DEFAULT false
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE v_email text := public.audience_normalize_email(p_email);
BEGIN
  INSERT INTO public.audience_webhook_quarantine(
    provider_event_id, event_type, email_hash, reason,
    provider_message_id, application_tag, hard_eligible
  ) VALUES (
    p_provider_event_id, p_event_type,
    CASE WHEN v_email IS NULL THEN NULL ELSE encode(digest(v_email, 'sha256'), 'hex') END,
    left(coalesce(nullif(btrim(p_reason), ''), 'unscoped provider event'), 300),
    nullif(btrim(p_provider_message_id), ''), nullif(btrim(p_application_tag), ''),
    coalesce(p_hard_eligible, false)
  ) ON CONFLICT (provider_event_id) DO NOTHING;
  RETURN 'quarantined';
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_audience_provider_event(
  p_provider_event_id text,
  p_event_type text,
  p_email text,
  p_provider_contact_id text DEFAULT NULL,
  p_audience_id text DEFAULT NULL,
  p_expected_audience_id text DEFAULT NULL,
  p_provider_message_id text DEFAULT NULL,
  p_application_tag text DEFAULT NULL,
  p_permanent_bounce boolean DEFAULT false
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := public.audience_normalize_email(p_email);
  v_profile public.profiles%ROWTYPE;
  v_message_owned boolean := false;
  v_mode text;
  v_profile_count integer;
BEGIN
  IF nullif(btrim(p_provider_event_id), '') IS NULL OR v_email IS NULL THEN
    RAISE EXCEPTION 'provider event id and email are required' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (SELECT 1 FROM public.audience_webhook_quarantine WHERE provider_event_id = p_provider_event_id)
     OR EXISTS (SELECT 1 FROM public.audience_suppression_events WHERE provider_event_id = p_provider_event_id)
     OR EXISTS (SELECT 1 FROM public.audience_contact_reconciliation WHERE provider_event_id = p_provider_event_id) THEN
    RETURN 'duplicate';
  END IF;
  SELECT activation_mode INTO v_mode FROM public.delivery_runtime_config WHERE singleton;
  IF v_mode IS NULL THEN v_mode := 'quarantined'; END IF;

  IF p_event_type = 'contact.updated' THEN
    IF nullif(btrim(p_provider_contact_id), '') IS NULL
       OR nullif(btrim(p_expected_audience_id), '') IS NULL
       OR p_audience_id IS DISTINCT FROM p_expected_audience_id THEN
      RETURN public.quarantine_audience_webhook(
        p_provider_event_id, p_event_type, v_email, 'contact is not scoped to the configured WashedUp audience'
      );
    END IF;
    SELECT * INTO v_profile FROM public.profiles
     WHERE public.audience_normalize_email(email) = v_email;
    IF NOT FOUND THEN
      RETURN public.quarantine_audience_webhook(
        p_provider_event_id, p_event_type, v_email, 'contact does not resolve to one WashedUp profile'
      );
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.profiles p
       WHERE public.audience_normalize_email(p.email) = v_email AND p.id <> v_profile.id
    ) THEN
      RETURN public.quarantine_audience_webhook(
        p_provider_event_id, p_event_type, v_email, 'contact resolves to multiple WashedUp profiles'
      );
    END IF;
    INSERT INTO public.audience_contact_reconciliation(
      provider_event_id, profile_id, normalized_email, email_hash,
      provider_contact_id, expected_audience_id, local_consent_revision
    ) VALUES (
      p_provider_event_id, v_profile.id, v_email, encode(digest(v_email, 'sha256'), 'hex'),
      p_provider_contact_id, p_expected_audience_id, v_profile.marketing_consent_revision
    );
    RETURN 'reconciliation_queued';
  END IF;

  IF p_event_type NOT IN ('email.bounced', 'email.complained', 'email.suppressed') THEN
    RETURN public.quarantine_audience_webhook(
      p_provider_event_id, p_event_type, v_email, 'unsupported provider event type'
    );
  END IF;
  IF p_event_type = 'email.bounced' AND NOT p_permanent_bounce THEN
    RETURN public.quarantine_audience_webhook(
      p_provider_event_id, p_event_type, v_email, 'bounce was not classified permanent',
      p_provider_message_id, p_application_tag, false
    );
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.transactional_email_jobs
     WHERE provider_message_id = nullif(btrim(p_provider_message_id), '')
  ) INTO v_message_owned;
  IF NOT v_message_owned
     AND EXISTS (
       SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'ticket_orders'
          AND column_name = 'confirmation_email_id'
     )
     AND nullif(btrim(p_provider_message_id), '') IS NOT NULL THEN
    EXECUTE 'select exists (select 1 from public.ticket_orders where confirmation_email_id = $1)'
      INTO v_message_owned USING p_provider_message_id;
  END IF;
  IF NOT v_message_owned AND p_application_tag IS DISTINCT FROM 'washedup' THEN
    RETURN public.quarantine_audience_webhook(
      p_provider_event_id, p_event_type, v_email,
      'email event has no WashedUp send receipt or application tag',
      p_provider_message_id, p_application_tag,
      p_event_type IN ('email.complained', 'email.suppressed')
        OR (p_event_type = 'email.bounced' AND p_permanent_bounce)
    );
  END IF;
  SELECT count(*) INTO v_profile_count FROM public.profiles p
   WHERE public.audience_normalize_email(p.email) = v_email;
  IF v_mode = 'quarantined'
     OR (v_mode = 'seed_only' AND (
       v_profile_count <> 1 OR NOT EXISTS (
         SELECT 1 FROM public.delivery_seed_profiles s
          JOIN public.profiles p ON p.id = s.profile_id
         WHERE public.audience_normalize_email(p.email) = v_email
       )
     )) THEN
    RETURN public.quarantine_audience_webhook(
      p_provider_event_id, p_event_type, v_email,
      'provider event is outside the current delivery activation scope',
      p_provider_message_id, p_application_tag, true
    );
  END IF;
  PERFORM public.record_audience_suppression(p_provider_event_id, p_event_type, v_email);
  RETURN 'hard_suppression_recorded';
END;
$function$;

CREATE OR REPLACE FUNCTION public.reconcile_quarantined_audience_events(
  p_batch_size integer DEFAULT 10
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_limit integer := least(greatest(coalesce(p_batch_size, 10), 1), 50);
  v_mode text;
  v_row public.audience_webhook_quarantine%ROWTYPE;
  v_profile public.profiles%ROWTYPE;
  v_profile_count integer;
  v_owned boolean;
  v_resolved integer := 0;
BEGIN
  SELECT activation_mode INTO v_mode FROM public.delivery_runtime_config WHERE singleton;
  IF v_mode IS NULL OR v_mode = 'quarantined' THEN RETURN 0; END IF;
  FOR v_row IN
    SELECT * FROM public.audience_webhook_quarantine
     WHERE status = 'pending' AND available_at <= now()
       AND hard_eligible
       AND event_type IN ('email.bounced', 'email.complained', 'email.suppressed')
     ORDER BY received_at LIMIT v_limit FOR UPDATE SKIP LOCKED
  LOOP
    v_owned := coalesce(v_row.application_tag = 'washedup', false);
    IF NOT v_owned AND v_row.provider_message_id IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM public.transactional_email_jobs
         WHERE provider_message_id = v_row.provider_message_id
      ) INTO v_owned;
      IF NOT v_owned AND EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'ticket_orders'
           AND column_name = 'confirmation_email_id'
      ) THEN
        EXECUTE 'select exists (select 1 from public.ticket_orders where confirmation_email_id = $1)'
          INTO v_owned USING v_row.provider_message_id;
      END IF;
    END IF;
    SELECT count(*) INTO v_profile_count FROM public.profiles p
     WHERE encode(digest(public.audience_normalize_email(p.email), 'sha256'), 'hex') = v_row.email_hash;
    SELECT * INTO v_profile FROM public.profiles p
     WHERE encode(digest(public.audience_normalize_email(p.email), 'sha256'), 'hex') = v_row.email_hash
     ORDER BY p.id LIMIT 1;
    IF v_owned AND v_profile_count = 1 AND v_profile.id IS NOT NULL
       AND (v_mode = 'live' OR EXISTS (
         SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = v_profile.id
       )) THEN
      PERFORM public.record_audience_suppression(
        v_row.provider_event_id, v_row.event_type, v_profile.email
      );
      UPDATE public.audience_webhook_quarantine
         SET status = 'resolved', last_checked_at = now(), reason = 'WashedUp send receipt reconciled'
       WHERE provider_event_id = v_row.provider_event_id;
      v_resolved := v_resolved + 1;
    ELSE
      UPDATE public.audience_webhook_quarantine
         SET attempts = attempts + 1,
             last_checked_at = now(),
             available_at = now() + interval '1 hour',
             status = CASE WHEN expires_at <= now() THEN 'expired' ELSE status END
       WHERE provider_event_id = v_row.provider_event_id;
    END IF;
  END LOOP;
  RETURN v_resolved;
END;
$function$;

CREATE OR REPLACE FUNCTION public.claim_audience_contact_reconciliations(
  p_batch_size integer DEFAULT 10,
  p_lease_seconds integer DEFAULT 600
)
RETURNS SETOF public.audience_contact_reconciliation
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_limit integer := least(greatest(coalesce(p_batch_size, 10), 1), 10);
  v_lease integer := least(greatest(coalesce(p_lease_seconds, 600), 300), 3600);
  v_mode text;
BEGIN
  SELECT activation_mode INTO v_mode FROM public.delivery_runtime_config WHERE singleton;
  IF v_mode IS NULL OR v_mode = 'quarantined' THEN RETURN; END IF;
  RETURN QUERY
  WITH chosen AS (
    SELECT r.id FROM public.audience_contact_reconciliation r
     WHERE ((r.status = 'pending' AND r.available_at <= now())
         OR (r.status = 'processing' AND r.claimed_at < now() - make_interval(secs => v_lease)))
       AND (v_mode = 'live' OR EXISTS (
         SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = r.profile_id
       ))
     ORDER BY r.available_at, r.id
     LIMIT v_limit FOR UPDATE SKIP LOCKED
  )
  UPDATE public.audience_contact_reconciliation r
     SET status = 'processing', attempts = r.attempts + 1,
         claimed_at = now(), updated_at = now()
    FROM chosen c WHERE r.id = c.id
  RETURNING r.*;
END;
$function$;

CREATE OR REPLACE FUNCTION public.complete_audience_contact_reconciliation(
  p_id bigint,
  p_provider_unsubscribed boolean,
  p_confirmed_audience_id text,
  p_confirmed boolean DEFAULT false,
  p_error text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_job public.audience_contact_reconciliation%ROWTYPE;
  v_current_revision bigint;
BEGIN
  SELECT * INTO v_job FROM public.audience_contact_reconciliation WHERE id = p_id FOR UPDATE;
  IF NOT FOUND OR v_job.status <> 'processing' THEN RETURN false; END IF;
  IF NOT p_confirmed OR p_confirmed_audience_id IS DISTINCT FROM v_job.expected_audience_id THEN
    UPDATE public.audience_contact_reconciliation
       SET status = 'pending', claimed_at = NULL,
           available_at = now() + interval '5 minutes',
           last_error = left(coalesce(p_error, 'provider state was not confirmed'), 500), updated_at = now()
     WHERE id = p_id;
    RETURN false;
  END IF;
  SELECT marketing_consent_revision INTO v_current_revision
    FROM public.profiles WHERE id = v_job.profile_id FOR UPDATE;
  IF v_current_revision IS DISTINCT FROM v_job.local_consent_revision
     OR EXISTS (
       SELECT 1 FROM public.audience_sync_outbox o
        WHERE o.profile_id = v_job.profile_id
          AND o.revision > v_job.local_consent_revision
          AND o.status IN ('pending', 'processing')
     ) THEN
    UPDATE public.audience_contact_reconciliation
       SET status = 'cancelled', claimed_at = NULL, terminal_at = now(),
           purge_after = now() + interval '30 days',
           last_error = 'stale provider preference ignored after newer local consent', updated_at = now()
     WHERE id = p_id;
    RETURN false;
  END IF;

  INSERT INTO public.audience_provider_preferences(
    profile_id, email_hash, unsubscribed, local_consent_revision,
    provider_event_id, confirmed_at
  ) VALUES (
    v_job.profile_id, v_job.email_hash, p_provider_unsubscribed,
    v_job.local_consent_revision, v_job.provider_event_id, now()
  ) ON CONFLICT (profile_id) DO UPDATE
    SET email_hash = EXCLUDED.email_hash,
        unsubscribed = EXCLUDED.unsubscribed,
        local_consent_revision = EXCLUDED.local_consent_revision,
        provider_event_id = EXCLUDED.provider_event_id,
        confirmed_at = now();

  IF p_provider_unsubscribed THEN
    UPDATE public.profiles
       SET marketing_opt_in = false,
           marketing_opt_in_source = 'provider_preference'
     WHERE id = v_job.profile_id
       AND marketing_consent_revision = v_job.local_consent_revision
       AND marketing_opt_in IS DISTINCT FROM false;
  END IF;
  UPDATE public.audience_contact_reconciliation
     SET status = 'delivered', claimed_at = NULL, terminal_at = now(),
         purge_after = now() + interval '30 days', last_error = NULL, updated_at = now()
   WHERE id = p_id;
  RETURN true;
END;
$function$;

-- Replace the original claim with activation and seed scoping.
CREATE OR REPLACE FUNCTION public.claim_audience_sync_jobs(
  p_batch_size integer DEFAULT 10,
  p_lease_seconds integer DEFAULT 600
)
RETURNS SETOF public.audience_sync_outbox
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_limit integer := least(greatest(coalesce(p_batch_size, 10), 1), 10);
  v_lease integer := least(greatest(coalesce(p_lease_seconds, 600), 300), 3600);
  v_mode text;
BEGIN
  SELECT activation_mode INTO v_mode FROM public.delivery_runtime_config WHERE singleton;
  IF v_mode IS NULL OR v_mode = 'quarantined' THEN RETURN; END IF;
  RETURN QUERY
  WITH chosen AS (
    SELECT o.id FROM public.audience_sync_outbox o
    WHERE ((o.status = 'pending' AND o.available_at <= now())
       OR (o.status = 'processing' AND o.claimed_at < now() - make_interval(secs => v_lease)))
      AND (
        v_mode = 'live'
        OR EXISTS (SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = o.profile_id)
        OR EXISTS (SELECT 1 FROM public.delivery_seed_jobs s
                    WHERE s.queue_name = 'audience_sync' AND s.job_id = o.id)
      )
    ORDER BY o.available_at, o.id
    LIMIT v_limit FOR UPDATE SKIP LOCKED
  )
  UPDATE public.audience_sync_outbox o
     SET status = 'processing', attempts = o.attempts + 1,
         claimed_at = now(), updated_at = now()
    FROM chosen c WHERE o.id = c.id
  RETURNING o.*;
END;
$function$;

CREATE OR REPLACE FUNCTION public.purge_audience_personal_data(p_batch_size integer DEFAULT 1000)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE v_limit integer; v_deleted integer := 0; v_rows integer;
BEGIN
  IF p_batch_size IS NULL OR p_batch_size < 1 OR p_batch_size > 10000 THEN
    RAISE EXCEPTION 'audience retention batch size must be between 1 and 10000';
  END IF;
  v_limit := p_batch_size;
  WITH doomed AS (
    SELECT id FROM public.audience_sync_outbox
     WHERE purge_after < now() ORDER BY id LIMIT v_limit
  ) DELETE FROM public.audience_sync_outbox o USING doomed d WHERE o.id = d.id;
  GET DIAGNOSTICS v_rows = ROW_COUNT; v_deleted := v_deleted + v_rows;
  WITH doomed AS (
    SELECT id FROM public.audience_contact_reconciliation
     WHERE purge_after < now() ORDER BY id LIMIT greatest(v_limit - v_deleted, 0)
  ) DELETE FROM public.audience_contact_reconciliation r USING doomed d WHERE r.id = d.id;
  GET DIAGNOSTICS v_rows = ROW_COUNT; v_deleted := v_deleted + v_rows;
  DELETE FROM public.audience_webhook_quarantine
   WHERE provider_event_id IN (
     SELECT provider_event_id FROM public.audience_webhook_quarantine
      WHERE expires_at < now() ORDER BY received_at LIMIT greatest(v_limit - v_deleted, 0)
   );
  GET DIAGNOSTICS v_rows = ROW_COUNT; v_deleted := v_deleted + v_rows;
  DELETE FROM public.audience_consent_events
   WHERE id IN (
     SELECT id FROM public.audience_consent_events
      WHERE occurred_at < now() - interval '2 years'
      ORDER BY id LIMIT greatest(v_limit - v_deleted, 0)
   );
  GET DIAGNOSTICS v_rows = ROW_COUNT; v_deleted := v_deleted + v_rows;
  DELETE FROM public.audience_suppression_events
   WHERE provider_event_id IN (
     SELECT provider_event_id FROM public.audience_suppression_events
      WHERE received_at < now() - interval '2 years'
      ORDER BY received_at LIMIT greatest(v_limit - v_deleted, 0)
   );
  GET DIAGNOSTICS v_rows = ROW_COUNT; v_deleted := v_deleted + v_rows;
  RETURN v_deleted;
END;
$function$;

REVOKE ALL ON FUNCTION public.audience_normalize_email(text),
  public.enqueue_audience_sync_for_email(text, boolean),
  public.enqueue_current_profile_audience_sync(uuid),
  public.record_profile_consent_evidence(),
  public.record_audience_suppression(text, text, text),
  public.claim_audience_sync_jobs(integer, integer),
  public.complete_audience_sync_job(bigint, bigint, text, boolean, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.profile_consent_metadata_guard(),
  public.profile_consent_evidence_enqueue(),
  public.enqueue_audience_sync_for_profile(uuid, text, boolean),
  public.quarantine_audience_webhook(text, text, text, text, text, text, boolean),
  public.record_audience_provider_event(text, text, text, text, text, text, text, text, boolean),
  public.reconcile_quarantined_audience_events(integer),
  public.claim_audience_contact_reconciliations(integer, integer),
  public.complete_audience_contact_reconciliation(bigint, boolean, text, boolean, text),
  public.purge_audience_personal_data(integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_current_profile_audience_sync(uuid),
  public.claim_audience_sync_jobs(integer, integer),
  public.complete_audience_sync_job(bigint, bigint, text, boolean, text) TO service_role;
GRANT EXECUTE ON FUNCTION
  public.record_audience_provider_event(text, text, text, text, text, text, text, text, boolean),
  public.reconcile_quarantined_audience_events(integer),
  public.claim_audience_contact_reconciliations(integer, integer),
  public.complete_audience_contact_reconciliation(bigint, boolean, text, boolean, text),
  public.purge_audience_personal_data(integer)
  TO service_role;

COMMENT ON TABLE public.audience_suppression_events IS
  'Provider suppression evidence. Stores a SHA-256 email hash, never a raw email.';
COMMENT ON TABLE public.audience_sync_outbox IS
  'Service-only coalescing desired audience state keyed by normalized email. Raw email is purged 30 days after terminal delivery state.';
COMMENT ON TABLE public.audience_consent_events IS
  'Hash-only consent evidence retained for two years for consent audit; hashes remain personal data and are service-only.';
COMMENT ON TABLE public.audience_contact_reconciliation IS
  'Service-only provider preference reconciliation. Raw email is purged 30 days after terminal state.';

COMMIT;
