-- Durable, idempotent transactional confirmation for free Event RSVPs.
-- This migration only creates the outbox, enqueue trigger, and atomic fair
-- claim function. The provider worker is transactional-email-drain. No cron,
-- provider secret, or external send is activated by applying this file.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- G0 release interlock. Schema apply is intentionally inert: no queue can be
-- claimed until a later protected gate moves this singleton out of quarantine.
CREATE TABLE IF NOT EXISTS public.delivery_runtime_config (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  activation_mode text NOT NULL DEFAULT 'quarantined'
    CHECK (activation_mode IN ('quarantined', 'seed_only', 'live')),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.delivery_runtime_config(singleton, activation_mode)
VALUES (true, 'quarantined')
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.delivery_seed_profiles (
  profile_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  approved_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.delivery_seed_jobs (
  queue_name text NOT NULL CHECK (queue_name IN ('transactional_email', 'audience_sync')),
  job_id bigint NOT NULL,
  approved_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (queue_name, job_id)
);

CREATE TABLE IF NOT EXISTS public.delivery_worker_leases (
  worker_name text PRIMARY KEY CHECK (worker_name IN ('transactional_email', 'audience_sync')),
  lease_token uuid NOT NULL,
  lease_expires_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.delivery_runtime_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_seed_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_seed_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_worker_leases ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.delivery_runtime_config, public.delivery_seed_profiles,
  public.delivery_seed_jobs, public.delivery_worker_leases
  FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.delivery_runtime_config, public.delivery_seed_profiles,
  public.delivery_seed_jobs, public.delivery_worker_leases TO service_role;

CREATE OR REPLACE FUNCTION public.acquire_delivery_worker_lease(
  p_worker_name text,
  p_lease_seconds integer DEFAULT 300
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_token uuid := gen_random_uuid();
  v_seconds integer := least(greatest(coalesce(p_lease_seconds, 300), 30), 900);
BEGIN
  IF p_worker_name NOT IN ('transactional_email', 'audience_sync') THEN
    RAISE EXCEPTION 'unknown delivery worker' USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.delivery_worker_leases(
    worker_name, lease_token, lease_expires_at, updated_at
  ) VALUES (
    p_worker_name, v_token, now() + make_interval(secs => v_seconds), now()
  )
  ON CONFLICT (worker_name) DO UPDATE
    SET lease_token = EXCLUDED.lease_token,
        lease_expires_at = EXCLUDED.lease_expires_at,
        updated_at = now()
    WHERE public.delivery_worker_leases.lease_expires_at <= now();
  IF NOT FOUND THEN RETURN NULL; END IF;
  RETURN v_token;
END;
$function$;

CREATE OR REPLACE FUNCTION public.release_delivery_worker_lease(
  p_worker_name text,
  p_lease_token uuid
)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  DELETE FROM public.delivery_worker_leases
   WHERE worker_name = p_worker_name AND lease_token = p_lease_token
  RETURNING true
$$;

REVOKE ALL ON FUNCTION public.acquire_delivery_worker_lease(text, integer),
  public.release_delivery_worker_lease(text, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_delivery_worker_lease(text, integer),
  public.release_delivery_worker_lease(text, uuid) TO service_role;

CREATE TABLE IF NOT EXISTS public.transactional_email_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('free_event_rsvp')),
  idempotency_key text NOT NULL UNIQUE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  explore_event_id uuid NOT NULL REFERENCES public.explore_events(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'delivered', 'failed', 'cancelled')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at timestamptz,
  claimed_at timestamptz,
  delivered_at timestamptz,
  provider_message_id text,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS transactional_email_jobs_claim_idx
  ON public.transactional_email_jobs (status, available_at, attempts, id)
  WHERE status IN ('pending', 'processing');

ALTER TABLE public.transactional_email_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.transactional_email_jobs FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.transactional_email_jobs TO service_role;

CREATE OR REPLACE FUNCTION public.enqueue_free_rsvp_confirmation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_should_enqueue boolean := false;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_should_enqueue := NEW.status = 'going';
  ELSIF TG_OP = 'UPDATE' THEN
    v_should_enqueue := NEW.status = 'going' AND OLD.status IS DISTINCT FROM 'going';
  END IF;

  IF v_should_enqueue THEN
    INSERT INTO public.transactional_email_jobs (
      kind, idempotency_key, user_id, explore_event_id, available_at
    ) VALUES (
      'free_event_rsvp',
      'free-rsvp/' || NEW.explore_event_id::text || '/' || NEW.user_id::text,
      NEW.user_id,
      NEW.explore_event_id,
      now()
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.enqueue_free_rsvp_confirmation() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS enqueue_free_rsvp_confirmation_trigger
  ON public.explore_event_rsvps;
CREATE TRIGGER enqueue_free_rsvp_confirmation_trigger
AFTER INSERT OR UPDATE OF status ON public.explore_event_rsvps
FOR EACH ROW EXECUTE FUNCTION public.enqueue_free_rsvp_confirmation();

CREATE OR REPLACE FUNCTION public.claim_transactional_email_jobs(
  p_batch_size integer DEFAULT 10,
  p_lease_seconds integer DEFAULT 300
)
RETURNS SETOF public.transactional_email_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_limit integer := least(greatest(coalesce(p_batch_size, 10), 1), 100);
  v_lease_seconds integer := least(greatest(coalesce(p_lease_seconds, 300), 30), 3600);
  v_activation_mode text;
BEGIN
  SELECT activation_mode INTO v_activation_mode
    FROM public.delivery_runtime_config WHERE singleton;
  IF v_activation_mode IS NULL OR v_activation_mode = 'quarantined' THEN
    RETURN;
  END IF;
  RETURN QUERY
  WITH fresh AS (
    SELECT j.id FROM public.transactional_email_jobs j
    WHERE j.attempts = 0
      AND (
        (j.status = 'pending' AND coalesce(j.available_at, j.created_at) <= now())
        OR (j.status = 'processing' AND j.claimed_at < now() - make_interval(secs => v_lease_seconds))
      )
      AND (
        v_activation_mode = 'live'
        OR EXISTS (SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = j.user_id)
        OR EXISTS (SELECT 1 FROM public.delivery_seed_jobs s
                    WHERE s.queue_name = 'transactional_email' AND s.job_id = j.id)
      )
    ORDER BY coalesce(j.available_at, '-infinity'::timestamptz), j.id
    LIMIT ((v_limit + 1) / 2)
    FOR UPDATE SKIP LOCKED
  ),
  retries AS (
    SELECT j.id FROM public.transactional_email_jobs j
    WHERE j.attempts > 0
      AND (
        (j.status = 'pending' AND coalesce(j.available_at, j.created_at) <= now())
        OR (j.status = 'processing' AND j.claimed_at < now() - make_interval(secs => v_lease_seconds))
      )
      AND (
        v_activation_mode = 'live'
        OR EXISTS (SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = j.user_id)
        OR EXISTS (SELECT 1 FROM public.delivery_seed_jobs s
                    WHERE s.queue_name = 'transactional_email' AND s.job_id = j.id)
      )
    ORDER BY coalesce(j.available_at, '-infinity'::timestamptz), j.id
    LIMIT (v_limit / 2)
    FOR UPDATE SKIP LOCKED
  ),
  reserved AS (
    SELECT id FROM fresh
    UNION ALL
    SELECT id FROM retries
  ),
  fill AS (
    SELECT j.id FROM public.transactional_email_jobs j
    WHERE NOT EXISTS (SELECT 1 FROM reserved r WHERE r.id = j.id)
      AND (
        (j.status = 'pending' AND coalesce(j.available_at, j.created_at) <= now())
        OR (j.status = 'processing' AND j.claimed_at < now() - make_interval(secs => v_lease_seconds))
      )
      AND (
        v_activation_mode = 'live'
        OR EXISTS (SELECT 1 FROM public.delivery_seed_profiles s WHERE s.profile_id = j.user_id)
        OR EXISTS (SELECT 1 FROM public.delivery_seed_jobs s
                    WHERE s.queue_name = 'transactional_email' AND s.job_id = j.id)
      )
    ORDER BY coalesce(j.available_at, '-infinity'::timestamptz), j.id
    LIMIT greatest(v_limit - (SELECT count(*)::integer FROM reserved), 0)
    FOR UPDATE SKIP LOCKED
  ),
  chosen AS (
    SELECT id FROM reserved
    UNION ALL
    SELECT id FROM fill
  )
  UPDATE public.transactional_email_jobs j
     SET status = 'processing',
         attempts = j.attempts + 1,
         claimed_at = now(),
         updated_at = now()
    FROM chosen c
   WHERE j.id = c.id
  RETURNING j.*;
END;
$function$;

REVOKE ALL ON FUNCTION public.claim_transactional_email_jobs(integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_transactional_email_jobs(integer, integer)
  TO service_role;

COMMENT ON TABLE public.transactional_email_jobs IS
  'Transactional delivery outbox. Stores identifiers and provider evidence, never email addresses or message bodies.';
COMMENT ON FUNCTION public.claim_transactional_email_jobs(integer, integer) IS
  'Atomically reserves activation-scoped fresh and retry work with fixed batch sharing so neither class can starve the other.';
COMMENT ON TABLE public.delivery_runtime_config IS
  'Singleton release interlock. New delivery queues default to quarantined and require a separately approved mode change.';

COMMIT;
